### ISSUE TITLE
Given object, make roxygen template

### ISSUE THREAD

**Issue by hadley** [klutometis/roxygen#253]
Maybe `roxygen_template()`. Could be used for rstudio and ess.

Should add `@export` and `@examples` by default. Add `@return` if it's a function (incl. generics)

**Comment by ateucher** [comment]
@hadley I don't know if it's helpful or along the lines you're thinking, but I've written a function that I use a lot for this: https://gist.github.com/ateucher/1342ec5c7f2ab3d83c32.

**Comment by hadley** [comment]
Thanks @ateucher - I think that provides a bit too much (since a lot of it will need to be deleted after generating it), but it's helpful.

**Comment by ateucher** [comment]
Gotcha. True, I do end up deleting a lot of it...

**Comment by hadley** [comment]
cc @kevinushey

**Comment by kevinushey** [comment]
FWIW the current RStudio implementation is done through a combination of R and GWT code: https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/common/r/roxygen/RoxygenHelper.java; I'm guessing it's not that helpful for `roxygen2`.

I think the simplest mechanism for RStudio would be something of the form:

1. We given `roxygen2` the current function, as well as its roxygen comment, as a string,
2. `roxygen2` returns us text that we use to replace the current roxygen2 block (or generate the skeleton if none is there).

**Comment by hadley** [comment]
@kevinushey has anything changed here? I'm guessing implementing this in roxygen and getting merged into the IDE would be relatively expensive.

**Comment by hadley** [comment]
Given that RStudio now does this for you, I'm going to close this (old) issue.

**Comment by hechth** [comment]
Will this feature be supported in other editors? I'm specifically looking at VSCode
