### ISSUE TITLE
make it possible to not reference all aliases with @family

### ISSUE THREAD

**Issue by thomasp85** [klutometis/roxygen#283]
It seems @family uses aliases to create cross-linking between documentation. Sometimes this is not desired as it can inflate the size of the see also section if there is cross-linking between classes with a lot of accessors documented with the class.

Is it possible to provide a toggle or a new tag that only takes the name into account?

**Comment by gaborcsardi** [comment]
This would be great indeed. I think it has little use to include 5-10 links that point to the same manual page....

**Comment by gaborcsardi** [comment]
FWIW, it is easy to change to this behavior (obviously): https://github.com/gaborcsardi/roxygen/commit/796fc0b2b8a79241524864f6d23ac50bcdea22a2

I am not sure what the best way would be to provide a toggle.

**Comment by thomasp85** [comment]
What is the status on this? Lack of time, disagreement on the feature, or something else?

**Comment by hadley** [comment]
I'd be happy to review a PR

**Comment by thomasp85** [comment]
Would you prefer a change in behaviour of the current @family tag or the creation of a new e.g. @smallFamily?

**Comment by hadley** [comment]
Change current behaviour
