### ISSUE TITLE
RC method usage line too long

### ISSUE THREAD

**Issue by RyanHope** [klutometis/roxygen#293]
It appears as though the automatically generated usage line for documented RC methods does not auto wrap like normal function usage lines do. The result is a usage line that would not pass CRAN submission. See example blow...

![docs](http://s10.postimg.org/9b52o3a5l/Screen_Shot_2014_10_09_at_12_45_39_PM.png)

**Comment by hadley** [comment]
Can you please provide a minimal reprex?
