### ISSUE TITLE
Problems when specifying S4 methods for class `{`

### ISSUE THREAD

**Issue by rappster** [klutometis/roxygen#296]
I'd like to write an S4 method for class `{` but get the following error when building the package (using roxygen2 for the documentation): 

```
Warning: Q:/home/wsp/rapp2/yamlr/man/getYaml-open-curly-YamlContext.ObjectReference.S3-method.Rd:114: unexpected END_OF_INPUT '
'
Error : Q:/home/wsp/rapp2/yamlr/man/getYaml-open-curly-YamlContext.ObjectReference.S3-method.Rd: Sections \title, and \name must exist and be unique in Rd files
ERROR: installing Rd objects failed for package 'yamlr'
* removing 'Q:/home/apps/rapptools/apps/r/R-3.1.1/library/yamlr'
* restoring previous 'Q:/home/apps/rapptools/apps/r/R-3.1.1/library/yamlr'
```
You can check out the actual (roxygen) code here: [`getYaml`](https://github.com/Rappster/yamlr/blob/master/R/getYaml.r) (lines 140 ff).

Being aware that it generally might not be the best idea to mix informal S3 and S4 classes, I'd nevertheless like to specify a method for class `{` and  document it with roxygen2 if possible. Am I just doing something wrong?

My session info:

```
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] yamlr_0.4.7  bumpr_0.6    testthat_0.9

loaded via a namespace (and not attached):
[1] devtools_1.6.0.9000 tools_3.1.1         yaml_2.1.13    
```

**Comment by hadley** [comment]
This is a rare special case and would be a lot of work to fix. Unfortunately, it's unlikely this will ever rise to the top of my to do list, so I'm going to close in order to not give you false hope.
