### ISSUE TITLE
Merge sections with identical title

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#300]
If two files have entries `@section OBTW` and `@rdname base`, the file `base.Rd` contains two sections titled "OBTW". On the other hand, the "Description" and "Detail" sections are merged. Wouldn't it be a good idea (and feasible) to also merge sections with identical names?

Example package: https://github.com/krlmlr/section.merge.test

Also, the contents are generated in the order of the input file names. In the example above, it's a < b < base, but `base.R` is the "main" source file for `base.Rd`. Perhaps the contents that come from the "main" input file (if there is one) should come before the other contents?

**Comment by Geoff99** [comment]
Not sure if it is exactly what you are looking for in terms of the *natural* order for the merged sections, but  pull request #324, relating to issue #323, would ensure that roxygen2 parses the files in collate (as opposed to alphabetical) order, and hence also generates the documentation in that order. 

If not it might at least give a low effort way of specifying the *natural* order via `@include` tags.
