### ISSUE TITLE
Vignettes roclet

### ISSUE THREAD

**Issue by hadley** [klutometis/roxygen#314]
Should rebuild if compiled is older than source. 

Ping @jjallaire about RStudio UI support when done

**Comment by jjallaire** [comment]
RStudio support is in the current daily (>= v0.99.148). Note that the vignette roclet is only used for roxygen2 >= 4.1.0.9001 so the package still needs a version bump for this to work.

**Comment by jennybc** [comment]
What are you doing here that causes intermediate Markdown of your vignettes to be left behind? I have enabled the Vignettes roclet in Project Build Options in RStudio and it's being run when I document my package, but I'm only getting `vignette.Rmd` --> `vignette.R` and `vignette.html`. No `vignette.md` :cry:

**Comment by rmflight** [comment]
I wouldn't have expected that the intermediate `vignette.md` is kept around @jennybc as this isn't the default behavior in `build_vignettes`. AFAIK `build_vignettes` only does as you describe, keeping the `.R` and `.html` output, and discarding the `.md`.

**Comment by jennybc** [comment]
But I see `.md` for the vignettes here:

<https://github.com/klutometis/roxygen/tree/master/vignettes>

and they appear to have been checked in at same time as the `.html` and `.R` files. That's why I thought maybe this new roclet had some impact on retention of intermediate markdown.

**Comment by Geoff99** [comment]
Hi @jennybc 

**Very** much a guess (I only started to read up on creating vignettes in the last day) but *maybe* you can retain the intermediate files by using `rmarkdown::render` from the Rstudio console.  I *think* render is used "underneath the hood" to generate vignettes.

There is an argument `clean` which defaults to TRUE, but if set to FALSE seems to leave heaps of intermediate stuff lying round.

From `?rmarkdown::render`

> clean TRUE to clean intermediate files created during rendering.

Maybe that would get what you are looking for?  Not quite as painless as running from the RStudio buttons and menus, but it might work.  (I tried on a dummy example and got some `.md` files, but not able to tell if they are the ones you want.)  If I discover an easier or more elegant method I'll update this set of comments. (I have yet to read up on the vignettes roclet).

**Comment by jennybc** [comment]
Thanks @Geoff99. I'm pretty well-versed in the usage of `rmarkdown::render`. What I'm getting at here is whether I'm overlooking some new way to get intermediate `.md` for free when I automate package development tasks, such as updating docs.

**Comment by jennybc** [comment]
Thanks again @Geoff99. Your message prompted me to be more bold re: modifying the YAML of my R Markdown vignette, as I would with any other `.Rmd` document. So this YAML now gets me my intermediate Markdown without any no manual intervention. YAY.

```yaml
---
title: "gspreadr Basic Usage"
author: "Joanna Zhao, Jenny Bryan"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    keep_md: true
vignette: >
  %\VignetteIndexEntry{gspreadr Basic Usage}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```

**Comment by Geoff99** [comment]
Glad I was able to help in some small way @jennybc , even though I didn't have the right answer.  I've learnt something new from your solution and will add looking into YAML more closely to my "to learn about" list.
