### ISSUE TITLE
Citing articles using roxygen2

### ISSUE THREAD

**Issue by fgnu** [klutometis/roxygen#320]
*Note: cross-posted from [here](http://stackoverflow.com/questions/28190868/citing-articles-using-roxygen2) and relates to issue #90.*

----
As in [this question][1], I would like to include citations to articles in function documentation. I use `roxygen2` for all documentation, and it appears that there was a [pull request][2] to `roxygen2` with the necessary functionality, but Hadley turned it down since `roxygen2` was in maintenance mode. Have things changed since then? Is there another way to cite/ include article references stored in BibTeX format?

  [1]: http://stackoverflow.com/q/10207564/1414455
  [2]: https://github.com/klutometis/roxygen/pull/90

**Comment by hummelriegel** [comment]
I would like to see this as well ... it would be great to cite properly and since many mathematical/statistical functions refer to a certain paper/source, this is quite interesting

**Comment by jacobcvt12** [comment]
Bumping this question. I would be happy to update the previous pull request (some of the code - such as the unit tests - is outdated) if this feature would be accepted.

Any thoughts on this, @hadley ?

**Comment by hadley** [comment]
I'd be happy to review a pull request, but I'm unlikely to work on this myself.
