### ISSUE TITLE
roxygen2:roxygenise() overwrote existing Rd files

### ISSUE THREAD

**Issue by adalisan** [klutometis/roxygen#321]
I thought roxygen2:roxygenise()  was not supposed to overwrite Rd files not created by roxygen2. In my case, it did. I was running it for the first time on a R package
> roxygen2::roxygenise(".")
    First time using roxygen2 4.0. Upgrading automatically...
    Writing NAMESPACE
    Writing community.analysis.Rd
    Writing run.analyses.Rd
    Writing top_n_verts_plot.Rd

**Comment by jonassundman** [comment]
When migrating to Roxygen no existing files without roxygen comments should be overwritten. As long as no comments are added, there is no way to indicate that existing files should not be touched.

With existing man pages and `NAMESPACE`, on the *first* run of `document()` any comments added that match existing man pages will be overwritten and if there is any `@export` comments, `NAMESPACE` will be overwritten, too. 

As soon as any man page or `NAMESPACE` has a roxygen comment, any subsecuently added comments will *not* overwrite existing files.

One workaround is to add a dummy file e.g.  `xxx.R` with a minimum of content

    #' xxx
    #' @name xxx
    NULL

and run `document()` once before adding any further comments, to ensure that existing files are not owerwritten.
