### ISSUE TITLE
roxygizing data without "LazyData: true" fails

### ISSUE THREAD

**Issue by talgalili** [klutometis/roxygen#322]
I added to a package a new dataset using "devtools::use_data()", and added the relevant roxygen markup in data.R.
When running "document" (from RStudio), I got the following error: 

```
Error: Failure in roxygen block beginning data.R:1
object 'data_name' not found
Execution halted

Exited with status 1.
```

This was fixed only after I added "LazyData: true" to DESCRIPTION.

p.s: Thanks for the great package :)
Tal

**Comment by hadley** [comment]
IMO you should be using `LazyData: true` anyway, so fixing this is not high priority for me.
