### ISSUE TITLE
Clarify overwrite prevention.

### ISSUE THREAD

**Issue by coolbutuseless** [klutometis/roxygen#327]
I just spent 10 minutes trying to workout what "NAMESPACE not generated by roxygen2. Skipped." actually meant.

I had interpreted it as "roxygen2 is not configured to write a NAMESPACE file" and I then spent some time trying to tweak rstudio/project options.

After a bit I realised it was trying to say: "The existing NAMESPACE file was not generated by roxygen2. Not going to overwrite it."

Could this warning text be adjusted to clarify the meaning?  e.g. "The existing NAMESPACE file was not generated by roxygen2, and will not be overwritten."

It's probably getting a bit verbose, but since Rstudio -> new project -> new package  automatically creates a NAMESPACE file, this is going to be a trip hazard.

**Comment by hadley** [comment]
Sure. Want to do a pull request?

**Comment by coolbutuseless** [comment]
sure.

**Comment by dmpe** [comment]
Hi @coolbutuseless , 

I was doing some work in there and seeing your issue I have create an improvement. I hope you don't mind me doing it.
