### ISSUE TITLE
indent issue in the usage of Rd

### ISSUE THREAD

**Issue by zhilongjia** [klutometis/roxygen#332]
if there is no @usage in the R file, roxygen will generate the usage automatically. This issue is the indent is two spaces if the usage is longer than one line in Rd file, while BiocCheck::BiocCheck in Bioconductor requires 4 spaces.

**Comment by hadley** [comment]
To me, the easier solution would be for BioCheck to be a bit more relaxed about the number of spaces.

**Comment by sthawinke** [comment]
For me, this issue persists.

**Comment by LiNk-NY** [comment]
Hi @hadley,

It is pretty relaxed in `BiocCheck` given that it is a `NOTE`:

```
* NOTE: Consider multiples of 4 spaces for line indents
```

I think this should be left up to the users to possibly set a package-wide option. 
Thanks.
