### ISSUE TITLE
Feature request: using markdown in roxygen code

### ISSUE THREAD

**Issue by rappster** [klutometis/roxygen#336]
`roxygen2` is one of my favorite tools for package development. Thanks a lot for coming up and maintaining it!!

What do you think of optionally being able to use markdown inside roxygen code? As this [post](http://stackoverflow.com/questions/15539851/convert-markdown-to-rd-or-define-custom-markdown-conversion-rules) outlines this would make documenting even more fun.

**Comment by hadley** [comment]
See discussion at #244
