### ISSUE TITLE
Create NAMESPACE entries in the order given by DESCRIPTION

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#339]
Does the order of the `import` entries matter? If yes, probably the package order given by the `Depends` and `Imports` declarations should be reflected in the autogenerated `NAMESPACE`.

Example: When a package imports both `plyr` and `dplyr` and declares `#' @import plyr` and `#' @import dplyr`, they are nevertheless imported in alphabetic order, contrary to the suggestion to import `plyr` first.

Please advise.

**Comment by hadley** [comment]
It does matter but if you're relying on it you're in for a world of pain.

**Comment by krlmlr** [comment]
...which shows in warnings during build and install. So, the symbols imported through `NAMESPACE` should be unique.

Would you support an `@importExcept` tag, like `@importFrom` but importing everything *except* the names given?

**Comment by hadley** [comment]
I'd prefer to encourage people to use explicit `foo::bar` or `@importFrom foo bar`

**Comment by krlmlr** [comment]
`@importExcept` still would expand to *many* `importFrom()` entries in the `NAMESPACE` file. Collisions seem to be checked when attaching or loading the package, and also by `R CMD check`. (Try adding `import(plyr,dplyr)` to the `NAMESPACE` of a package.) Why would you voluntarily give up this comfort (and encourage others), given that there exist mechanisms that verify unambiguity?

**Comment by hadley** [comment]
Because it's better to be explicit about where functions outside your package are coming from.

**Comment by krlmlr** [comment]
I see your point, still I've summarized the idea in #343. Thanks for your feedback so far.
