### ISSUE TITLE
Parse PackageRoxygenize entry from .Rproj file

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#341]
In an RStudio-oriented environment, currently the default roclets can be specified in two places:

- `DESCRIPTION` file, `Roxygen` element
- RStudio project, `PackageRoxygenize` entry

Should `roxygen2` also attempt to parse an `.Rproj` file to allow a single-source definition of what to do by default?

**Comment by hadley** [comment]
I think people tend to use one or the other. I'm not too worried about the duplication.
