### ISSUE TITLE
Proposition: @importExcept tag

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#343]
A new tag `@importExcept` with the following semantics:

- `@importExcept package` adds an entry `importFrom(package,symbol)` for every symbol that `package` exports
- `@importExcept package exception1 exception2` adds an entry `importFrom(package,symbol)` for every symbol that `package` exports, except for symbols `exception1` and `exception2`

Rationale: If I know I'll be using many functions from a specific package, I'm inclined to simply say `@import package` and get done with it. However, there are drawbacks to this approach:

- If two imported packages have a symbol with the same name, warnings are issued when building or loading such a package
- From [R-exts](http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Specifying-imports-and-exports): "Using importFrom selectively rather than import is good practice."

Benefits: Drop-in replacement for `@import` that shows explicitly (at least in the generated `NAMESPACE`) what is imported in the end, and allows safe resolution of collisions.

Drawbacks: Performance impact unclear.

**Comment by hadley** [comment]
Personally, I wouldn't use this (because I prefer to import the smallest possible set of things), but I'm not fundamentally opposed to it. (i.e. I won't implement it, but I'd review a PR)

**Comment by lcolladotor** [comment]
I found this old issue when searching how to specify `import(pkg, except = c('a', 'b'))` which does work in R. I first found about how to do this in a bioc-devel thread: https://stat.ethz.ch/pipermail/bioc-devel/2016-September/009750.html.

**Comment by hadley** [comment]
You can always use `@rawNamespace`

**Comment by lcolladotor** [comment]
Awesome, thanks! I didn't know about `@rawNamespace`. For others that find this thread, you can see how to use this tag at https://blog.rstudio.org/2015/10/29/roxygen2-5-0-0/
