### ISSUE TITLE
Support for decorators

### ISSUE THREAD

**Issue by Mullefa** [klutometis/roxygen#344]
Having no understanding of how `roxygen` works I don't know if this is possible, but it'd be great to have support for something similar to Python's [decorators](http://thecodeship.com/patterns/guide-to-python-function-decorators/).

Example 1:

```R
say_hello <- function(f) {
  function(...) {
    cat("hello\n")
    f(...)
  }
}

#' @export
#' @decorator say_hello
say_hello_and_goodbye <- function() {
  cat("goodbye\n")
}
```

Example 2:

```R
say <- function(string) {
  function(f) {
    function(...) {
      cat(string)
      cat("\n")
      f(...)
    }
  }
}

#' @export
#' @decorator say("hello")
say_hello_and_goodbye <- function() {
  cat("goodbye\n")
}
```

**Comment by hadley** [comment]
I don't think roxygen could do that, and it doesn't seem so important in R since you can do the decoration yourself:

```R
say_hello_and_goodbye <- say("hello")(function() {
  cat("goodbye")
})
```

**Comment by Mullefa** [comment]
You can do 'self decoration' in Python too. I _think_ the main advantage is that is is more expressive, gives a nice level of abstraction, and makes the programmer think in a differently (correctly?) about their code. But fair enough if roxygen can't do that; I thought it might be pushing it somewhat.
