### ISSUE TITLE
Proposal: New @Todo Tag

### ISSUE THREAD

**Issue by dmpe** [klutometis/roxygen#345]
Hi @hadley, 
I would like to see `@todo` tag being implemented. Any chance of accomplishing it? This can be very handy when creating new packages (like I do now) when there is e.g. more work required on some function & its behaviour but not having time (etc.) for doing it now. 

Are you fundamentally opposed, because maybe I would try to create a pull request for it. 

Something like 
http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.todo.pkg.html
or 
http://usejsdoc.org/tags-todo.html

**Comment by hadley** [comment]
I'm not opposed, so I'd be happy to review a pull request. What would the output of `@todo` be?

**Comment by dmpe** [comment]
Great to hear that!
At first, I would think of `@todo` tag collapsing only "their values into a single string", i.e. just what the `@note`, `@description` etc. tags do. [here link to code to what I mean](https://github.com/klutometis/roxygen/blob/master/R/rd-tag-api.R#L97).

I would have this:
```
@todo - Improve documentation/examples here 
```
rendered exactly in the same way as `Description` currently does. 

The other option would be to render it the way how `@return` does (`Value` in the `.Rd` files). That would, of course, mean I could have more `@todo` tags for the same function. 

In my case, I would like to see probably only the first variant. Any you ?

**Comment by dmpe** [comment]
Hi @hadley, 
So according to this http://developer.r-project.org/parseRd.pdf, there is no build-in LATEX support for `@todo` tag.
Does it mean that I will need to implement a parser for it ? Like e.g. here https://github.com/klutometis/roxygen/pull/90/files

Thanks.

**Comment by hadley** [comment]
Why not just put it in a `\section{To do}`?  I think you should start by sketching out what the output Rd should look like

**Comment by dmpe** [comment]
Hi @hadley, 
Exactly I was looking for just that. So there is no reason to make a new one. Thanks. Closing

**Comment by dmpe** [comment]
Just for myself:
```
#' @section TODO: or more URLs  
```
