### ISSUE TITLE
Bug: @describeIn fails when combined with @rdname

### ISSUE THREAD

**Issue by thomasp85** [klutometis/roxygen#346]
When documenting S4 generics and methods I find that I often want to add several generics to the same documentation file (often setters and getters). In some circumstances it makes sense to change the name of the generated rd file to reflect this multiplicity.

When having @rdname in a generic and then using @describeIn for a method I wish to include in the documentation I get the following error:

    Error: Failure in roxygen block beginning pgFull.R:118
    Don't know how to describe s4method in data.

It seems adding @rdname messes up how roxygen infers the type. Removing @rdname and changing @describeIn accordingly removes the error...

**Comment by hadley** [comment]
You should either use `@describeIn` or `@rdname`, not both

**Comment by thomasp85** [comment]
This is not within the same roxygen block. One block defines the name of the rd file using @rdname, another block references this using @describeIn. Shouldn't this be allowed?

**Comment by hadley** [comment]
Ooooh, I see what you mean.

**Comment by hadley** [comment]
Can't you just use the rd name in the describe in tag? It doesn't look like any other behaviour will be easy to add, but if you create a reproducible example, I'll definitely take more of a look.

**Comment by thomasp85** [comment]
I'll take a look at creating a minimal example - it's been a while...

**Comment by hadley** [comment]
Closing, but feel free to ping me if you still care

**Comment by nick-ulle** [comment]
This issue still affects roxygen 6.0.1.

Here's a minimal example:
```r
#' @rdname MyClass
setClass("abcMyClass")

#' @describeIn MyClass Show an abcMyClass object.
setMethod("show", signature(object = "abcMyClass"), function(object) {
  cat("MyClass\n")
})
```

**Comment by hadley** [comment]
Please file a new issue. Commenting on a closed issue is unlikely to catch my attention
