### ISSUE TITLE
Proposal: New @familyref tag

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#347]
So that items "outside" a family can link to all items of a family.

Example:

```
#' @family fam
"a"

#' @family fam
"b"

#' @familyref fam
"c"
```

The docs to `c` would contain "See also" entries to both `a` and `b`.

I wonder if this is useful, or if this can be implemented using existing features.

**Comment by hadley** [comment]
I'd definitely review a pull request for this, but it's not high enough up on my priorities that I'd implement it myself.
