### ISSUE TITLE
Move travis to proper R "version"

### ISSUE THREAD

**Issue by dmpe** [klutometis/roxygen#353]
Hi @hadley, 

Is there any reason why one should not move travis to `R` style description. Instead of having the "old" C one style. 

Just by looking at `travis.yml` I cannot think about any.

**Comment by dmpe** [comment]
#351

**Comment by hadley** [comment]
No reason, just haven't updated yet.

**Comment by dmpe** [comment]
Ok, I have already opened a pull request here https://github.com/klutometis/roxygen/pull/355
