### ISSUE TITLE
'dontrun' example file

### ISSUE THREAD

**Issue by cdeterman** [klutometis/roxygen#359]
Is there any way to use the `@example` and `\dontrun`?  It is quite simple to use the normal `@examples` and `\dontrun` but the examples I work with can be more verbose and I don't want it cluttering my code.  They may also be used in other functions documentation.  However, I don't want the examples to be run.  Is there a way to accomplish this?

test.R
```r
# this does not work
#' @title test
#' @example \dontrun{examples/test_example.R}
test <- function(){
    print("hello")
}
```
```r
# this does
#' @title test
#' @examples 
#' \dontrun{
#' test()
#' }
test <- function(){
    print("hello")
}
```

test_example.R
```r
test()
```

P.S.  I posted this question of [SO](http://stackoverflow.com/questions/31412724/roxygen2-how-to-not-run-example-file) but it wasn't receiving much attention.

**Comment by hadley** [comment]
No, sorry. You'd have to put the `\dontrun{}` inside `test_example.R`
