### ISSUE TITLE
Function's usage does not get documented when its class attribute is set

### ISSUE THREAD

**Issue by lionel-** [klutometis/roxygen#361]
In the following situation:

```r
#' @rdname my_doc
#' @export
my_fun <- function(x) NULL
class(my_fun) <- "my_class"
```

`my_fun()`'s usage does not get documented in `my_doc`.

Note that the usage will get documented if I add the "function" class:
```r
class(my_fun) <- c("function", "my_class")
```
Ideally, this should not be necessary since "function" is not a class but a type.

**Comment by lionel-** [comment]
I've only a very limited understanding of roxygen's code so maybe I'm mistaken but from [usage.R](https://github.com/lionel-/roxygen/blob/master/R/usage.R), it looks like it's because the code relies on S3 dispatch.

Non-object functions get implicitly dispatched as `function` objects, but that's not the case for functions with a class attribute.

@hadley Given this caveat, maybe the best practice is to add an explicit `function` class to function objects after all? I've relied on S3 dispatch in other code as well so that is probably the more robust course to avoid strange bugs.

**Comment by hadley** [comment]
Yeah, I agree that we should probably add an explicit "function" to the class.
