### ISSUE TITLE
Preref parser for auto-detected title, description and details

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#364]
The registered parsers are only called if the `@title`, `@description` and `@details` tags are used explicitly, but not if they are just extracted from the first and second paragraphs and the rest.

It would be great if they could be called from `process_description` as well.

**Comment by hadley** [comment]
PR would be great :)

**Comment by gaborcsardi** [comment]
This part is a bit messy in roxygen. First the file is split on `@`, and all tags call their preref parsers. The initial part does not have a `@` tag, so that is left out from this process, and passed along as `introduction`. Then, at a higher level, `process_description` is called, which splits this initial part into `@title`, `@description` and `@details`.

`@details` is especially tricky, because `process_description` merges the `@details` tag (if present) with the leftover of the intro, so the preref parser is sometimes only called on part of the real `@details`.

I think the splitting done in `process_description` should be done in `parse.preref`, conceptually. Instead of or in addition to just passing along `introduction`. As I see it, this is a clean change, `process_description` does not do anything else in addition to the splitting.

Please let me know if I am missing something.

**Comment by hadley** [comment]
That seems reasonable to me.
