### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#365]
I was wondering if you would like to have https://github.com/gaborcsardi/maxygen within roxygen. I think it would make sense.

It adds two bigish dependencies: `xml2` and `commonmark`.

If you like it, then let's discuss what would be the best way.

**Comment by jeroenooms** [comment]
That would be awesome. Roxygen already depends on `Rcpp` and `stringi` so I guess adding `xml2` and commonmark won't hurt.

**Comment by hadley** [comment]
Yessssssssssss.

The main challenge (apart from converting md to Rd) is to figure out a way to turn it off or on per project. Maybe use the `Roxygen` field in the DESCRIPTION.

I bet it would also substantially improve adoption if you provided a Rd -> md converter that you could run on your existing roxygen comments.

**Comment by gaborcsardi** [comment]
md -> Rd conversion is really easy, because commonmark parses the md into an XML tree, that it trivial to translate to Rd. These are all the XML tags currently: https://github.com/gaborcsardi/maxygen/blob/6287fe5964589e7496e0cff9c652e4a325cd1589/R/markdown.R#L54

As for the Rd -> md converter, I am not sure. Why would you convert to md if you already have it working with the current syntax?

The good thing is, you can turn on md formatting, and still use the old files, the `\code{}` etc. command are preserved, so unless you have valid md markup in your old files, which is improbable, you are fine with keeping the old style and adding the new docs in md. On the other hand it would make sense for `Rd2roxygen` to convert into md.

OK, so I can make a PR, with an option in DESCRIPTION/Roxygen, and also an argument to `roxygenize`, maybe. Do you want to be able to turn it on/off from the chunk?

Btw. it would be great to fix #364, I can also submit a PR for that.

**Comment by hadley** [comment]
Ah, if Rd works as is in md, that's cool. We can default to having md conversion on, and then give an option for people to turn off if it's annoying (and/or maybe a `@nomd` tag?)

**Comment by gaborcsardi** [comment]
@hadley We can think about cases when Rd is meaningful md syntax. E.g. in formulas, where you have multiple lower indices, you can have stuff like `\eqn{x'_{1} + x_{2}}` and then that might be interpreted as emphasis in markdown. Similarly with stars. They need to be somewhat special, e.g. `\eqn{x_1 + x_2}` is fine.

We can also just turn off `_` and `*` within formulas. 

I cannot really think of other bad examples, but I am sure there some more. We can even turn off markdown within any Rd `\command{}`.

**Comment by gaborcsardi** [comment]
I would probably start with turning markdown off within `\eqn{}` and `\deqn{}` and addinf a `@nomd` tag. Then we'll see.

We can even re-roxygenize all CRAN packages and compare the old and new output. They should be the same, ideally. This seems a lot of work, but it is not completely unreasonable.

**Comment by leeper** [comment]
Just saw this and I love it (one of my big holdouts about adopting roxygen is the need to mix Rd and rmarkdown for any kind of complex doc page).

Perhaps if an Rd -> md conversion is needed, @yihui could add something to https://github.com/yihui/Rd2roxygen to accommodate the maxygen formatting? That's probably a one-time action that any particular user would take, so I don't see a reason to have it as a feature of either roxygen2 (or maxygen).

**Comment by hadley** [comment]
@gaborcsardi how's progress on this? I feel like you asked for my comments somewhere, but I can't find the right issue.

**Comment by gaborcsardi** [comment]
We discussed the links, here: https://github.com/gaborcsardi/maxygen/issues/3
I guess I could implement the links and then put together a PR.
