### ISSUE TITLE
Roxygen2 is not case sensetive

### ISSUE THREAD

**Issue by RomanTsegelskyi** [klutometis/roxygen#368]
I run into a problem with functions that have the same name, but have different case. Here is a toy example:
```r
#' Create a multitable used for rendering objects from rms package
#' @export
test <- function() {}

#' Create a multitable used for rendering objects from rms package
#' @export
Test <- function() {}
```
Only `test.Rd` would be generated.

While it's not a problem for such example, it becomes a problem for S3 methods. For example, there `glm` in `stats` and `Glm` in `rms` models. And I was working for adding support for those modes in pander - https://github.com/Rapporter/pander/pull/212. So I have `pander.glm` and `pander.Glm` functions. But when I try to generate documentation, only one `pander.glm.Rd`, which correspords to `pander.Glm` will be generated.

**Comment by hadley** [comment]
Are you sure it's not your file system?

**Comment by RomanTsegelskyi** [comment]
Yeah, it seems like it is. What might be the reason?

```r
> roxygenize()
Writing NAMESPACE
Writing pander.glm.Rd
Writing pander.Glm.Rd
Deleting test.Rd
> list.files(path = 'man', pattern = '[gG]lm')
[1] "pander.glm.Rd"         "pander.summary.glm.Rd"
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] tools     grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] roxygen2_4.1.1       pander_0.5.3         gtable_0.1.2         tseries_0.10-34   
```

**Comment by hadley** [comment]
OS X is a case insensitive file system, so you can't have two files only differing in case. You'll need to override the default file name choice with `@rdname`
