### ISSUE TITLE
Proposal: New @since tag

### ISSUE THREAD

**Issue by yu-iskw** [klutometis/roxygen#369]
It would be nice to support a tag to specify since when (version or time) an entity is available. The tag corresponds to `\since{}` doxygen command.
http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsince

### Example:

```
#' @rdname foo
#' @since 1.5.0
```

**Comment by hadley** [comment]
What would the output in terms of Rd look like?

**Comment by yu-iskw** [comment]
Ah, I'm sorry. Unlike doxygen, Rd doesn't have a command to specify since when an entity is available.
https://cran.r-project.org/doc/manuals/R-exts.html#Documenting-functions
