### ISSUE TITLE
some way to pass through if statements to NAMESPACE?

### ISSUE THREAD

**Issue by bbolker** [klutometis/roxygen#371]
I'm trying to figure out some way to get additional material into the `NAMESPACE` file such as:

```
if(getRversion() >= "3.3.0") {
    importFrom("stats", sigma)
} else {
    export(sigma)
}
```

Any thoughts on fixes/workarounds/ways to incorporate this in a roxygen workflow?

**Comment by fabian-s** [comment]
I'm having a similar issue as well. Any ideas?

**Comment by hadley** [comment]
Probably needs a new tag that just inserts raw namespace code
