### ISSUE TITLE
Import only roclet

### ISSUE THREAD

**Issue by hadley** [klutometis/roxygen#372]
When you add a new method to a generic defined in another package, you need to first import that generic. This makes it easy to get stuck in a state (e.g. https://github.com/ThierryO/testS4) that you can't easily get out without modifying the `NAMESPACE` by hand. 

One solution would be to have a separate roclet that works like `collate`. I think the translation from all the import directives is straightforward, so this should work. (But it can't do all namespace directives because `@export` definitely needs the loaded code)

**Comment by richierocks** [comment]
I'm currently working around this issue with the script here:

https://gist.github.com/richierocks/21b29f13320716ba6fca

The code isn't yet robust enough to go into roxygen, but works well enough for people that need a quick fix.

cc: @ThierryO

**Comment by hadley** [comment]
This will require:

* A C++ function, `find_imports()` analogous to `find_includes()` that parses all R files and extracts any tag starting with imports

* An `update_imports()` function analogous to `update_collate()`, which writes out a simple `NAMESPACE` listing all imported functions (provided any exist, and adding the correct comment so roxygen can later overwrite)

* Updates to `roxygenise()` and `devtools::document()` to collate, update imports, then roxygen. Given that pkgload now exists, it may now be possible to move more of the logic in to roxygenise so that `document()` becomes a thinner wrapper

**Comment by hadley** [comment]
I'm now thinking that it will be better to re-use the parse data that we have to generate later on. I think it will be possible to split the process into two pieces - one that works purely with parse data, and the other that also uses the package environment.
