### ISSUE TITLE
Add docs for Rcpp modules

### ISSUE THREAD

**Issue by dselivanov** [klutometis/roxygen#374]
May be I missed something, but it was hard to find how to `@export` **Rcpp module**. Only relevant example I found was this [issue](https://github.com/klutometis/roxygen/issues/148).
As I understand, regular Rcpp-roxygen2 annotations don't work in this case and we should write `@export` somewhere in package R files.
```r
#' @name ModuleName
#' @export
```
It would be nice if somebody (who has more experience with Rcpp modules) add example into vignette about such use case. I can try to write paragraph about that, but I'm afraid it will be not most correct solution. 
Here is simple example, adapted from Rcpp-modules vignette:

**Uniform.cpp**
```c++
using namespace Rcpp;
class Uniform {
public:
  Uniform(double min_, double max_) : min(min_), max(max_) {}
  NumericVector draw(int n) const {
  RNGScope scope;
  return runif( n, min, max );
  }
  double min, max;
};
double uniformRange( Uniform* w) {
  return w->max - w->min;
}
RCPP_MODULE(UnifModule) {
  class_<Uniform>( "Uniform" )
  .constructor<double,double>()
  .field( "min", &Uniform::min )
  .field( "max", &Uniform::max )
  .method( "draw", &Uniform::draw )
  .method( "range", &uniformRange )
  ;
}
```
**Exporter.r**
```r
#' Rcpp module: UnifModule
#' @name UnifModule
#' @export
NULL
loadModule("UnifModule", TRUE)
```

**Comment by hadley** [comment]
I don't know how to do this either - I think it unfortunately falls through the gaps as no one uses both roxygen and Rcpp modules

**Comment by pommedeterresautee** [comment]
https://github.com/RcppCore/Rcpp/issues/617
