### ISSUE TITLE
commted out chunks even when including roxygen tags should be ignored

### ISSUE THREAD

**Issue by markheckmann** [klutometis/roxygen#375]
Building from within RStudio using `devtools` and `roxygen2` (v. 4.1.1) I noticed that commented out chunks including roxygen tags, like the one below, cause an `export("#")` entry in `NAMESPACE` which will cause an error during building. It would be nice if commented out code including tags would be ignored by roxygen.

    # #' foo
    # #' @export
    # foo_1 <- function(x){}

**Comment by hadley** [comment]
I can't reproduce the problem
