### ISSUE TITLE
Pass the documented object to preref parsers

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#377]
For flexibility. If it is OK, I can submit a pull request.

**Comment by krlmlr** [comment]
I could use that, too. Thanks for considering.

**Comment by hadley** [comment]
Oops, wrong issue.

**Comment by hadley** [comment]
Yeah, that seems reasonable to me

**Comment by hadley** [comment]
I'd be willing to consider this, but it's harder than I first thought since creating the object currently requires the parsed block (in order to figure out if a function is actually an S3 method which wasn't detected automatically).
