### ISSUE TITLE
feature request: Support for conditional @importFrom

### ISSUE THREAD

**Issue by richierocks** [klutometis/roxygen#378]
Some base-R functions are not available under all OSes.  If you want to use these functions in a cross-platform way, then you need to conditionally import the function.

Full discussion on [r-package-devel](https://stat.ethz.ch/pipermail/r-package-devel/2015q3/000478.html).

For example, `utils::win.version` is only available under Windows.  If your package includes a function that calls this, the NAMESPACE file should contain a conditional importFrom:

```{r}
if(.Platform$OS.type == "windows") {
importFrom(utils, win.version)
}
```

The way I'd typically write such a function would be this:

```{r}
#' An OS-specific fn
#' 
#' This  fn uses win.version
#' @return The value of win.version, or NULL.
#' @importFrom utils win.version
#' #export
f <- function()
{
  if(.Platform$OS.type == "windows")
  {
    win.version()
  }
}
```

AFAIK, there currently isn't a way to specify the `@importFrom` line to make it conditional.  This would be a nice feature.

Possible syntax would be `#' @importFrom utils win.version .Platform$OS.type == "windows"`.  That is, anything after the function name up to a newline would be considered as a condition to go in an if block.

**Comment by jgrn307** [comment]
I'd like to +1 this.  A good example is trying to:
#' @importFrom utils shortPathName
This is only available in Windows, not in other OSs.  My code is clever enough to not use this function, but the CRAN checks get caught on this.  Catch 22.  If I have this line, the package doesn't build on non-Windows.  If I don't have it, I get yelled at by the R CMD CHECK

**Comment by hadley** [comment]
I think it's better to just do foo::bar and avoid the conditional include. But roxygen does need a way to include literal text in the namespace.

**Comment by jgrn307** [comment]
Is this allowed in CRAN submissions?

**Comment by hadley** [comment]
Yes

**Comment by bbolker** [comment]
related to https://github.com/klutometis/roxygen/issues/371
