### ISSUE TITLE
LaTeX Errors when creating PDF version

### ISSUE THREAD

**Issue by gregmacfarlane** [klutometis/roxygen#379]
I'm trying to check the develop branch of a [package](https://github.com/gregmacfarlane/censusr/tree/develop), and I get a `WARNING` from LaTeX errors.

    * checking PDF version of manual ... WARNING
    LaTeX errors when creating PDF version.
    This typically indicates Rd problems.

My log is stored [in this gist](https://gist.github.com/gregmacfarlane/8ba3c4511d1a7b54a550). The log only has three complaints:

  - No `.aux`, which wouldn't exist on the first pass anyways
  - No `.toc`, which also wouldn't exist on the first pass
  - An overfull \hbox. 

Nothing seems wrong with the final manual, and these are issues that I would normally just ignore when writing a doc.

**Comment by hadley** [comment]
Given that there are no latex errors in the log, I'd suspect the problem lies elsewhere
