### ISSUE TITLE
@export doesn't export S3methods correctly

### ISSUE THREAD

**Issue by NattyE** [klutometis/roxygen#380]
I am having a similar issue to the comments made on @hadley 's answer in this SO thread: <http://stackoverflow.com/questions/7198758/roxygen2-how-to-properly-document-s3-methods>

If we take the SO example:
    
    #' A description of MyHappyFunction
    #'
    #' A details of MyHappyFunction
    #'
    #' @title MyHappyFunction: The my happy function
    #' @param x numeric number
    #' @param ... other arguments
    #' @examples
    #' a <- 1
    #' class(a) <- "lm"
    #' MyHappyFunction(a)
    #' @export
    MyHappyFunction <- function(x, ...){
      UseMethod("MyHappyFunction")
    }
    
    #' @export
    MyHappyFunction.lm = function(x, ...) {
      # do some magic
    }
    
    #' @export
    MyHappyFunction.default = function(x, ...) {
      # do some magic
    }

What will happen on my machine is that my `NAMESPACE` file will look like this:

    S3method(MyHappyFunction,lm)
    S3method(MyHappyFunction,default)
    export(MyHappyFunction)

But if I try to use `edit(MyHappyFunction.lm)` when I have the package loaded, I cannot. R simply tells me that `Error in edit(MyHappyFunction.lm) : object 'MyHappyFunction.lm' not found`. I have similar issues with `fix()` in that it will not find the function, it just returns a blank function instead. I can get around these issues by explicitly exporting the methods, e.g.

    #' @export MyHapppyFunction.lm

which will generate the following `NAMESPACE`:

    export(MyHappyFunction.lm)

Am I missing something?

**Comment by hadley** [comment]
Yeah, you shouldn't expect edit to work. (And you should probably avoid it in any non-toy workflow)

**Comment by NattyE** [comment]
`edit()` is useful for debugging purposes (as is `fix()`

This still doesn't seem correct to me. If I create a new method called `my_method` for say, `plot`, then when I `@export` `plot.my_method`, it will export as an `S3method` and furthermore, I will be able to `edit` and `fix` `plot.my_method`. So the behaviour of `@export` is not the same when generating your own generics compared to the behaviour of base generics.

**Comment by hadley** [comment]
Using fix and edit is A BAD IDEA. Because they can't reach into the namespace in the right way to get S3 methods, amongst other reasons. Roxygen2 is correct here. You shouldn't be exporting methods as functions.
