### ISSUE TITLE
Inherit anything

### ISSUE THREAD

**Issue by hadley** [klutometis/roxygen#384]
* [x] section (#299)
* [x] returns (#298)
* [ ] slots
* [ ] fields
* [ ] methods (#145)
* [x] description
* [x] details
* [x] params
* [x] seealso
* [x] references

**Comment by cfhammill** [comment]
Would it also be possible to get `@inheritParam` for a single parameter? May be useful when parameters are inherited from multiple functions with many shared parameter names. This way you don't have to specifically worry about the order of the tags.

**Comment by hadley** [comment]
Probably not, but I'll keep it in mind as I work through the code.

**Comment by hadley** [comment]
Inheriting slots and fields will be slightly complicated because they are nested in sections (in Rd files).

You probably will want to be able to inherit sections by name, so they might be more easily handled with their own `@inheritSections` tag. An additional complication is that section names tend to have spaces in them, so using space delimiters (like other tags) isn't going to work. Use commas instead?

**Comment by krlmlr** [comment]
How about a simple `@inheritSection` that expects one argument?

**Comment by hadley** [comment]
@krlmlr yeah, that's what I was thinking except I forgot to write it down anywhere

**Comment by hadley** [comment]
Cleaning up this issue, and moving all `@inheritSection` related stuff to #513

**Comment by hadley** [comment]
I'm not going to both with the S4/ref class stuff for now
