### ISSUE TITLE
S4 class and package with same name, duplicate alias warning in check

### ISSUE THREAD

**Issue by agrueneberg** [klutometis/roxygen#403]
My package contains an S4 class with the same name as the package:

```R
#' Test package
#' 
#' @name Test
#' @docType package
NULL

#' Test class
#' 
Test <- setClass("Test")
```

If I run `devtools::check()` I get the following warning: `Rd files with duplicated alias 'Test'`. And indeed, both `man/Test-class.Rd` and `man/Test.Rd` contain the same `\alias{Test}` line.

*Writing R Extensions* recommends to only use `pkgname` as an additional `\alias` if a topic named `pkgname` does not exist in another `Rd` file (see https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Documenting-packages). Is there a way to prevent roxygen from writing the `Test` alias in `man/Test.Rd`?

**Comment by agrueneberg** [comment]
Looked at the source code today, this did the trick:

```r
#' Test package
#' 
#' @name Test
#' @docType package
#' @aliases NULL
NULL
```

**Comment by hadley** [comment]
Glad you figured it out :)
