### ISSUE TITLE
roxygen2 4.0 creates empty export

### ISSUE THREAD

**Issue by braverock** [klutometis/roxygen#406]
current code creates line:

export("")

in the NAMESPACE file, 

leading to an unbuildable package.  Prior versions of roxygen2 did not do this (and were used to build the documentation for the CRAN version of PerformanceAnalytics and PortfolioAnalytics)

**Comment by hadley** [comment]
Can you please provide a reprex? Or at least a link to a package with the problem.

**Comment by braverock** [comment]
On Wed, 2015-10-21 at 11:55 -0700, Hadley Wickham wrote:
> Can you please provide a reprex? Or at least a link to a package with
> the problem.

I pointed to both PerformanceAnalytics and PortfolioAnalytics in the
report.

PerformanceAnalytics contains over 200 .R files.  roxygen2 is giving no
indication where your new parser is inserting that empty export("") line
from.

**Comment by hadley** [comment]
Link? Are they on github?

**Comment by braverock** [comment]
On Wed, 2015-10-21 at 12:26 -0700, Hadley Wickham wrote:
> Link? Are they on github?

They are on CRAN and R-Forge.

The CRAN versions documentation for both packages were built using CRAN
versions of roxygen2, without errors.
> 
> 

-- 
Brian G. Peterson
http://braverock.com/brian/
Ph: 773-459-4973
IM: bgpbraverock

**Comment by braverock** [comment]
On Wed, 2015-10-21 at 12:26 -0700, Hadley Wickham wrote:
> Link? Are they on github?

I suspect that the issue may be related to trailing whitespace in the
@export line because trailing whitespace in the @rdname line causes
roxygenize errors as well.  

I'm attempting to remove those instances now to see if that resolves the
issue.
> 

-- 
Brian G. Peterson
http://braverock.com/brian/
Ph: 773-459-4973
IM: bgpbraverock

**Comment by hadley** [comment]
That's likely to be the issue - since I changed the parser I may have accidentally changed whitespace behaviour. I'll fix it tomorrow

**Comment by braverock** [comment]
related problems also seem to be a trailing roxygen comment, e.g.

#' rdname somethingOrOther
#'
function somethingDifferent(...)

these will cause roxygenize to try to add spaces in names.  Assuming you're using a centralized parser, the problems could be related.

**Comment by hadley** [comment]
Yeah, that will also get flagged as trailing whitespace.

**Comment by braverock** [comment]
even after removing all trailing whitespace and trailing roxygen comments, some other minor annoyances are resolved, (so whitespace is still a problem in current roxygen2 code) but the empty export remains.

svn checkout svn://svn.r-forge.r-project.org/svnroot/returnanalytics/pkg/PerformanceAnalytics

will check out the current code.  Otherwise pointers on how to debug into a suspect internal roxygen2 function would be appreciated.

**Comment by hadley** [comment]
That should fix it - I just ran on PerformanceAnalytics and it seemed to work

**Comment by braverock** [comment]
confirmed.  spurious export is gone.  thanks.
