### ISSUE TITLE
Mismatched braces (false positive)

### ISSUE THREAD

**Issue by yihui** [klutometis/roxygen#407]
See here for an example:
https://github.com/yihui/Rd2roxygen/blob/3ba56bf/R/rd2roxygen.R#L158 roxygen2 believes there are unmatched braces in `\code{"##' "}`, and that is not true. A minimal repro:

```r
library(roxygen2)
roxygen2:::roc_proc_text(rd_roclet(), "#' @note A comment \\code{\"##' \"}.
NULL")
# list()
# Warning message:
# @note [file57272837fd1#2]: mismatched braces 
```

**Comment by yihui** [comment]
There are many more similar issues when I test the leaflet package, e.g. https://github.com/rstudio/leaflet/blob/3b4d8a38654d/R/colors.R#L243

**Comment by hadley** [comment]
Noooooooooooo why would you write code like that, why If why :sob:

(It is valid Rd but I'd hope I wouldn't have to implement the full set of rules for switching between r and Rd escaping)

**Comment by yihui** [comment]
And URLs that contain `#` won't work, either, e.g. `\url{http://foo.com/#bar}`...

Why do you need to check if braces are matched? I mean, why not leave this job to `R CMD check`?

**Comment by hadley** [comment]
Because that gives error messages that refer to .Rd files, which I'd prefer to insulate the roxygen2 user from.

**Comment by yihui** [comment]
Okay, then I want an option to say "I'm an expert of roxygen2 and Rd; don't check or warn against my braces" :)

**Comment by hadley** [comment]
Or I could just write code that works correctly...

**Comment by cbarbu** [comment]
I have an other similar but frequent for me example, in any @examples a comment with a simple quote (') would raise this warning. Commented code should probably be left alone in @examples.

**Comment by hadley** [comment]
@cbarbu that's already handled. For future reference, please file a new issue, rather than combining with an existing issue unless you're sure it's the same problem.

**Comment by hadley** [comment]
@yihui I think I just made a couple of dumb mistakes and it's not as hard as I thought. Your problem is now fixed, and I checked by documenting leaftlet, and didn't see any problems.

**Comment by yihui** [comment]
Confirmed. Thanks!
