### ISSUE TITLE
Repeated descriptions of re-exported functions

### ISSUE THREAD

**Issue by yihui** [klutometis/roxygen#408]
An example:

```r
#' @importFrom htmlwidgets JS saveWidget
#' @export
htmlwidgets::JS
#' @export
htmlwidgets::saveWidget
#' @importFrom magrittr %>%
#' @export
magrittr::`%>%`
```

The Rd generated:

```latex
% Please edit documentation in R/package.R
\name{reexports}
\alias{JS}
\alias{\%>\%}
\alias{reexports}
\alias{saveWidget}
\title{Re-exported functions}
\description{
These functions have been imported from other packages, and reimported by this package so that you can use them without having to attach another package. See the original documentation, linked to below, for more details

These functions have been imported from other packages, and reimported by this package so that you can use them without having to attach another package. See the original documentation, linked to below, for more details

These functions have been imported from other packages, and reimported by this package so that you can use them without having to attach another package. See the original documentation, linked to below, for more details
}
\seealso{
\code{\link[htmlwidgets]{JS}}, 

\code{\link[htmlwidgets]{saveWidget}}, 

\code{\link[magrittr]{\%>\%}}, 
}
\keyword{internal}
```

Actually I had a hack in Rd2roxygen to deal with re-exported objects (https://github.com/yihui/Rd2roxygen/blob/3ba56bff/R/build.R#L171-L226), and the Rd generated from it looks like this: https://github.com/rstudio/DT/blob/01b28ee4/man/DT-imports.Rd

![image](https://cloud.githubusercontent.com/assets/163582/10671797/3dd8c346-78b2-11e5-8db6-f2f96e333f04.png)

I think it looks better than the version that roxygen2 currently generates. 

![image](https://cloud.githubusercontent.com/assets/163582/10671836/6e702dbe-78b2-11e5-9325-74d9d9801b31.png)

In particular, I listed the package names before the re-exported functions so users know where they come from. Two other issues are:

1. I used `\docType{import}` so R knows these objects don't need to be documented in detail and `R CMD check` will not check, for example, if the arguments of functions are documented;
2. I added a prefix to the `\name{}` of Rd, which is the package name. Without the prefix, `?reexports` can be ambiguous.

**Comment by hadley** [comment]
Where did you find out about `\docType{import}` - I can't see it anywhere in R-exts?  

I like the suggestions!

**Comment by yihui** [comment]
Last year I suggested to R core that 1) R CMD check should skip the check of the documentation of re-exported objects, and 2) the R help system should just redirect to the original documentation of re-exported objects. Basically they did 1, and added `\docType{import}` so R CMD check knows there is no need to check this Rd. The NEWS for R 3.1.1 mentioned `promptImport()` and that is where I found this special `\docType`: https://cran.r-project.org/doc/manuals/r-release/NEWS.html

**Comment by hadley** [comment]
Nice - thanks for the explanation!  I really wish we could do documentation redirects :/

**Comment by hadley** [comment]
I think I got most of your issues - unfortunately I can't easily customise the topic name to include the package name, but I think people mostly won't be looking up `?rexports`  so it shouldn't be a huge problem (and if it is, we can fix in the next version)

**Comment by yihui** [comment]
That makes sense.
