### ISSUE TITLE
Support for functions that return a populated environment

### ISSUE THREAD

**Issue by tomtom** [klutometis/roxygen#423]
I often use this pattern:

    MyClass <- function(init.args, ...) {

        myfn <- function(fn.args, ...) {
            +++
        }

        self <- environment()
        class(self) <- c("MyClass")
        invisible(self)
    }

Currently roxygen doesn't provide a way to properly document these inner functions and to include their doc's in the help text of "MyClass". I have to include the help text of "myfn" in "MyClass" which is cumbersome and requires the use of rd macros like `\description`.

It would be great if I could use `@describeIn` to include a description of the argument list in the doc of "MyClass".

**Comment by hadley** [comment]
It's unlikely that roxygen2 will ever help with this, unless you use R6 (#388)
