### ISSUE TITLE
If function defintion contains @ a warning is incorrectly thrown

### ISSUE THREAD

**Issue by bestdan** [klutometis/roxygen#426]
Consider documenting the following R file: 

```r
#' @title Test Bug
#' @description Stuff.
#' @param x A thing.
#' @export
#' @examples
#' TestFun(x)

testFun <- function(x){
  
  #'  @dan 
  return(TRUE)
}
```
If we roxygenize it: 

`devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))`

it throws warnings:

```r
> Warning messages:
> 1: @dan [TestFun.R#13]: unknown tag
```

**Comment by hadley** [comment]
Roxygen now respects roxygen comments inside functions in preparation for R6/RC support
