### ISSUE TITLE
is_s3_generic fails on 'predict' method - is S4 method?

### ISSUE THREAD

**Issue by kenahoo** [klutometis/roxygen#427]
I've got a simple class `"foo"` and I want to define some methods like `predict` and `coef`:

```
##' @export
foo <- function(mean, var) {
  fit <- nnls(cbind(mean^2, mean), mean+var)
  class(fit) <- c('foo', class(fit))
  fit
}

## @export
coef.foo <- function(object, ...) {
  co <- NextMethod(object)
  c(a=co[1], b=1+co[2])
}

##' @export
predict.foo <- function(object, newdata, ...) {
  co <- coef(object)
  with(newdata, co[1]*mean^2 + co[2]*mean)
}
```

However, this doesn't always work - sometimes `predict` and `coef` are recognized as methods (so `S3method` is generated in the `NAMESPACE` file), and sometimes not (so I get `export` in the `NAMESPACE`).  I've seen it go back and forth in the same project.

Looking deeper, I notice that `roxygen:::is_s3_generic` fails on, e.g., the generic `predict` method:

```
> roxygen2:::is_s3_generic("predict")
[1] FALSE
> roxygen2:::is_s3_generic("print")
[1] TRUE
```

I think this is probably because `predict` calls `standardGeneric("predict")` rather than `UseMethod`, right?  Does that make it an S4 method?  If so, what's the right way to document `predict` / `coef` methods with roxygen?

**Comment by hadley** [comment]
Can you try it in a clean session? They are not normally s4 generics.

**Comment by kenahoo** [comment]
Aha, that's indeed what's happening.  I loaded the 'kernlab' package and it defines a `predict` function, unfortunately, which is exported.  I didn't notice that before, because the name of the environment was obfuscated:

```
> predict
standardGeneric for "predict" defined from package "stats"

function (object, ...) 
standardGeneric("predict")
<environment: 0x119a56808>
Methods may be defined for arguments: object
Use  showMethods("predict")  for currently available ones.
```

Anyway, in a fresh R session I see this:

```
Restarting R session...

> roxygen2:::is_s3_generic("predict")
[1] TRUE
> library(kernlab)
> roxygen2:::is_s3_generic("predict")
[1] FALSE
```

Thanks for the quick eye.

**Comment by kenahoo** [comment]
I'm wondering what's the right thing to do about this issue - I thought the `kernlab` package was misbehaving with its exports, so I was going to submit a patch to them, but looking more closely, it only has an `exportMethods("coef", "fitted", "plot", "predict", "show")` in its `NAMESPACE` file, not an `export("show")` or the like.  So as far as I can see, it's playing nice.

Also, I'm not doing `library("kernlab")` in my code, I'm only doing `library("LinearizedSVR")`, and the `LinearizedSVR` package only `Imports` 2 methods from `kernlab` (neither method is "show"), it doesn't `Depend` on it.  But apparently this is enough to turn the `show` method from an S3 to an S4 generic.

If all these packages were playing nicer with each other, what would they be doing?  The only workaround I can see right now is to keep using the `@S3method` directive.

**Comment by kenahoo** [comment]
By which I mean - if `kernlab` is actually doing things properly and that still messes up the generic/method detection of `roxygen2`, then perhaps the `is_s3_generic` method needs to be fixed after all to detect the situation better somehow?  Or the `@S3method` tag needs to be un-deprecated, if it's the only way to work around the non-detection?

**Comment by hadley** [comment]
Could you create a minimal reprex for me? (i.e. a package with just one predict method and the minimal set of imports to recreate the problem).

**Comment by kenahoo** [comment]
Will do.

**Comment by kenahoo** [comment]
Okay, apparently the issue is different than I thought.  It depends on whether the `kernlab` package is currently loaded in the session when I run `devtools::document()` - not on whether/how I depend on [something that depends on] `kernlab` in my `DESCRIPTION` file.

Ordinarily one doesn't run `devtools::document()` in an active session, but I have to do it this way because `devtools` is installed in my user library, not in R's system library, so doing Cmd-Shift-D in RStudio results in this error in the Build window:

```
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: suppressPackageStartupMessages ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Exited with status 1.
```

See https://support.rstudio.com/hc/communities/public/questions/205289827-There-is-only-Zuul-not-devtools- for some background on that.

So it looks like a solution to this problem is to set not just the `.libPaths()` value in my `~/.Rprofile`, but also the `R_LIBS` environment variable.  That will work as long as I'm not using `packrat`, which will highjack the `.Rprofile` file, but I'll deal with that some other time.

**Comment by PeteHaitch** [comment]
I think I had a similar issue with `duplicated()`, which [_BiocGenerics_](https://bioconductor.org/packages/release/bioc/html/BiocGenerics.html) redefines as an S4 generic (in fact it redefines many S3 generics as S4 generics; this is the purpose of the package). In the end I simply switched out the `@export` tag for `@rawNamespace S3method(duplicated, GTuples)` (see https://github.com/PeteHaitch/GenomicTuples/commit/e75ce50c37bdccb3c5b1acfe4e67805e67476f88).
