### ISSUE TITLE
Overly aggressive rewrite of DESCRIPTION

### ISSUE THREAD

**Issue by eddelbuettel** [klutometis/roxygen#430]
I just got

```
-Imports: Rcpp (>= 0.11.0), utils
-Suggests: fts, xts, zoo, knitr
+Imports:
+    Rcpp (>= 0.11.0),
+    utils
+Suggests:
+    fts,
+    xts,
+    zoo,
+    knitr
 VignetteBuilder: knitr
 LazyLoad: yes
 LinkingTo: Rcpp, BH
 Description: An R Interface to Bloomberg is provided via the Blp API.
 SystemRequirements: A valid Bloomberg installation. API headers and dynamic
- library are downloaded from <https://github.com/Rblp/blp> during the build
- step. See <http://www.bloomberglabs.com/api/> for API documentation.
+    library are downloaded from <https://github.com/Rblp/blp> during the build
+    step. See <http://www.bloomberglabs.com/api/> for API documentation.
 License: file LICENSE
+RoxygenNote: 5.0.0
```

and only the last line is a legitimate change.  The rest is you imposing a style on me.

**Comment by gaborcsardi** [comment]
I believe this is devtools and not roxygen. Although sometimes it is hard to tell. :)

Btw. this will change soon, once devtools manipulates DESCRIPTION with https://github.com/metacran/description, which does not reformat, unless you actually change a field.

**Comment by eddelbuettel** [comment]
[This is the script I called](https://github.com/eddelbuettel/littler/blob/master/inst/examples/roxy.r):

```r
#!/usr/bin/r
#
# Simple helper script for roxygen2::roxygenize() 
#
# Dirk Eddelbuettel, August 2013
#
# GPL-2 or later

## load roxygen
library(roxygen2)

## check all command-line arguments (if any are given) for directory status
argv <- Filter(function(x) file.info(x)$is.dir, argv)

## loop over all argument, with fallback of the current directory, and
## call compileAttributes() on the given directory
sapply(ifelse(length(argv) > 0, argv, "."), FUN=roxygenize, roclets="rd")
```

I would not miss a chance to yell at devtools as @hadley knows, but here it really was roxygen.  It only happens on the first pass when it adds it 'Roxy 5 was here' stamp.  Subsequent runs are fine.

**Comment by hadley** [comment]
@gaborcsardi I'm using desc 1.0.0 and it seems like `desc::desc_set_collate()` still affects other fields (namely it adds trailing whitespace after depends, imports, and suggests).  It also doesn't allow me to start collate on new line.

**Comment by hadley** [comment]
Oh I see the discussion about the spaces, I guess I can live with that. But not starting on a new line bugs me.

**Comment by gaborcsardi** [comment]
YEah, I don't mind starting on a new line: https://github.com/metacran/desc/issues/24

**Comment by eddelbuettel** [comment]
But it;s my (DESCRIPTION) file and I didn't ask for a rewrite that pleases you.  I _just_ asked for a transfer of Rd content from R files to Rd files.

It is somewhat rude to alter unrelated files in a different format, however pleased you may be with the format.  I did not ask for it.

**Comment by gaborcsardi** [comment]
@eddelbuettel `desc` only reformats fields that you manipulate, so once `roxygen2` uses it, this issue should be solved.

**Comment by eddelbuettel** [comment]
@gaborcsardi I don't follow. 

I use roxygen. I dislike its behaviour. I file a bug report. Nine month later I am graced this discussion.

**Comment by hadley** [comment]
@eddelbuettel If you're no longer interested in the discussion, you might want to click the "unsubscribe button". Gabor and I are working to make sure any changes to the DESCRIPTION are minimal — unfortunately base `read.description` and `write.description` do not preserve formatting. It's not me imposing a style on you, it's base R.

**Comment by gaborcsardi** [comment]
@eddelbuettel The next version of `roxygen2` will (probably) use the `desc` package for `DESCRIPTION` manipulation. `desc` does not reformat your fields. :)

**Comment by eddelbuettel** [comment]
@hadley:   Old roxygen didn't do it.  So there goes your 'it is not me'.   

Anyway, we're talking software so of course it is 'next version will be perfect'.

**Comment by gaborcsardi** [comment]
Yeah, I believe the reformatting is in roxygen: https://github.com/klutometis/roxygen/blob/39a824c5944de99b8ee431b93b7ebcd3baf99ad4/R/description.R

So I guess you don't really need this file any more, although it seems that `read.description` is used in the test cases.

**Comment by gaborcsardi** [comment]
@hadley: I fixed the `Collate` issue, it was a bug, not a design choice. :) 

I'll fix the trailing whitespace issue with whatever solution we agree on, and then make a new release.
