### ISSUE TITLE
line wrapping inserts unwanted spaces

### ISSUE THREAD

**Issue by phaverty** [klutometis/roxygen#434]
Some words in roxygen tag content get split and wrapped upon conversion to Rd. Final text output (e.g. M-x ess-roxy-preview-text) get's un-wrapped by gains a space where the breaking and wrapping occurred. This seems to happen in URLs and at hyphens. For example

http://foo.org/this/is/some/path

may be wrapped to

http://foo.org/this/
is/some/path

and then end up as

http://foo.org/this/ is/some/path

Oddly enough, the Rd that ends up in the man/ directory following a roxygenize call does not have this issue.

**Comment by hadley** [comment]
Roxygen2 doesn't do any wrapping anymore, so a reproducible example would be helpful.

**Comment by jeroenooms** [comment]
I'm having the same issue with URL's being split in my `DESCRIPTION` file.

**Comment by hadley** [comment]
@jeroenooms I think you're complaining about #430
