### ISSUE TITLE
wrap_field_if_necessary() does not work with non-native encoding of DESCRIPTION file

### ISSUE THREAD

**Issue by WastlM** [klutometis/roxygen#435]
I cannot `roxygenise()` a package with a DESCRIPTION in "latin1" encoding on my Linux machine. The problem is caused by the `wrap_field_if_necessary()` function, where the use of `str_length()` and `str_wrap()` assumes properly encoded strings. Here is a simple example:

    > roxygen2:::wrap_field_if_necessary("Author", "a non-ASCII author in latin1 encoding as returned by read.dcf() on my machine: S\xf8ren")
    Error in if (longest.line > wrap.threshold) { : 
      missing value where TRUE/FALSE needed
    In addition: Warning message:
    In stri_length(string) :
      invalid UTF-8 byte sequence detected. perhaps you should try calling stri_enc_toutf8()

I have added a complete test case with a DESCRIPTION file in "latin1" encoding in my roxygen fork (https://github.com/WastlM/roxygen/commit/94ac5375423f91b0c303daa1349c6e0d63d695ac), which currently fails because of the above problem.

It seems to me as if the `value` argument of `wrap_field_if_necessary()` needs to be `iconv()`ed from the "Encoding" set in the DESCRIPTION (if present) to the native encoding, such that `str_length()` does not produce NA's and `str_wrap()` does not fail. 

Additionally, in `cat.description()`, the original encoding of the DESCRIPTION file has to be preserved. This issue has probably been addressed in #277.

**Comment by hadley** [comment]
I am somewhat sympathetic to your plight, but I would much rather standardise on UTF-8.

**Comment by WastlM** [comment]
I am happy to note that `roxygenise`ing a package with a DESCRIPTION file in a non-native encoding now works in **roxygen2** 6.0.0, because the problematic code to update the DESCRIPTION file has been replaced by functions from the **desc** package (39a824c5944de99b8ee431b93b7ebcd3baf99ad4).

A corresponding test should be added, where the DESCRIPTION actually contains non-ASCII characters in a non-standard locale. Maybe just add something to the [DESCRIPTION file of the **testNonASCII** test package](https://github.com/klutometis/roxygen/blob/master/tests/testthat/testNonASCII/DESCRIPTION)? (@shrektan)
