### ISSUE TITLE
Creating OS-specific Rd files

### ISSUE THREAD

**Issue by richierocks** [klutometis/roxygen#438]
A few functions in base-R have different function signatures depending upon the operating system.  Consequently, they have multiple Rd files.  See, for example, the documentation for `grDevices::png` in [`man/unix`](https://github.com/wch/r-source/blob/trunk/src/library/grDevices/man/unix/png.Rd) and [`man/windows`](https://github.com/wch/r-source/blob/trunk/src/library/grDevices/man/windows/png.Rd).

Currently, AFAIK, it isn't possible to generate multiple Rd files in this way using roxygen.  Please can you add this feature.

(I realise that creating your own functions that have different function signatures under different OSes is mostly insane, but my use case is trying to add `with_png` to the [`withr`](https://github.com/jimhester/withr) package, and the arguments need to follow those in base-R, so it is unavoidable.)

**Comment by richierocks** [comment]
A related issue is that `@inheritParams` doesn't seem to understand `#ifdef` directives, such as this fragment from [`pdf.Rd`](https://github.com/wch/r-source/blob/trunk/src/library/grDevices/man/pdf.Rd#L85):

```{r}
#ifdef unix
    See the \sQuote{Note} for a possible fix for some viewers.
#endif
```

That means that something like the following will generate a bad Rd file:

```{r}
#' @inheritParams grDevice::pdf
my_fn <- function() {}

**Comment by hadley** [comment]
I believe that with different arguments on different OSes are a terrible idea, so I have no interest in supporting this.  For your specific problem, why not just make a wrapper around `png()` that is consistent?
