### ISSUE TITLE
Data documentation error

### ISSUE THREAD

**Issue by christophergandrud** [klutometis/roxygen#442]
I'm trying to document a data set called `MisNodes` that is part of a package. I use:

```{r}

#' A data file of nodes from Knuth's Les Miserables characters data base.
#'
#' @source See Mike Bostock \url{http://bl.ocks.org/mbostock/4062045}.
#' @format A data set with 77 observations of 2 variables, plus made up
#' node size variable.
"MisNodes"
```

And get the error: `Error: 'MisNodes' is not an exported object from 'namespace:networkD3'`

Any help would be much appreciated.

**Comment by hadley** [comment]
Do you have `LazyData: true` in your description?

**Comment by christophergandrud** [comment]
Nope

**Comment by christophergandrud** [comment]
Figured out the problem. The data was stored in `tsv` format rather than `rda`. Once I converted to `rda` everything is fine.
