### ISSUE TITLE
List of available tags

### ISSUE THREAD

**Issue by torbjorn** [klutometis/roxygen#447]
I may not have searched long enough but I cant find a list of available tags? I feel thats a must-have for a project like this. Every search result seems to point to a tutorial or introduction guide that repeats usage of 4-5 tags.

**Comment by 1beb** [comment]
Agree, where is this? I think it used to be in documentation but now I can't find it.

**Comment by hadley** [comment]
See http://r-pkgs.had.co.nz/man.html

**Comment by grabear** [comment]
Looking for an answer to this issue in #792 @hadley @1beb @torbjorn

**Comment by daattali** [comment]
For anyone arriving at this issue, #792 has a link to where the list of tags is currently housed: https://roxygen2.r-lib.org/articles/rd.html
