### ISSUE TITLE
Roxygen doesn't understand UseMethod("generic", x)

### ISSUE THREAD

**Issue by jackwasey** [klutometis/roxygen#448]
Having battled through the R documentation, I don't see any objection to using `UseMethod` within an S3 method to dispatch again, but doing this breaks `roxygen2:::calls_use_method` which simply looks for whether `UseMethod` exists.

I want to do something like:

```
#' my method
#' @export
my_method <- function(x)
  UseMethod(x)

#' @describeIn my_method a class stuff
#' @export
my_method.a_class <- function(x)
 return("something")

#' @describeIn my_method determine class and re-dispatch
#' @export
my_method.default <- function(x)
  class(x) <- "a_class"
  UseMethod("my_method", x)
```
This works from an R point of view, and, although it is not a common use of UseMethod, it is the simplest way I can see to solve a more complicated problem in my package (https://github.com/jackwasey/icd9). Unfortunately, roxygen2 gives:
`Error: Don't know how to describe s3generic in s3generic.`
Commenting the second `UseMethod` lets roxygen run okay.

Incidentally, `NextMethod` is not the solution to this for multiple reasons, not least that you can't update the class passed to NextMethod.

**Comment by jackwasey** [comment]
Removing all roxygen comments also allows the documentation to compile. Maybe I shouldn't be exporting the default method?

**Comment by jackwasey** [comment]
A work-around is possible using `@method`. I added an explicit `@method` for the default function in the example above, and roxygen then compiles the documentation correctly.

**Comment by hadley** [comment]
I think the correct solution here is to use `@method`. It's fine to use `UseMethod("generic", foo)` in a generic.
