### ISSUE TITLE
Unicode character not dropped from usage section

### ISSUE THREAD

**Issue by brry** [klutometis/roxygen#452]
In Roxygen2 5.0.1, I have a default axis label to get cubic meters via unicode:
ylab="Discharge  [m\U00B3/s]"
In the usage section of the Rd document, this becomes:
ylab = "Discharge  [m<U+00B3>/s]"
Which yields a code/documentation mismatch in devtools::check().

**Comment by hadley** [comment]
It works for me:

```R
out <- roc_proc_text(rd_roclet(), "
  #' A
  a <- function(a = '\U00B3') {}
")[[1]]
get_tag(out, "usage")$values
#> <rd> a(a = "³")
```

What platform are you on?

**Comment by brry** [comment]
Sorry for coming back so late, I missed that you closed the issue. I still have this problem (Windows 7). 
Your example works in pure R for me, too. (In Rstudio's R console, the cubic three is displayed as a black diamond with white question mark. I'm using the current version 1.0.44 and I am fine with that.)

The problem consists of Roxygen writing an incorrect usage section which then gets flagged by R CMD check.
The Rd file should contain `backslash U code`, but Roxygen writes `lesser U plus code larger`. 

(My original issue comments gets displayed correctly in Firefox, but I'm not sure if that always works so I wrote out the names).

Here's my R CMD check result (the same with devtools::check)

  Mismatches in argument default values:
    Name: 'ylab' Code: "Discharge HQ  [m³/s]" Docs: "Discharge HQ  [m<U+00B3>/s]

**Comment by hadley** [comment]
Unless you can create a minimal reproducible example that illustrates the problem, it is unlikely that I will be able to fix it.

**Comment by brry** [comment]
Your MWE above already contains the problem. The exponent 3 gets displayed correctly in R and on github, but in the actual Rd file is not `\Uxxx` as it is supposed to be, but `<U+xxx>`. I'm sorry for being so bad at expressing this... 
btw: The R file is saved in ASCII encoding, so that seems not to be the reason.

**Comment by brry** [comment]
Any news as to why in the usage section, Unicode `\Uxxx` is changed to the symbol it represents? 
The latter used to be `<U+xxx>`, now the Rd file just displays a cubic3-symbol in all my texteditors.

Even worse: If I run `document` and it newly creates the Rd file, it works fine. But if I run `document` a second time, I get the `Error in gsub("\n", "\r\n", contents, fixed = TRUE) :  input string 1 is invalid UTF-8` after the package is loaded. calling stack is here:
document -> withr::with_envvar -> force -> roxygen2::roxygenise -> unlist -> lapply -> FUN -> roclet_output -> roclet_output.roclet_rd -> mapply ->  -> same_contents -> gsub -> gsub("\n", "\r\n", contents, fixed = TRUE)[1] "Error in gsub [...]

Now if I change the `% Generated by roxygen2` line by hand (and the offending symbol back to `\U{00B3}`), things work fine, but this is not elegant...

**Comment by hadley** [comment]
I'd recommend opening a new issue with a reprex, based on the code snipped I showed.
