### ISSUE TITLE
Documenting s4 generic 'c' method?

### ISSUE THREAD

**Issue by cboettig** [klutometis/roxygen#456]
This is probably just user stupidity, but it's not clear to me what the minimal Roxygen documentation is required to document a concatenate method for an S4 class. I anticipated roxygen would generate this automatically.   (It seems other generics don't need documenting, like 'initialize')

For a `c` method, it seems I still need name, title, param and a rdname?

```r
#' concatenate
#' 
#' concatenate
#' @param x,... objects to concatenate
#' @param recursive Needed for compatibility with generic, otherwise ignored
#' @rdname c-methods
setMethod(c, signature("myclass"), function(x, ..., recursive = FALSE) list(x, ...) )
```

feels a bit verbose when these should perhaps be coming from the definition of the generic anyway?  Or maybe I'm just confused.  Thanks for any input.

**Comment by hadley** [comment]
Yes, as far as I know, you have to document all S4 methods
