### ISSUE TITLE
Double-quotes inside roxygen comments fail to roxygenize with "mismatched braces or quotes" error

### ISSUE THREAD

**Issue by mbacou** [klutometis/roxygen#457]
I've just noticed starting with roxygen2 **v5.0.0** that any backtick in regular inline comments inside function calls (starting with `# `) fail to roxygenize. E.g. sometimes I write comments like:

```
f <- function() {
  # Write custom `README.md` and `README.html`
  # Return `myfield` from `mydataframe`
  # [...]
}
```

**Comment by mbacou** [comment]
Renaming this issues, as Iive realized the backticks are not the culprit. The problem seems to come from this type of construct, where `#` signs follow `#'`:

```
#' @examples
#' # Generate auxiliary files for soil organic carbon concentration and 2012 total population
#' f <- meta(c("soc_d5", "PN12_TOT"))
#' f
#'
#' # Equivalent cUrl request at the command line
#' # curl http://hcapi.harvestchoice.org/ocpu/library/hcapi3/R/meta \
#' # -d '{"var" : ["soc_d5", "PN12_TOT"]}' \
#' # -X POST -H 'Content-Type:application/json'
```

**Comment by fakenmc** [comment]
I think this is related with the curly braces. For example, the following fails:

```{R}
#' @examples
#' paste0("Paste{","test", "}")
#' # [1] "Paste{test}"
```

with "@examples [...]: mismatched braces or quotes ". Remove the curly braces from the last line (comment) and no warning occurs.

**Comment by mbacou** [comment]
Correct thx, I am confirming. Hopefully that's an easy bug to fix.

**Comment by mbacou** [comment]
Closing, this is a duplicate of https://github.com/klutometis/roxygen/issues/393
