### ISSUE TITLE
verbose output from roxygenize when needed?

### ISSUE THREAD

**Issue by pdbailey0** [klutometis/roxygen#459]
I was getting an error when calling roxygenize because I had some code in a file that wouldn't execute. it would have helped if there were a way to see which file was causing the error. One option would be to allow a verbose flag in roxygenize to change source_package to call this

lapply(paths, function(z) { cat("z=",z,"\n");sys.source(z, envir=env, keep.source=FALSE) })

in place of 

 lapply(paths, sys.source, envir = env, keep.source = FALSE)

a better thing might be to catch the error in sys.source and tell the user which file caused sys.source to throw an error. As it stands now, traceback() doesn't give helpful info about which thing was being sourced so I had act as if I was debugging source_package to figure out which file was causing it.

This is, obviously, an RFE, so I won't complain if you just close it. Now that I have figured out this situation I see that another option would have been to search the R/ folder for the call that I most recognized from traceback() to find what was causing the issue. But I'm not sure how many users would get that far.

Thanks for this amazing package!

**Comment by hadley** [comment]
You're better off using `devtools::document()` which uses a more sophisticated strategy that should give better errors.
