### ISSUE TITLE
R 3.3.0 roxygen problem with templates

### ISSUE THREAD

**Issue by dankelley** [klutometis/roxygen#468]
In my `oce` package, I found a problem with templates, but it went away when I installed roxygen2 from GH. I thought you'd like to know, since the last edits on GH are pretty old ... possibly a re-release of roxygen2 is in order?  Details are at

https://github.com/dankelley/oce/issues/957

in case you want to check.

Thanks for roxygen[2]?, which I LOVE!

**Comment by hadley** [comment]
I don't see any changes related to templates, but I'm glad reinstalling helped you.
