### ISSUE TITLE
Build binary package - failed

### ISSUE THREAD

**Issue by xhudik** [klutometis/roxygen#469]
Hi,
i'm able to compile package by pressing on "Build/Build&Reload" in the right panel. However, when I want to build a binary package and I press in menu: "Build/Build Binary Package", I got this error:

===================================
_==> devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))

Updating My_prj documentation
Loading My_prj
Skipping invalid path:  DB Ingest.Rd 
Writing prj_Data_Gathering_MergeSourcesAtStage.Rd
Writing DataGg_Tests.Rd
Writing FE.Rd
Writing Fr.Rd
Writing Lllirt.Rd
Writing klIK.Rd
Writing AutomaticKlIK.Rd
Writing prj_Cal.Rd
Writing NAMESPACE
Updating vignettes
There were 10 warnings (use warnings() to see them)
Documentation completed

==> devtools::build(binary = TRUE, args = c('--preclean'))

'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/home/tth/tmp/prj_pokustek/My_prj' --build  \
  --preclean 

* installing to library ‘/tmp/RtmpI3lLet/file2ffd4c8cd54b’
* installing *source* package ‘My_prj’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘Now’
ERROR: lazy loading failed for package ‘My_prj’
* removing ‘/tmp/RtmpI3lLet/file2ffd4c8cd54b/My_prj’
Error: Command failed (1)
Execution halted

Exited with status 1.

=================================

There is reported missing package ‘Now’. However, this package doesnt exist in R and I don't use it in my package. I must re-run roxygen2::roxygenise()  in order to continue development without annoying messages about Now package...

Any idea?

Rstudio version (compiled from git) : Version 99.9.9 – © 2009-2016 RStudio, Inc.

**Comment by hadley** [comment]
I'd recommend starting by eliminating the 10 warning messages that you are getting
