### ISSUE TITLE
Check Rd syntax only after merging tags

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#471]
not for individual snippets. Example:

```
#' @return
#' \describe{
#'
...
#' @return
#'   \item{...}{...}
...
#' @return
#' }
```

This will warn on the first and third `@return` tag, but shouldn't.

Source location: https://github.com/klutometis/roxygen/blob/7133fd62123eb3a8ea513a962d5c2f2d8d905da4/R/parse-preref.R#L85

**Comment by hadley** [comment]
How badly do you need this? I'd rather stick to the philosophy that each tag must be a valid Rd fragment.

**Comment by krlmlr** [comment]
I'm fine with the current implementation, will reopen/resubmit if necessary.
