### ISSUE TITLE
Export parse_file

### ISSUE THREAD

**Issue by AugustT** [klutometis/roxygen#473]
I’m the maintainer of the zoon R package for building reproducible species distribution models (SDM).  I use roxygen:::parse_file to read in user created functions to check that all the metadata is present and sensible. devtools::check(), raises a note for the use of ‘:::’ and following the guidance in the documentation for ‘:::’ I am contacting you to see if you would consider exporting parse_file from roxygen.

**Comment by hadley** [comment]
I would prefer not to — it's an internal function for a reason. There's no guarantee that I'll continue to return the same object in the future.
