### ISSUE TITLE
Escaping "}" in a character string within `\dontrun{ }` 

### ISSUE THREAD

**Issue by SymbolixAU** [klutometis/roxygen#476]
[Related StackOverflow question](http://stackoverflow.com/q/37360571/5977215)

Allow `}` to be included / escaped in `\dontrun{ }`

**Example**

In the `\dontrun{ }` section I have a string that contains `}`. 

```
    #' ...
    #' @examples
    #' \dontrun{
    #' ## polyline joining the capital cities of Australian states
    #' pl <- "nnseFmpzsZgalNytrXetrG}krKsaif@kivIccvzAvvqfClp~uBlymzA~ocQ}_}iCthxo@srst@"
    #'
    #' df_polyline <- decodepl(pl)
    #' }
    #' ...
```

When built, the documentation for the example is

```
## Not run: 
## polyline joining the capital cities of Australian states
pl <- "nnseFmpzsZgalNytrXetrG
## End(Not run)krKsaif@kivIccvzAvvqfClp~uBlymzA~ocQ
```

Where everything after the first `}` is cut off and placed after `End(Not run)`.

**Comment by hadley** [comment]
Fixing this is quite difficult (as far as I can it will require writing a considerably more complicated Rd parser), and it's a rare occurrence, so realistically this is never going to get high up enough on my to do list to fix it.
