### ISSUE TITLE
Bug?  requires a value 

### ISSUE THREAD

**Issue by danielmarcelino** [klutometis/roxygen#480]
Hi, for some reason I'm receiving the following message from package check results. The puzzling thing is that those two file have titles, and roxygen was creating the Rd files just fine few months ago. Am I doing any out of dated?
The package I'm building is [here](https://github.com/danielmarcelino/SciencesPo). 

`R CMD check results`
`0 errors | 0 warnings | 0 notes`
`Warning messages:`
`1: @title [Outlier.R#1]: requires a value `
`2: @description [Outlier.R#1]: requires a value `
`3: @title [TESTS.R#1]: requires a value `
`4: @description [TESTS.R#1]: requires a value `

`R CMD check succeeded`

**Comment by zkamvar** [comment]
I have also received these warnings and perhaps I have found a solution to your problem?

These were my warnings:
```
> roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))
Creating a generic function for ‘rbind’ from package ‘base’ in package ‘roxygen_devtest’
There were 14 warnings (use warnings() to see them)
> 
> warnings()
Warning messages:
1: @title [get_methods.R#1]: requires a value
2: @description [get_methods.R#1]: requires a value
3: @title [get_methods.R#1]: requires a value
4: @description [get_methods.R#1]: requires a value
5: @title [get_methods.R#1]: requires a value
6: @description [get_methods.R#1]: requires a value
7: @title [get_methods.R#1]: requires a value
8: @description [get_methods.R#1]: requires a value
9: @title [get_methods.R#1]: requires a value
10: @description [get_methods.R#1]: requires a value
11: @title [get_methods.R#1]: requires a value
12: @description [get_methods.R#1]: requires a value
13: @title [get_methods.R#1]: requires a value
14: @description [get_methods.R#1]: requires a value
```

It was for this pull request: https://github.com/knausb/vcfR/pull/41

I noticed that I had documented 8 methods and received 7 warnings for title and description, each. When I looked at the code, I noticed that it looked like this:

```r
#'
#' @rdname getFIX
...
```

When I got rid of that orphan roxygen tag, the warnings went away: https://github.com/knausb/vcfR/pull/41/commits/662d07db8b4459a52ed83d21522e5ee8b0e421fa

**Comment by hadley** [comment]
Please open a new issue and include the roxygen block that generated the error.

**Comment by zkamvar** [comment]
Are you referring to me or @danielmarcelino?
