### ISSUE TITLE
Optional parameters and default values

### ISSUE THREAD

**Issue by fernandojunior** [klutometis/roxygen#487]
What about something like [jsdoc](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values) for optional parameters and default values?

An optional parameter:
```R
#' @param [somebody] Somebody's name.
sayHello = function(somebody='John Doe') print(somebody)
```

An optional parameter and default value:
```R
#' @param [somebody=John Doe] Somebody's name.
sayHello = function(somebody='John Doe') print(somebody)
```

**Comment by artemklevtsov** [comment]
Read the docs: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Rd-format

**Comment by fernandojunior** [comment]
@artemklevtsov Done, what next?

> Information is given within a series of sections with standard names (**and user-defined sections are also allowed**)
