### ISSUE TITLE
Tab vs space between #' and @

### ISSUE THREAD

**Issue by rcorty** [klutometis/roxygen#491]
Not sure if this is a bug or a feature, just documenting it a bit in case it's a bug.

I'm using R version 3.3.0 on Rstudio 0.99.902 on Mac OS 10.11.6 (15G31).

I had the following in the preamble to one of my functions

```
#'  @title myFunction
#'  @param my.parameter.description
#'  @export
```

Note that there are two spaces between `#'` and `@`.  This is what Rstudio puts there if I type pound-singlequote-tab-atsign.  On `roxygenise()`, myFunction wasn't getting added to NAMESPACE.  I remembered some problem I had months ago about the spacing before the `@`, so I switched the preamble to this:

```
#'  @title myFunction
#'  @param my.parameter.description
#' @export
```

Note that now the `@export` line has only one space before the `@`.  
When I used `roxygenise()`, I got this error:

`@export [myFuncion.R #43]: may only span a single line `

I switched all the lines to have a single space between `#'` and `@` and now `roxygenise()` works as expected.

**Comment by hadley** [comment]
Yes, you must have one space.  I can't get RStudio to produce a double space.

cc @kevinushey in case he has any ideas

**Comment by rcorty** [comment]
Maybe relevant, in RStudio preferences, I have it set to insert two spaces for tabs.
