### ISSUE TITLE
Error parsing @importFrom statements

### ISSUE THREAD

**Issue by fangly** [klutometis/roxygen#492]
Hi,

I have a package documented with Roxygen2. I decided to organize my main R file into several smaller ones. It all went well until I moved one of my @importFrom statements (#' @importFrom lattice trellis.device) to a new file.

A clean&rebuild in RStudio resulted in:

** preparing package for lazy loading
Error : object '(for' is not exported by 'namespace:lattice'
ERROR: lazy loading failed for package 'S001'

This is because the devtools::document() step generates a wrong NAMESPACE file, with entries like:
```
importFrom(methods,new)
importFrom(utils,"\\code{simpleError}")
importFrom(utils,"message,")
importFrom(utils,Create)
importFrom(utils,The)
```

The solution was the same as explained here, i.e. inserting a NULL after the @importFrom line:
http://stackoverflow.com/questions/26386811/rstudio-roxygen2-importfrom-parsing-function-header

It was also discussed here:
http://stackoverflow.com/questions/27364610/create-an-r-package-with-dependencies

Cheers,

Florent

**Comment by hadley** [comment]
I don't see any easy way to fix this class of problems with out a lot of work, and then do seem to be relatively uncommon.  Just make sure your roxygen blocks always start with the title.
