### ISSUE TITLE
DESCRIPTION on mounted folders

### ISSUE THREAD

**Issue by gdkrmr** [klutometis/roxygen#495]
Situation:

Ubuntu 16.04, latest R and roxygen2 from CRAN and a Package in a folder mounted with sftp via gnome virtual file system

A call to `roxygen2::document()` produces a garbage `DESCRIPTION` file: instead of appending it overwrites from the beginning. The problem is R and writing to connections
```R
 for(i in 1:10){cat(i, file = "/mounted/folder/test2", append = TRUE)}
```
gives a file that reads `10` and not `1 2 ... 10`

Solution, open the file only once:
```R
assignInNamespace(
    "write.description",
    function(desc, file = "") {
        con <- if(file != ""){
            file(file, "w")
        } else {
            ""
        }
            
        mapply(roxygen2:::cat.description, names(desc), desc, MoreArgs = list(file = con))

        if(inherits(con, "connection")) close(con)
        
        invisible()
    },
    "roxygen2"
)
```

The post that helped me with this can be found here:
https://stackoverflow.com/questions/24927041/r-writeappend-true-overwrites-file-contents

**Comment by gdkrmr** [comment]
I did some more checking with :
```R
for(i in 1:10){cat(i, file = "/mounted/folder/test2", append = TRUE)}
```

- A mapped network drive on Windows 7 and R 3.2.5 works fine.
- A samba share on a Mac works fine.
- A samba share on Ubuntu 16.04 works fine.
- An sftp share on Ubuntu 16.06 does not work.

**Comment by hadley** [comment]
This is a bug with R — can you please report on R-devel?

**Comment by eddelbuettel** [comment]
Nope.

(r-devel sent him to r-sig-debian where I just conjectured that R has nothing to do with this. The 'append' property is not being honoured by the filesystem, which is not the fault of the client.)

I would suggest to work around it.  Create the DESCRIPTION file somewhere else -- say in `/tmp` where the write and append semantics work.  Then copy the final file.

**Comment by gdkrmr** [comment]
you can change the roxygen2:::write.description as above and it works fine.
If anyone should ever come across the same isse, here is how I resolved it for me:

I created a file named .Rprofile in the package root folder (which is the working directory for the R process) with the following content:
```R
.First <- function() {
    requireNamespace("roxygen2")
    unlockBinding("write.description", asNamespace("roxygen2"))
    assign(
        "write.description",
        function(desc, file = "") {
            con <- if(file != "") file(file, "w") else ""
            
            mapply(roxygen2:::cat.description, names(desc), desc, MoreArgs = list(file = con))
            
            if(con != "") close(con)
            
            invisible()
        },
        envir = asNamespace("roxygen2")
    )
    lockBinding("write.description", asNamespace("roxygen2"))
}
```

**Comment by hadley** [comment]
This will not work in the future because `write.description` has been removed.  But I don't think the functions from the desc package will have the same problem.
