### ISSUE TITLE
FR: A robust way for defining collation order

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#498]
Collation order is given implicitly by topologically sorting the graph defined by `@include` relationships. The only way to ensure that a certain order is maintained is to add explicit links to the immediate parent. This "linear list" data structure is difficult to maintain, because each insertion/deletion requires a nontrivial update in two files.

Example: Assume three files D.R, B.R, A.R, and I want the files to be collated in that order. I can add `@include D.R` to B.R, and `@include B.R` to A.R, but if I add a new file C.R to appear between B.R and D.R, I need to update B.R to ensure the collation order.

I'm working around this by defining a parent for all source files which `@include`-s them. This parent contains.

```r
#' @include A.R
#' @include B.R
#' @include C.R
#' @include D.R
NULL
```

The includes must appear *in reverse order* with the current implementation, see also a [real example](https://github.com/rstats-db/DBItest/blob/a41829808022aceaa74e01b9c6ea4f69f92730bf/R/spec-.R).

How about a new `@collate` tag that define include-like dependencies in order of appearance? The entry `@collate D.R C.R B.R A.R` would be equivalent to `@include D.R` in C.R, `@include C.R` in B.R and `@include B.R` in A.R . Only tags defined in the same source file (or the same roxygen block?) would be considered jointly.

**Comment by hadley** [comment]
This seems like a pretty rare use case

**Comment by krlmlr** [comment]
Agreed. I don't mind as long as my `@include` hack works, but if it breaks we'd need to reconsider.
