### ISSUE TITLE
as.vector S3 methods not being exported correctly

### ISSUE THREAD

**Issue by cdeterman** [klutometis/roxygen#503]
To demonstrate here is a trivial function

```r
#' @export
as.vector.foo <- function(x, mode = "any"){
  out <- x
  class(out) <- 'numeric'
  return(out)
}
```

When I build with roxygen2, the `NAMESPACE` gets the following line:

```
export(as.vector.foo)
```

This results in the following `NOTE` during R CMD check

```
* checking S3 generic/method consistency ... NOTE
Found the following apparent S3 methods exported but not registered:
  as.vector.foo
See section 'Registering S3 methods' in the 'Writing R Extensions'
manual.
```

**Comment by hadley** [comment]
Have you checked with the dev version? I'm pretty sure this is already fixed.

**Comment by cdeterman** [comment]
You are correct, the dev version has solved it.  Any timeline on the next release?

**Comment by hadley** [comment]
In the next few weeks
