### ISSUE TITLE
Better links in markdown

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#505]
From this discussion: https://github.com/klutometis/roxygen/pull/499/files/fc8ab2eddd1f855f7841a94151aaaeefdeae4b10#r78301946

Plan: 
* link to function in the same package: `[fun]`
* link to function in another package: `[pkg::fun]`
* link to function with link text: `[text][fun]`
* link to function in another package with link text: `[text][pkg::fun]`

I think this is all possible by simply adding the link references to the end of the text.

**Comment by gaborcsardi** [comment]
I am proposing that I would do this, obviously.

**Comment by hadley** [comment]
I like it!

**Comment by gaborcsardi** [comment]
Closed by #506.
