### ISSUE TITLE
Global roxygen options for a package

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#507]
We would put them in the `DESCRIPTION` file, in the `Roxygen` field, which is allowed, but not used currently. 

The plan is to have R code there, and initially we would support switching Markdown parsing on/off:
```
Roxygen: list(markdown = TRUE)
```

I will submit a PR in the coming days.

**Comment by gaborcsardi** [comment]
I see you are finishing things up. I'll try to write this tomorrow.

**Comment by hadley** [comment]
I'd also consider turning markdown on by default, and we can see how it goes when applied to my packages.

**Comment by gaborcsardi** [comment]
Of course you would turn it on, because you can blame me if sg goes wrong.
:)

With the current link implementation, there will be problems with Rd
brackets for example.

Why don't we just turn it on for your packages?

Regardless, we need this global switch, I think. I'll write it tonight.

**Comment by gaborcsardi** [comment]
Wait a sec, there is code for this already: https://github.com/klutometis/roxygen/blob/596893c42b48aaa91781a60ffaad3c2dc0000ac0/R/roxygenize.R#L86

I am sorry, I wasn't aware of this. So I can just all markdown here.....

**Comment by gaborcsardi** [comment]
This can be closed, there is a way, the `Roxygen` field. It works fine for markdown.
