### ISSUE TITLE
roxygen2 (>= 6.0.0) in Suggests if markdown is used in docs?

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#508]
In the markdown vignette, shall we tell people to put `Suggests: roxygen2 (>= 6.0.0)` in `DESCRIPTION` if they use markdown? 

Obviously, it is a pre-build time dependency, but you cannot express that in R. So I am not completely sure.

**Comment by hadley** [comment]
It's probably a good suggestion, but it doesn't really matter either way.

A slightly better approach might be for roxygen to warn if the RoxygenNote field is higher than its own version

**Comment by gaborcsardi** [comment]
Yeah, that's a good idea, actually. You probably don't want to downgrade....

**Comment by hadley** [comment]
This should be a simple check in `update_roxygen_version()`, but I'm blanking on the details because `package_version()` doesn't like `NA` as a specification

**Comment by hadley** [comment]
Ooops, wasn't that hard.
