### ISSUE TITLE
@inheritDotDotDot

### ISSUE THREAD

**Issue by hadley** [klutometis/roxygen#512]
Generate documentation for the `...` parameter by including (selected?) parameters from another function.  See `?plot` for an example of how this should render.

Not sure how you should specify which arguments to include in the list, since in many cases you won't want to include them all.

**Comment by privefl** [comment]
Sorry if it's a stupid remark. From what I understood from NEWS.md, I tried to use
```
#' @inheritDotParams bigmemory::big.matrix
#' @inheritDocParams -nrow -ncol -type -init
```
and my first question was "why a Dot and a Doc?".
After some **quick** trial and error, I used 
```
#' @inheritDotParams bigmemory::big.matrix -nrow -ncol -type -init
```
and it worked. 
Am I missing some documentation?
