### ISSUE TITLE
Context information for roxygen2 documentation blocks

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#516]
Last time I looked, the documentation blocks were available as a character vector, without context information. I wonder if we could add context information to each line processed, to support inline parameter documentation and R6 documentation (#306):

``` r
#' Some function 
fun <- function(
  a, #' description of argument a
  b = NULL) #' description of argument b
{
  ret <- process_it(a, b)
  ret #' a character vector
}
```

would be equivalent to

``` r
#' Some function
#' @param a description of argument a
#' @param b description of argument b
#' @return a character vector
```

This came up on the @RDocTaskForce mailing list.

**Comment by hadley** [comment]
I think this is basically done - the `roxy_block` class stores filename and line number, so you should be able to recreate the context if needed. Once you figure out exactly what you need, I'll be happy to review a PR that extends `roxy_block` with new fields.
