### ISSUE TITLE
Markdown link bug: [] are picked up in code by the link pre-parser parser

### ISSUE THREAD

**Issue by gaborcsardi** [klutometis/roxygen#518]
https://github.com/rstats-db/DBItest/commit/ccb5da5e99f0a1a55ee9adb00e9bc9f3884e01a2#commitcomment-19253359

**Comment by krlmlr** [comment]
Also:

```r
#' [`DBIResult`][DBIResult-class]
```

gives me a warning "mismatched braces or quotes". Might be related, if not, I'll open a new issue. Both of the following work:

```r
#' [`DBIResult`]
#' [DBIResult][DBIResult-class]
```

**Comment by gaborcsardi** [comment]
Not related, but I can fixed them together.

**Comment by jeroenooms** [comment]
Not sure if it is the same problem, but I found that when inserting a hyperlink with `[something](http://www.someurl.com)`, this is parsed both as a hyperlink as well as a footnote.

**Comment by gaborcsardi** [comment]
@jeroenooms I'll try to fix all these this week.

Unfortunately the links require some hacking, so I am not entirely surprised that they are buggy.

**Comment by gaborcsardi** [comment]
@krlmlr I cannot reproduce this with either commonmark 0.8 or 0.9. Can you please give me a `session_info()`

**Comment by gaborcsardi** [comment]
@krlmlr @jeroenooms Can you please check the test case I just added for this when you have time? Thanks!

https://github.com/gaborcsardi/roxygen/commit/0afa1cf2f3b17d45ba9a7a0f6595cae98d143225

**Comment by krlmlr** [comment]
I have commonmark 0.9.

**Comment by gaborcsardi** [comment]
So apparently the problem comes up if you have a space within the `[...]`. (!)

**Comment by gaborcsardi** [comment]
#528 should solve these. Please let me know and reopen if not.

**Comment by gaborcsardi** [comment]
Btw. @krlmlr and @jeroenooms, thanks for trying the markdown parser and reporting these bugs!
