### ISSUE TITLE
Markdown: handling of equations?

### ISSUE THREAD

**Issue by privefl** [klutometis/roxygen#520]
Would it be possible to have the "equation feature" also? 
For example, 

```
\[x^2 + y^2 = z^2\]
```

or

```
$x^2 + y^2 = z^2$
```

Anyway, this is a nice feature to be able to use Markdown in roxygen!

**Comment by gaborcsardi** [comment]
I think this is a good idea. Unfortunately equations are not supported by the commonmark parser that we use:

```r
❯ cat(markdown_xml("Foo \\[x^2 + y^2 = z^2\\] bar"))
#> <?xml version="1.0" encoding="UTF-8"?>
#> <!DOCTYPE document SYSTEM "CommonMark.dtd">
#> <document xmlns="http://commonmark.org/xml/1.0">
#>   <paragraph>
#>     <text>Foo </text>
#>     <text>[</text>
#>     <text>x^2 + y^2 = z^2</text>
#>     <text>]</text>
#>     <text> bar</text>
#>   </paragraph>
#> </document>

❯ cat(markdown_xml("Foo $x^2 + y^2 = z^2$ bar"))
#> <?xml version="1.0" encoding="UTF-8"?>
#> <!DOCTYPE document SYSTEM "CommonMark.dtd">
#> <document xmlns="http://commonmark.org/xml/1.0">
#>   <paragraph>
#>     <text>Foo $x^2 + y^2 = z^2$ bar</text>
#>   </paragraph>
#> </document>
```

Equations were discussed several times at the commonmark forum, but AFAIK nobody wrote any code to support them.
https://talk.commonmark.org/t/mathematics-extension/457/29
https://talk.commonmark.org/t/mathjax-extension-for-latex-equations/698/16
https://talk.commonmark.org/t/ignore-latex-like-math-mode-or-parse-it/1926

Note that `\eqn` and `deqn` are still supported in markdown mode, so you can just write equations that way for now, until commonmark gets proper equation support. It would probably also help if someone volunteered to implement it for them. :)
