### ISSUE TITLE
Section inheritance produces slightly wrong formatting

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#521]
Example: Comparison of original formatting and formatting produced by inheritance. https://github.com/rstats-db/DBI/commit/a9277a4f5a4187ef5f515c9288d9ad12c7ed7a52#commitcomment-19266464

**Comment by hadley** [comment]
I can no longer reproduce. Per discussion in #539, this is probably because it was fixed upstream and made it into R 3.3.3.
