### ISSUE TITLE
warning with template file containing '@export'

### ISSUE THREAD

**Issue by kevinushey** [klutometis/roxygen#522]
When building the `sparklyr` documentation with the development version of `roxygen2`, I see:

```
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating sparklyr documentation
Loading sparklyr
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
Warning: @export [TEMPLATE#11]: unknown tag
```

`sparklyr` includes `roxygen2` templates that include the `@export` tag. It looks like this is not included within the `roclet_tags` registry for some reason:

```
registry <- roxygen2:::roclet_tags.roclet_rd()
"export" %in% names(registry) # FALSE
```

It looks like it's available in the current `roxygen2` release:

```
registry <- roxygen2:::tags
"export" %in% names(registry) # TRUE
```

For reference, here's the missing elements:

```
# oldTags from roxygen2:::tags, current CRAN
# newTags from roxygen2:::roclet_tgs.roclet_rd(list())
> setdiff(names(oldTags), names(newTags))
 [1] "S3method"          "export"            "import"           
 [4] "importMethodsFrom" "importFrom"        "include"          
 [7] "exportPattern"     "exportClass"       "rawNamespace"     
[10] "useDynLib"         "exportMethod"      "importClassesFrom"

> setdiff(names(newTags), names(oldTags))
[1] "inherit"          "inheritDotParams" "inheritSection"   "md"              
[5] "noMd"     
```

**Comment by hadley** [comment]
Does that actually work? I don't think including `@export` in a template would get pulled in in the right place

**Comment by kevinushey** [comment]
Looks like it didn't; I was getting lucky as I had duplicated the `@export` tag in the actual roxygen comment header. Whoops!

Consider this a bug in `sparklyr`, not in `roxygen2` :)

**Comment by hughjonesd** [comment]
Just hit this issue myself. Not sure if it is easy to do, but it would be very intuitive if templates could include `@export`. I assume that at the moment `namespace_roclet` doesn't deal with them.
