### ISSUE TITLE
Hide documentation of non-exported functions

### ISSUE THREAD

**Issue by danielsjf** [klutometis/roxygen#523]
In the case of master functions, it is nice to let the slave functions inherit certain parameters. Unfortunately, even if I don't export the master function, it still shows the documentation. Is it possible to hide the documentation of non-exported functions?

The specific use case is that my master function has more arguments than I use in the slave functions for debugging reasons. I don't specifically want to show these additional arguments to the users of the package.

**Comment by hadley** [comment]
It's not possible to have documentation that you can inherit from, and yet is not turned in to Rd.
