### ISSUE TITLE
FR: API page

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#524]
How about documenting the entire API of a package (function names and interface) on a single page? This would simplify checking the API differences between two versions. Could be useful for pkgdown, too.

**Comment by hadley** [comment]
My gut feeling is that this is out of scope for roxygen2, and it would be better to have a package focussed specifically on API diffs (i.e. not only extracting the API from a given package, but also computing the diff). Other tools are likely to want something in a friendlier format than .Rd.

cc @wch since he's also been thinking about this.

**Comment by wch** [comment]
The use case we've talked about is finding in which versions functions have been added, removed, or changed. There are a lot of times that I've wanted to find which version of R added a particular function or argument to a function.

cc @gaborcsardi because this sounds like something he'd be into.

**Comment by gaborcsardi** [comment]
Indeed, this is interesting. 

I agree with @hadley that it does not really belong in roxygen. This said roxygen has a nice and tested parser, so I guess it would be possible to implement this as a roclet, in another package.

As a first step, it could just export the parsed functions and arguments, in some nice format. (Btw. does roxygen parse all functions, or just the ones with a `#'` header?)

Based on this, both of these things (i.e. @krlmlr 's nice API page, and @wch 's tool for computing on the API) could be done, "relatively" easily.

**Comment by hadley** [comment]
I'm pretty sure it parses everything, but I don't know where the filtering out happens. Should be straightforward to change if the current behaviour doesn't suit.

**Comment by hadley** [comment]
I'm going to close for now, since it seems like this should be its own package.
