### ISSUE TITLE
setAs with @describeIn giver missing object error

### ISSUE THREAD

**Issue by gdkrmr** [klutometis/roxygen#526]
``` r
#' A class for testing stuff
#'
#' @export
setClass('testClass',
          slots = c(dat = "data.frame"),
          prototype = list(dat = data.frame()))


#' @name as
#' @describeIn testClass convert to data.frame
setAs("testClass", "data.frame",
      function(from) {from@dat})
```

gives the following error:

```
Error: @describeIn must be used with an object
```

also a nice feature would be not having to write `@name as`

**Comment by hadley** [comment]
What exactly do expect the documentation to look like? i.e. what should the usage section show?

**Comment by gdkrmr** [comment]
That really is a good question, I thought roxygen would take care of this ;-). I think `Matrix-class` from the `Matrix` package could serve as a template.

**Comment by hadley** [comment]
That page doesn't really document the coercion methods? I don't use`setAs()` so I have no idea what you are expecting.

**Comment by gdkrmr** [comment]
It shows up under Methods, the coercion methods are mentioned:

```
Methods:
...

     as.vector ‘signature(x = "Matrix", mode = "missing")’:
          ‘as.vector(m)’ should be identical to ‘as.vector(as(m,
          "matrix"))’, implemented more efficiently for some
          subclasses.

     as(x, "vector"), as(x, "numeric") etc, similarly.

     coerce ‘signature(from = "ANY", to = "Matrix")’: This relies on a
          correct ‘as.matrix()’ method for ‘from’.
...
```

There should probably be a way to put similarly to a method into a class documentation using `@describeIn`. It would probably make sense to be able to put both conversion methods (`as(classA, "classB")` and `as(classB, "classA")`) in either the documentation of `classA` or `classB`.
E.g. both documentations of `as` should go into `testClass-class` under Methods:

```r
#' A class for testing stuff
#'
#' @export
setClass('testClass',
          slots = c(dat = "data.frame"),
          prototype = list(dat = data.frame()))

#' @describeIn testClass convert to data.frame by extracting the dat slot.
setAs("testClass", "data.frame",
      function(from) {from@dat})

#' @describeIn testClass convert from data.frame by putting the data frame into the dat slot.
setAs("data.frame", "testClass",
      function(from) {new("testClass", dat = from)})
```

**Comment by LiNk-NY** [comment]
I don't know if you want to have all the `setAs` coercion functions in separate documentation (as `@name as` implies). I would rather create a `@section Coercion:` and document methods there. 

```
#' @section Coercion: 

\code{as(testClass, "data.frame"): Convert testClass to data.frame by extracting the dat slot. 
```

Also, your first example looks like an S4 accessor function and not a coercion function.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
