### ISSUE TITLE
devtools::document() error for global variable that uses an external function

### ISSUE THREAD

**Issue by fangly** [klutometis/roxygen#533]
Hi,

I am trying to set some constants, i.e. read-only global variables, in a package I am writing. But I have a roxygen2 problem when running devtools::document():

```
> devtools::document()
Updating dummy documentation
Loading dummy
Error in eval(expr, envir, enclos) (from constants.R#4) : 
  could not find function "as.integer64"
```
The traceback looks like:
```
> traceback()
9: eval(expr, envir, enclos)
8: eval(exprs[i], envir)
7: source_one(file, envir = envir)
6: source_many(paths, env)
5: force(code)
4: withr_with_dir(file.path(pkg$path), source_many(paths, env))
3: load_code(pkg)
2: load_all(pkg)
1: devtools::document()
```

My minimal R example file, "constants.R" looks like this:
```R
#' @importFrom bit64  as.integer64
NULL

CONSTANT <- as.integer64(123)
```

And the "Imports:" section of my DESCRIPTION file does list the bit64 package, so, there really is no reason that "as.integer64" should not be found.

Fully qualifying the external functions (replacing as.integer64 by bit64::as.integer64 in the code) allows devtools::document() to run through and generate the NAMESPACE file, as expected. From then on, it's possible to revert to "as.integer64" (not fully qualified) and to run devtools::document() again without issues. Try to remove NAMESPACE, do a "clean & rebuild" in RStudio, a devtools::document() and the problem pops up again.

Note that if I use roxygen2::roxygenize() instead of devtools::document(), the problem goes away.

Cheers,

Florent

PS/ R 3.2.5, roxygen2 5.0.1, RStudio 1.0.44

**Comment by hadley** [comment]
Well if roxygen2 is going to generate the namespace file for you, it obviously can't rely on it existing. So I'd recommend fully qualifying the name in top level code.

**Comment by fangly** [comment]
Thank you for the reply, Hadley.

1/ As an end-user, I would expect roxygen to behave equally if I have the top-level expression 
```R
CONSTANT <- as.integer64(123))
```
or not
```R
CONSTANT <- function() {as.integer64(123)}
```
. After all, with my @importFrom statement, I have provided roxygen with all the information needed to generate a NAMESPACE.

2/ roxygenize() happens to handle the same issue without problem, which suggests that handling such cases is tractable.

I am not intimate with the internals of roxygen, and I fully appreciate that fixing this issue might be too much work for your perceived benefits. In that case, though it would be great to display a friendly error message (if possible) or at least to document this limitation (I have perused the documentation several times and have seen no mention of it).

Cheers,
Florent

PS/ If you feel that this issue is more devtools-related, I would be happy to report it there.

**Comment by hadley** [comment]
It's simply not possible - roxygen2 has to execute the code in the package in order to document it, and it can't execute your code without the NAMESPACE, which it is creating! It's a chicken and egg problem.

The fact that it works with `roxygenise()` just indicates that two bug are cancelling each other other

**Comment by fangly** [comment]
Got you, thank you for the explanations.
Florent

**Comment by gaborcsardi** [comment]
Just to be the devil's advocate. I agree with @fangly that the current behavior can be surprising, and even if it has happened to me many times, I always need to figure it out.

For generating the imports, I don't think you need to parse and run the code in the package. In theory we could also just replace all code chunks (or even code lines) with `foobar-xxx`, and generate a `NAMESPACE` from the dummy files. The exports in the `NAMESPACE` would be wrong, obviously, but the imports would be correct I believe. (But FIXME.)

Yes, this is a hack, but I think it would still make sense to do it.

**Comment by hadley** [comment]
@gaborcsardi in that case you're asking for #372 😉

**Comment by fangly** [comment]
Sounds good to me. I will subscribe to #372 then.
