### ISSUE TITLE
Links to S4 classes

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#536]
Ideally, `[SQLiteConnection]` would be translated to `\code{\linkS4class{SQLiteConnection}}`, but that's probably wishful thinking. How about `[SQLiteConnection-class]`?

**Comment by gaborcsardi** [comment]
Hmmm. AFAIR we do not have the documented object available, so we cannot tell if it is S4 or not. (Which is a pity, but we discussed this already I think, and it would require too many changes.)

Personally I don't mind `-class`, but are you sure that these are all S4 classes?

**Comment by krlmlr** [comment]
I'm not sure that it's always S4, can you propose a more robust syntax?

**Comment by hadley** [comment]
Doesn't \linkS4class just add a suffix?

**Comment by hadley** [comment]
Any more thoughts on this?

**Comment by krlmlr** [comment]
I don't know how `\linkS4class` is processed internally, but `[DBIConnection-class]` is translated to `\link{DBIConnection-class}`. The link is clickable and points to the right topic. Should we just be stripping the `-class` here?

**Comment by gaborcsardi** [comment]
It seems like @hadley is right, and `linkS4class` just adds `-class` to the target.

So yes, `[DBIConnection-class]` does work. If you don't want the `-class` form in the text, then yes, we can strip it. I assume that this won't surprise anyone too much.

If we don't strip, then you would need to write `[DBIConnection][DBIConnection-class]` which is rather clumsy.

**Comment by gaborcsardi** [comment]
So if @hadley is fine with the stripping, I can do a PR.

**Comment by hadley** [comment]
Stripping sounds good

**Comment by krlmlr** [comment]
I wonder if we could also support `[DBIConnection]` that checks if a topic `DBIConnection-class` exists, and uses the `\linkS4class{}` syntax in this case.

**Comment by gaborcsardi** [comment]
@krlmlr what if both exist? Can you check at all if a topic exists? Doesn't this depend on the order of the processing of the files? Also, checking this might be hard if referring to another package.

**Comment by krlmlr** [comment]
I'm not sure if the list of available topics (internal or external) is available at this stage. Stripping sounds way easier, let's do that.

**Comment by hadley** [comment]
Does this need to be done before release?

**Comment by krlmlr** [comment]
Having this in the released version would give a nicer source for the DBI spec.

**Comment by gaborcsardi** [comment]
I can write it today.

**Comment by hadley** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
Sorry, vis major yesterday. But here it is today: #551
