### ISSUE TITLE
documenting generic expressions

### ISSUE THREAD

**Issue by markvanderloo** [klutometis/roxygen#540]
Hi there,

I would like to build on `roxygen2` to be able add metadata to general expressions, for example
```r
#' Age positivity
#' @name agepositive
age > 0

#' Legal employment age
#' @name legal_age
if ( age < 15 ) job_status == "no job"
```
and so on. The use case is our [validate](https://github.com/data-cleaning/validate) package, where an expression is a statement used to check data against domain knowledge.

I can't use `roxygenize` with custom roclets because that calls `parse_text` , and that  evaluates the above code using `sys.source`.

However, I would probably be saved if I can call the now unexported `parse_blocks` or have the option to make `parse_text` skip the evaluation part.

So my question is to please consider one of these options (or another I haven't seen) to support documenting generic expressions.

**Comment by hadley** [comment]
This feels out of scope for roxygen2 to me. I'd prefer not to export currently internal code, but I'd consider a PR
