### ISSUE TITLE
Trouble with lower-case/upper-case under Windows

### ISSUE THREAD

**Issue by sfeuerriegel** [klutometis/roxygen#545]
I encountered an issue under Windows that occurs when renaming a function (class) from lower-case to upper-case or vice versa. 

* Let's assume a function named "Function". Roxygen now creates a file "Function.Rd". 
* When renaming it to "function". Roxygen does not delete the "Function.Rd" file or, alternatively, rename it to "function.Rd".
* The result is a mismatch when using devtools::check() as the filenames our identical.

**Comment by gaborcsardi** [comment]
Yeah, the same on macOS, if the file system is case insensitive.

**Comment by hadley** [comment]
I don't see any straightforward way of handling this (with doing a lot of work). You can work around the problem by running `roxygen(clean = TRUE)` which first deletes all `.Rd` files before generating afresh.
