### ISSUE TITLE
Add signature of exported function as a comment to NAMESPACE

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#546]
```
export(function) # x, y = NULL, ..., .dots = list()
```

For easier tracking of interface changes.

@hadley: Would you support this feature?

**Comment by hadley** [comment]
I think this is out of scope for roxygen2. @gaborcsardi is considering indexing this metadata for all cran packages (across multiple versions), which you could then use to generate appropriate description of API changes
