### ISSUE TITLE
Provide suitable default filename for objects with names starting with a dot

### ISSUE THREAD

**Issue by renozao** [klutometis/roxygen#548]
The default filename for objects whose name start with a dot is invalid and skipped/deleted.
Is this on purpose?
Adding the following step to `nice_name` would solve the issue of having to provide a `@rdname` for those objects:
```R
x <- str_replace_all(x, "^\\.", "dot-")
```

There always is `@keywords internal` for the cases where one wants to document an object but does not want the man page to be listed.

**Comment by hadley** [comment]
Generally, by convention, it's bad form to have an exported object that starts with a dot. But I'd consider a PR.

**Comment by renozao** [comment]
The use case is not for exported objects, but for documenting internal objects.
