### ISSUE TITLE
How to link to operators defined in other packages using Markdown?

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#550]
e.g., `magrittr::%>%`, as in `\code{\link[magrittr]{\%>\%}}`?

CC @gaborcsardi.

**Comment by gaborcsardi** [comment]
I don't think it is possible, at least not without commonmark extensions. Even if you escape the special characters, the markdown parser just parses `[magrittr::%>%]` as text. 

I don't know if an extension could do this. For now, we should probably have a section in the vignette, about things that need to be Rd, e.g. this, tables, formulas, etc.

**Comment by krlmlr** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
@krlmlr Please re-open and then I'll submit a PR that documents this.
