### ISSUE TITLE
Export helper functions for custom roclets

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#559]
- [ ] `made_by()` (with new optional argument "package name")
- [ ] `made_by_roxygen()`  (with new optional argument "package name", consider renaming to `check_made_by()`)
- [ ] `write_if_different()`

Use case: API roclet in [functionmap2 package](https://github.com/r-pkgs/functionmap2)

**Comment by hadley** [comment]
In some sense those aren't really part of roxygen2's API. I wonder if it would be better to have a small helper package for just that functionality (I end up using it in quite a lot of places)

**Comment by krlmlr** [comment]
I'll be adding `read_lines()` and `write_lines()` (with encoding) to utf8, could support these features there (as arguments to these functions).

**Comment by krlmlr** [comment]
Just saw readr has much better support for reading/writing text files. Should we rather enhance the readr functions?
