### ISSUE TITLE
Markdown headers

### ISSUE THREAD

**Issue by jeroen** [klutometis/roxygen#560]
Adding a markdown header yiels a strange error message:

```r
#'  Blabla bla
#' 
#' ## Output streams
#'
#' Blabla
```

Same happens for underline header

```r
#' Blabla
#'
#' Output streams
#' ---
#'
#' Blabla
```

This is the error:

```r
> roxygen2::roxygenise()
Error in markdown_rparse(markdown_tags[[xml_name(xml)]](xml), markdown_tags = markdown_tags) : 
  attempt to apply non-function
```

**Comment by gaborcsardi** [comment]
HEaders are not supported, but I agree that the error message should be better.

**Comment by jeroenooms** [comment]
OK. Is there any way to get custom section titles such as e.g. in `?connection` manual page?

**Comment by gaborcsardi** [comment]
@ section ?

**Comment by jeroenooms** [comment]
OK thanks :) I assumed it was a layout feature, not a `Rd` tag. Perhaps we can map markdown headers to `@section` tags.

**Comment by gaborcsardi** [comment]
WEll, `@section` is a roxygen tag, not Rd. Right now we do a separate markdown parsing for each roxygen tag.

**Comment by brodieG** [comment]
Fyi, this gets triggered by having something like `#' <hello hello>` in the docs, presumably because it tries to interpret it as some kind of markup tag and there is no equivalent value `roxygen2:::markdown_tags`.

**Comment by jarauh** [comment]
It would be good to mention in the documentation that sections are not supported.  The introduction of https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html ends with:

> See http://commonmark.org/help/ for more about the parser and the markdown language it supports.

This suggests that roxygen2 does work with sections.
