### ISSUE TITLE
roxygen2 version 6.0.0 warnings for reference class documentation

### ISSUE THREAD

**Issue by christophergandrud** [klutometis/roxygen#571]
I just upgraded to version 6.0.0 and am now getting a similar series of warnings for a package's reference class documentation, e.g.:

```
Updating Zelig documentation
Loading Zelig
Warning: @import [model-zelig.R#6]: unknown tag
Warning: @export [model-zelig.R#7]: unknown tag
Warning: @exportClass [model-zelig.R#8]: unknown tag
Warning: @import [model-timeseries.R#4]: unknown tag
Warning: @export [model-timeseries.R#5]: unknown tag
Warning: @exportClass [model-timeseries.R#6]: unknown tag
Warning: @export [model-timeseries.R#150]: unknown tag
Warning: @import [model-ma.R#5]: unknown tag
Warning: @export [model-ma.R#6]: unknown tag
Warning: @exportClass [model-ma.R#7]: unknown tag
Warning: @import [model-ar.R#5]: unknown tag
Warning: @export [model-ar.R#6]: unknown tag
Warning: @exportClass [model-ar.R#7]: unknown tag
and so on.
```

Any idea what's going on. (I'ld be happy to provide sessionInfo, etc if that would help.)

This should be reproducible with:

```r
library(devtools)
install_github('IQSS/Zelig')
document(roclets=c('rd'))
```

**Comment by hadley** [comment]
It's because of this: `document(roclets=c('rd'))` — those tags are all namespace tags, and since you're not using the namespace roclet, it doesn't know about the tags.

**Comment by christophergandrud** [comment]
Ah, got it. So the behaviour hasn't changed, but the warning is new?

**Comment by hadley** [comment]
Right — previously all tags were always registered, regardless of what roclets were used. Now each roclet is in charge of registering the tags that it uses.

**Comment by christophergandrud** [comment]
Thanks for the info.
