### ISSUE TITLE
R files not getting roxygenized after upgrade to 6.0.0.

### ISSUE THREAD

**Issue by bhaskarvk** [klutometis/roxygen#572]
```r
d> packageVersion('roxygen2')
[1] ‘6.0.0’
d> packageVersion('devtools')
[1] ‘1.12.0’
```

Everything under `man` is deleted and NAMESPACE contains nothing.
This started happening after upgrading to 6.0

**Comment by hrbrmstr** [comment]
I did an install from source (my home mini-CRAN didn't seem to have macOS binaries yet) and can't reproduce even if I add `@me` blocks.

**Comment by bhaskarvk** [comment]
I built roxygen2 and devtools both from source and it's still happening for me. Interestingly it's happening for 

- https://github.com/rstudio/leaflet
- https://github.com/bhaskarvk/leaflet.esri

But working for 
- https://github.com/bhaskarvk/leaflet.extras
https://github.com/bhaskarvk/colormap

So not sure what exactly is missing. Will debug more.

**Comment by bhaskarvk** [comment]
And, found the problem.

https://github.com/klutometis/roxygen/pull/570

**Comment by bhaskarvk** [comment]
Keeping open till 570 is merged.
