### ISSUE TITLE
New roxygen 6.0.0 is deletes all .Rd files and leaves empty NAMESPACE

### ISSUE THREAD

**Issue by lukasz-bednarz-reddeersystems** [klutometis/roxygen#574]
I have just upgraded to latest version of roxygen 6.0.0 and one of my private packages stopped builing completely.
Roxygen deletes all .Rd files without writing new ones and deletes all contents of NAMESPACE.

The only difference that exist in the package that doesn't build with 6.0.0 is that I am exporting classes that are built in real-time by class builder

#' derived class SomeDerivedClass
#'
#' @title SomeDerivedClass
#' @name SomeDerivedClass-class
#' @docType class
#' @rdname SomeDerivedClass-class
#' @exportClass SomeDerivedClass

derived_class_factory("SomeDerivedClass",  ....)

here derived_class_factory invokes "setClass" that creates new class based on its parameters.

Would this possibly unsettle new version of roxygen?

How can I possibly debug this issue? I am not able to share the package as it is internal development.

At the moment I have rolled back to 5.0.1 and it works.

Regards,

Lukasz

**Comment by hadley** [comment]
You probably have a blank line in your Rbuildignore. It's fixed in dev
