### ISSUE TITLE
Empty lines in .Rbuildignore makes roxygenize skip all files

### ISSUE THREAD

**Issue by renozao** [klutometis/roxygen#575]
If there is an empty line in `.Rbuildignore` then the function `ignore_files` filters out all files, which is not consistent with what happens when building the package with `R CMD build`. 
Removing empty lines would solve the issue:

```R
# Remove any files that match any perl-compatible regexp
patterns <- readLines(rbuildignore, warn = FALSE)
patterns <- patterns[nzchar(patterns)]
```

**Comment by hadley** [comment]
Already reported and fixed
