### ISSUE TITLE
Roxygen 5.0.1 clears DESCRIPTION file that was built with Roxygen 6.0.0 before

### ISSUE THREAD

**Issue by sjPlot** [klutometis/roxygen#577]
I'm not sure whether I can reproduce this issue, but the steps were:

  * I updated packages on my Win Laptop, Roxygen was updated to 6.0.0
  * Later, when I used my Mac (R files synced via cloud), where I did not update packages and used Roxygen 5.x, the description-file was completely cleared when building my package (except for the RoxygenNote-line)

On both win and mac, I use R 3.3.2, RStudio 1.0.136 and use devtools to build packages.

**Comment by hadley** [comment]
roxygen now uses the desc package for all reading and writing, so it's likely the bug lies there.

**Comment by gaborcsardi** [comment]
@sjPlot Do you think that this is reproducible?
