### ISSUE TITLE
WARNING: roxygen2 6.0.0 clears NAMESPACE and deletes man/*.Rd files

### ISSUE THREAD

**Issue by HenrikBengtsson** [klutometis/roxygen#578]
**I'd flag this a HIGH-PRIORITY ISSUE, because if someone is not using version control and if someone is just starting to use roxygen2 6.0.0, there seems to be a risk that they loose their files.** (I hope I'm wrong)

Sorry, don't have much time today for more than a quick report: After updating to roxygen2 6.0.0, running `roxygen2::roxygenize()` will clear the `NAMESPACE` file (leaving a single line `# Generated by roxygen2: do not edit by hand`) and and delete all `man/*.Rd` files.

# Reproducible example
```sh
$ git clone https://github.com/HenrikBengtsson/listenv.git
$ cd listenv
$ Rscript -e "roxygen2::roxygenize()"
Writing NAMESPACE
Deleting as.list.listenv.Rd
Deleting cash-.listenv.Rd
Deleting cash-set-.listenv.Rd
Deleting get_variable.Rd
Deleting length.listenv.Rd
Deleting listenv.Rd
Deleting map.Rd
Deleting names.listenv.Rd
Deleting parse_env_subset.Rd
Deleting undim.Rd
```

As suggested by https://twitter.com/hrbrmstr/status/827476343264780290 and https://twitter.com/M2RUseR/status/827510563282485249, this is due to empty lines in `.Rbuildignore`;
```sh
cat .Rbuildignore 
#----------------------------
# Git and SVN related
#----------------------------
^.svn
^.git
^.make
INSTALL[.]md
OVERVIEW[.]md
README[.]md

#----------------------------
# Travis-CI et al.
#----------------------------
^[.]travis[.]yml$
^travis-tool[.]sh$
^pkg-build[.]sh$
^appveyor[.]yml$
^covr-utils.R$
^[.]covr[.]R$

#----------------------------
# R related
#----------------------------
^cran-comments[.].*$
^vignettes/.*[.](pdf|PDF)$
^vignettes/.*[.](r|R)$
^vignettes/[.]install_extras$
^Makefile$
^incl
^NAMESPACE,.*[.]txt$
^nohup.*$
^[.]R
^[.]benchmark
^[.]devel
^[.]test
^[.]check
^.*[.]tar[.]gz$
```

Commenting out or removing those empty lines in `.Rbuildignore` avoids the problem.

Note that also empty trailing lines causes this problem to occur.

**Comment by gaborcsardi** [comment]
Fixed already:  #570

**Comment by HenrikBengtsson** [comment]
Thxs.  Leaving this open for the notice (but if maintainers wish to close, feel free to do so).

**Comment by kevinushey** [comment]
I was hit by this as well; I'd say this warrants a patch release to CRAN.

**Comment by hadley** [comment]
Yeah I'll do it when I get back on Monday. 

(It's not quite as severe as it looks because there's no data loss. It's just roxygen not regenerating any of the files that it generated)

**Comment by jjallaire** [comment]
In my configuration it removed all of my roxygen generated Rd files. Agreed this isn't technically "loss" since the files can be re-generated with a patched or older version of Roxygen but many users may not realize this and experience it losing all of their Rd files. Also if users don't know how to downgrade Roxygen e.g. using `devtools::install_version` they may get stuck. All of this to say I do think it's severe enough to warrant a patch release right away.

**Comment by hadley** [comment]
On its way to CRAN now
