### ISSUE TITLE
roxygen v6.0.0 fails to produce any .Rd file if .Rbuildignore includes blank lines

### ISSUE THREAD

**Issue by joethorley** [klutometis/roxygen#581]
I have never had this problem before but since upgrading to v6.0.0 on OSX with latest R and Rstudio the problem has occurred twice.

To replicate pull
https://github.com/poissonconsulting/subfoldr
and add a space between 
^output$
^report$

in the .Rbuildignore file

**Comment by gaborcsardi** [comment]
Known issue, reported several times, see e.g. #578. It was fixed in version 6.0.1, please upgrade.
