### ISSUE TITLE
Import and export are reordered, which prevents exports of imported objects from working

### ISSUE THREAD

**Issue by ugroempi** [klutometis/roxygen#591]
I maintain the package DoE.base; I am currently working on removing an obstacle in my package that prevents the functionality from working if my package is not loaded and thus forces other packages to depend on the package. The issue below is concerned with how to enable roxygen users to obtain the namespace file in the form needed for my package to work without being depended upon.

My package heavily relies on objects (mainly orthogonal arrays) present in and exported from the package namespace. There are various functions in the package that rely on these objects being on the search path, and it would be a lot of work, sometimes probably also quite difficult, to locate and change all this code to explicitly refer to those objects in the unloaded package namespace. A straightforward solution is for users who want to make the functionality work from within their package but not depend on my package to export those crucial objects from their package namespace, after importing them from my package. 

This requires the namespace to import many objects from my package and *afterwards* export some of them; I am not an experienced roxygen2 user. When doing a small test package, I noticed that roxygen2 seems to move the imports after the exports, even if they are provided before the exports. Is there a way with roxygen2 to address a namespace requirement like the one outlined above?

Best regards,
Ulrike

**Comment by hadley** [comment]
The order is not important in the namespace. I have many packages with:

```
export("%>%")
importFrom(magrittr,"%>%")
```

So something else must be going on in your case
