### ISSUE TITLE
Unicode changed to symbol in usage section

### ISSUE THREAD

**Issue by brry** [klutometis/roxygen#592]
Roxygen2 6.0.1 changes unicode statements in function defaults.
In the usage section, rather than keeping \Uxxxx, it writes the represented symbol.
On Windows with German locale, this leads roxygenise to get stopped by an encoding error if run repeatedly.
Here is some code to reproduce the error.

```r
devtools::create("dummypack", list(License="GPL-2"))
devtools::check("dummypack") # no errors, warnings or notes

cat("
  #' Some function
  #' @importFrom graphics plot
  #' @param b Some label
  a <- function(b = '7\\U{00B0}C') {plot(1, main=b)}
", file="dummypack/R/a.R")

devtools::document("dummypack") # works
#Updating dummypack documentation
#Loading dummypack
#Writing NAMESPACE
#Writing a.Rd

devtools::document("dummypack")  # error!!!
#Updating dummypack documentation
#Loading dummypack
#Error in gsub("\n", "\r\n", contents, fixed = TRUE) : 
#  input string 1 is invalid UTF-8

berryFunctions::tryStack(devtools::document("dummypack"))
# devtools::document -> withr::with_envvar -> force -> roxygen2::roxygenise -> 
# unlist -> lapply -> FUN -> roclet_output -> roclet_output.roclet_rd -> 
# mapply -> write_if_different -> same_contents -> gsub -> 
# gsub("\n", "\r\n", contents, fixed = TRUE)[1] "Error in gsub(    [...]

unlink("dummypack/man/a.Rd")
devtools::document("dummypack") # works
devtools::document("dummypack") # error
unlink("dummypack/man/a.Rd")
devtools::check("dummypack") # fails with gsub UTF8 error as well

rd <- readLines("dummypack/man/a.Rd")
rd[7] <- "a(b = \"7\\U{00B0}C\")"
writeLines(rd[-1], "dummypack/man/a.Rd")

devtools::document("dummypack") # works
devtools::document("dummypack") # works
devtools::check("dummypack") # works fine
 
unlink("dummypack", recursive = TRUE)
```

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252

**Comment by brry** [comment]
If at the very beginning of the code block above, I set `Sys.setlocale(locale="C")`, then I have no warnings with `document`, but `check` points out mismatches, because in the Rd file, Roxygen writes `<U+00B0>` instead of `\U{00B0}`, see https://github.com/klutometis/roxygen/issues/452.

**Comment by jranke** [comment]
Just a quick note that I am also affected by this issue. Thanks for taking the time to document it.

**Comment by jranke** [comment]
The problem is  - on my Windows 7 box - that the .Rd file that is written out contains characters in latin1 encoding. On Linux everything works fine here.

I wrote a test to investigate the problem:

https://github.com/jranke/roxygen/commit/db1320b720e771760d4116a6acda4f872e654857

**Comment by jranke** [comment]
Not a new issue:

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16064

**Comment by jranke** [comment]
@hadley Thanks, using unicode in default values for function arguments works nicely now!!!
