### ISSUE TITLE
Roxygen2 new version C stack usage issue with S4 methods

### ISSUE THREAD

**Issue by sylvainschmitt** [klutometis/roxygen#597]
Hello,

For a week I've got issue to use Roxygen2 to write my package documentation with `devtools::document` function. Searching for an answer I tried to upload and document the last stable version off the package. And surprise documentation doesn't work anymore I got the same issue :

> Error: C stack usage  7972080 is too close to the limit

So I checked and the only change is that I were using the 4.0.1 version on my last stable version of the package and now Roxygen2 is on 6.0.1 version. nevertheless when I install the old version I can't document my old stable version. When I use the `traceback` function it appears it is due to an infinite loop when trying to document code S4 method. Any idea for the reason, or maybe for a solution to get my documentation in waiting ?

**Comment by sylvainschmitt** [comment]
After a lot of search it appears it is due to the import of `spThin (>= 0.1.0)` package in my `DESCRIPTION` file. I'll try to figure out what the issue with the SpThin package because I need the dependency and S4 methods documentation. But if you have any idea I'm interested..

PS : I tried reinstalling the package but it didn't change anything

**Comment by hadley** [comment]
Please provide a reproducible example. For this problem, that will be a minimal package that demonstrates the problem.

**Comment by sylvainschmitt** [comment]
Thank you for looking at it. I tried to reproduce the error by creating a minimal package importing `spThin` package and using the `thin` function. And it didn't throw any error when documenting with `devtools::document()` . Whereas for my current package in development the issue is still here and disappear as soon as I remove `spThin` from Imports filed in DESCRIPTION file. So I need to search more deeply what's really  creating the error in my current package in development. I come back to you as soon as I get it.
