### ISSUE TITLE
Problem with suggests/import

### ISSUE THREAD

**Issue by jpfrench81** [klutometis/roxygen#598]
I have an R package (autoimage) that suggests the akima package but does not import it because of licensing issues.  However, certain functionality is enabled when the akima package has been installed by the user.  

My code uses akima::interp to call the relevant function from the akima package, causing roxygen to add this as importFrom in the namespace.  This causes an error when checking the package because the akima package is only suggested.

Would it be possible to have an exclude_importFrom tag to prevent adding a package to namespace when it is only suggested?

The github repository for the package in question is https://github.com/jpfrench81/autoimage.

**Comment by gaborcsardi** [comment]
You are adding the import yourself: https://github.com/jpfrench81/autoimage/blob/ca05244338422bbbbdf2da6739326633dd51174d/R/ggautoimage.R#L60

Remove this line (and other similar lines if you have more of them).

**Comment by jpfrench81** [comment]
You're 100% correct.  Apologies for the error.
