### ISSUE TITLE
Commented out line that starts with apostrophe messes up export

### ISSUE THREAD

**Issue by PeterVermont** [klutometis/roxygen#599]
See my  [Stackoverflow comment](http://stackoverflow.com/a/42513528/283973)

> I had a similar problem. It turned out that inside my function I had commented out a line that began with an apostrophe (in front of 'Battlestar Galactica' in my fake example) so it look like this:
> 
> #' @export
> getMyFavoriteSciFiShows <- function() {
>   myFavoriteSciFiShows <-
>     c('Star Trek Next Generation',
>       #'Battlestar Galactica',
>       'Babylon 5')
>   return(myFavoriteSciFiShows)
> }
> This really screwed up roxygen2 v 6.0.1 since it did not signal any errors and this is what it put into my NAMSEPACE file:
> 
> export("Galactica',")
> export(Battlestar)

**Comment by hadley** [comment]
Yes, because that's a roxygen comment.

**Comment by PeterVermont** [comment]
Why does a roxygen comment affect export?

**Comment by hadley** [comment]
Because that's what roxygen parses to generate the documentation
