### ISSUE TITLE
Namespace directive order should honour Collate order

### ISSUE THREAD

**Issue by renozao** [klutometis/roxygen#601]
Currently, the namespace roclet sorts the directives, which causes check and loading warnings of the following sort:

```
Found the following significant warnings:
  Warning: replacing previous import ‘Rcpp::prompt’ by ‘utils::prompt’ when loading ‘pkgA’
```

These warnings can be avoided by forcing package import order in the `NAMESPACE` file.
However, this is not possible when this file is generated by roxygen, because of the default sort. 
Users should be able to control order by having the `@import` tags parsed in the correct order, which can be achieved easily if the namespace directives are output directly without sorting.

That is having :
```R
roclet_process.roclet_namespace <- function(x, parsed, base_path,
                                            global_options = list()) {
  ns <- unlist(lapply(parsed$blocks, block_to_ns)) %||% character()
  unique(ns)
}
``` 
instead of
```R
roclet_process.roclet_namespace <- function(x, parsed, base_path,
                                            global_options = list()) {
  ns <- unlist(lapply(parsed$blocks, block_to_ns)) %||% character()
  sort_c(unique(ns))
}
```

**Comment by gaborcsardi** [comment]
What if someone wants a NAMESPACE import order that is different from the Collate order? Or that doesn't happen?

Btw. I think a good workaround is to **not** import conflicting names, but refer to them with `utils::prompt` and `Rcpp::prompt`. This is also more readable, as the reader does not have to think where a given reference to `prompt` is coming from.

**Comment by renozao** [comment]
Currently there is no choice in the order. Following Collate order does not really impose any specific order, because the user decides in which file to place the `@import` tags and can choose the Collate order. The point is that it enables the user to fully control the order: any order can be achieved.

It looks like that most of these are not real conflicts, but S4 generics defined for existing S3 generics which I think are supposed to be fine.
I feel that the workaround of specific import is a bit too much for base packages such as `utils` and `stats`, from which you often need many many functions.
I agree with the explicit namespace calling if there really is a conflict.

While sorting directive makes the NAMESPACE look more tidy, I think this should be a secondary objective, given that the order does matter.

**Comment by gaborcsardi** [comment]
> While sorting directive makes the NAMESPACE look more tidy, I think this should be a secondary objective, given that the order does matter.

That's a good point. Maybe this could be opt-in, because otherwise roxygen will re-order the `NAMESPACE` for everybody, which is annoying.

**Comment by renozao** [comment]
I'd even say why allowing for sorting at all?

My experience is that I only look at the NAMESPACE file to check for
specific things like import/export of specific functions/classes. Or when
there is a loading error due to a bad @export directive.
For that I do a text search to jump to relevant lines, so whether it is
sorted or not does not really matter.
Do you often open the NAMESPACE for reasons that would require nice sorting?

To tidy a bit and help in debugging, one may consider adding comment lines
showing the filename from which the directive was taken. That would
organize directives in blocks.
But it seems too much work for little benefit.

**Comment by renozao** [comment]
In the end, I reckon that the "unsorted" behavior should be an option and one should be conservative to avoid all current NAMESPACE files to be re-written and confuse users.
How about a global option, passed to `roclet_process`? 
Making a pull request with this now, although a cleaner solution would be to have roclet specific options.

**Comment by gaborcsardi** [comment]
Maybe you want to wait for Hadley to see what he thinks about this.

**Comment by hadley** [comment]
Sorting is important because it improves git diffs. I would possibly consider a pull request to make it an option, but I think depending on precise ordering of the NAMESPACE is bad practice.

**Comment by renozao** [comment]
I agree with the benefit of having a sorting namespace. The issue is that,
currently, loading a package with a sorted namespace that imports a not so
uncommon combinations packages does result in spurious warnings.
From the point of view of dependency management, it does make sense that
dependencies are imported in the order given by the chain of dependencies,
not by alphabetical order.
I guess that If the unsorted behaviour is optional, then the package
maintainer will be aware of the implication for git diff. I don't think it
would be that big of a problem for most commits.

A middle way could be that directives are still sorted by groups, but
imports are kept unsorted within their group.
