### ISSUE TITLE
S3 methods not registered if created in an unusual way

### ISSUE THREAD

**Issue by hughjonesd** [klutometis/roxygen#603]
Related to #503.

Using github roxygen2, this creates a line `S3method(foo,huxtable)` in NAMESPACE:

```

#' @export
foo <- function(x, ...) UseMethod('foo')

#' @export
foo.huxtable <- function() 'hi'
```

But this (admittedly corner) case, where a function is assigned to the environment, does not:

```
#' @export
foo <- function(x, ...) UseMethod('foo')

make_foo_hux <- function() {
  assign('foo.huxtable', function(x, ...) "hi", envir = parent.frame() )
}

#' @export
#' @name foo.huxtable
NULL

make_foo_hux()
```

**Comment by hadley** [comment]
You'll need to use `@method` to tell roxygen2 that it's an S3 method

**Comment by hughjonesd** [comment]
I'm afraid this also does not seem to write an S3method line in NAMESPACE. Test case:

```

#' A foo
#'
#' With some foo
#'
#' @export
foo <- function(x, ...) UseMethod('foo')

make_foo_hux <- function() {
  assign('foo.huxtable', function(x, ...) "hi", envir = parent.frame() )
}

#' @rdname foo
#' @export
#' @name foo.huxtable
#' @method foo huxtable
NULL

make_foo_hux()

```

**Comment by hughjonesd** [comment]
The only way to do this is to use @s3method, which is deprecated.

**Comment by hadley** [comment]
That is simply not true. Use `@method` to tell roxygen it's an S3 method, then `@export` to export it.

**Comment by hughjonesd** [comment]
Strong words! 

The test case above generates the following NAMESPACE for me:

```
# Generated by roxygen2: do not edit by hand

export(foo)
export(foo.huxtable)
```

No "S3method" line.

I also tried putting `@method` first, followed by `@export`. I tried it with and without `@name`. These all generate the same file.

I am using Roxygen2 6.0.1. I've also tried with the Github version. Tell me if you need other details.

**Comment by hughjonesd** [comment]
I hope someone will look again at this. I am worried that the deprecated `@s3method` will be removed, whereupon I won't be able to create documentation using Roxygen. If my test case above is doing something wrong, please say.

**Comment by egnha** [comment]
@hughjonesd You could try the `@evalNamespace` tag (new in 6.0.1.9000), which enables you to insert literal NAMESPACE entries:
```R
#' @evalNamespace "S3method(foo,huxtable)"
NULL
```
Would that do what you need?

**Comment by hadley** [comment]
Or just `@rawNamespace`

**Comment by hughjonesd** [comment]
That would probably fix it :-) I'll look forward to the new version.

David

**Comment by egnha** [comment]
@hadley Silly me :-/, thanks for the correction.
