### ISSUE TITLE
Typo in the "Generating Rd files" document

### ISSUE THREAD

**Issue by ximeg** [klutometis/roxygen#610]
In the manual at https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html there is a typo under the section "S4":

## S4
Older versions of **roxyen2** required explicit ...

**Comment by ximeg** [comment]
And the section "Do repeat yourself" should be probably called "Do NOT repeat yourself", shouldn't it?

**Comment by LiNk-NY** [comment]
Hi @ximeg, 
Actually, it should read "Do repeat yourself" as the section heading. 
MR

**Comment by ximeg** [comment]
I fixed "roxyen" typo in bc198c12a8c3a798f88e3f11af93cb2d14110e88. Could you pease merge?

**Comment by hadley** [comment]
Looks like this got merged already. Thanks!
