### ISSUE TITLE
ü is turning into Ã¼ when calling ?my_fun in R 

### ISSUE THREAD

**Issue by levisc8** [klutometis/roxygen#613]
Example: 
#'Hello world
#'@param x Logical
#'@references Carl G, Kühn I (2016)

hello2 <- function(x=TRUE) {
  if(x) print("Hello, world!")
}

After using devtools::document('Mypackage') and then checking the output with ?hello2, the References section reads as follows: 

Carl G, KÃ¼hn I (2016)

Here are the settings in the description file: 

Package: Mypackage
Type: Package
Title: What the Package Does (Title Case)
Version: 0.1.0
Author: Who wrote it
Maintainer: The package maintainer <yourself@somewhere.net>
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.
License: What license is it under?
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.0

There is nothing else in the package. Any suggestions on how I should fix this?

**Comment by gaborcsardi** [comment]
Note that R source files must be ASCII currently. You need to encode non-ascii characters in the `\uxxxx` form. Here is a similar issue with some discussion: https://github.com/hadley/devtools/issues/1421

**Comment by levisc8** [comment]
Ok, that seems to have done the trick. Thanks for your help!

**Comment by shrektan** [comment]
Just add my 2 cents:

> Note that R source files must be ASCII currently. You need to encode non-ascii characters in the 

`\uxxxx` form. Here is a similar issue with some discussion: [r-lib/devtools#1421](https://github.com/r-lib/devtools/issues/1421)

I've read through the discussion [r-lib/devtools#1421](https://github.com/r-lib/devtools/issues/1421). I don't fully agree with the claim that "R source files must be ASCII currently" as it's only meaningful when the user wants it to be published on CRAN.
