### ISSUE TITLE
Segfault running roxygenise in rstudio

### ISSUE THREAD

**Issue by cfhammill** [klutometis/roxygen#614]
Running roxygenize 6 on my package (www.github.com/Mouse-Imaging-Centre/RMINC develop branch) causes rstudio to crash which is a segfault I assume. No problem running in terminal. Seems to be caused by a roxygen block with an @md tag, but still containing classic Rd markup in addition to the markdown.

I'm running R 3.3.1, rstudio 1.0.136

**Comment by denrou** [comment]
I have the same problem (rstudio 1.0.143 and R 3.3.3).
Rstudio crash when I try a `devtools::document()` with some markdown tag in the documentation.

**Comment by gaborcsardi** [comment]
Can one you provide a *small* example for this? RMINC is quite big, I have been running the install process for ~15 minutes now....

**Comment by gaborcsardi** [comment]
Oh, yeah, and the installation process just just failed.... Thanks!
