### ISSUE TITLE
6.0.1 SystemRequirements mangled

### ISSUE THREAD

**Issue by cfhammill** [klutometis/roxygen#615]
Roxygen 6.0.1 is deleting my `SystemRequirements` field and replacing it with `SystemRequirements:SystemRequirements:` . Is this something that needs to go in the package documentation block now?

Edit: manually fixing the requirements field in place and re-roxygenizing seems to solve the problem, it may be a field order problem.

**Comment by gaborcsardi** [comment]
Do you have a reproducible example?

**Comment by cfhammill** [comment]
Yup, run package.skeleton() and replace DESCRIPTION with:

```
Package: anRpackage
Type: Package
Title: What the package does (short line)
Version: 1.0
Date: 2017-03-24
Author: Who wrote it
Maintainer: Who to complain to <yourfault@somewhere.net>
Description: More about what it does (maybe more than one line)
Depends:
    R (>= 3.0.1),
    BatchJobs
Imports:
    dplyr
Suggests:
    igraph
LinkingTo:
    Rcpp
SystemRequirements:
    lsof
License: BSD_3_clause + file LICENSE
LazyLoad: yes
OS_type: unix
SystemRequirements:
URL: https://github.com/Mouse-Imaging-Centre/RMINC
RoxygenNote: 5.0.1
```

Run roxygenise and get the following diff

```
18c18,19
< SystemRequirements:SystemRequirements: 
---
> SystemRequirements:
>     lsof
21a23
> SystemRequirements: 
23c25,26
< RoxygenNote: 6.0.1
---
> RoxygenNote: 5.0.1
> 
```

**Comment by gaborcsardi** [comment]
You have `SystemRequirements:` twice here, so this is not a valid file imo.

**Comment by cfhammill** [comment]
True enough, I didn't realize I had two in there. Sorry for the noise.
