### ISSUE TITLE
FR: Support :: in @import declaration

### ISSUE THREAD

**Issue by ctbrown** [klutometis/roxygen#616]
I think it would be very useful, intuitive to support a syntax such as:

    @import pkg::function [...]

As a substitute for:

    @importFrom pkg function

There are several reasons:
1. There is no real reason for a separate `@importFrom` statement separate from `@import`
2, Explicitly declaring  is a useful practice and should be encouraged.  It makes refactoriing and managing the DESCRIPTION `Imports:` easier. 

Thoughts?

**Comment by rlzijdeman** [comment]
Hi, this now appears to be implemented (see below) and [documented](https://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html).

It's just that if you use ```devtools:document()``` it's not recognized, but if you use ```roxygen2::roxygenize()``` instead, ```import pkg::function``` is processed. Compare both in this output:
```
> devtools::document()
Updating grlcR documentation
Loading grlcR
Writing NAMESPACE
Warning messages:
1: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called ‘httr:GET’
2: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called ‘httr:content’
> roxygen2::roxygenize()
Loading required package: jsonlite
Loading required package: httr
```

The latter results in the following NAMESPACE entry:
```
# Generated by roxygen2: do not edit by hand

...

import("httr:GET")
import("httr:content")
importFrom(jsonlite,fromJSON)
```

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
