### ISSUE TITLE
handle except clauses in import statements?

### ISSUE THREAD

**Issue by vjcitn** [klutometis/roxygen#617]
Is it possible to write an @import directive that produces 

import(foo, except=c(bar,baz)) 

as in 1.5.2 of https://cran.r-project.org/doc/manuals/r-release/R-exts.html

With roxygen2 6.0.1.9000 @importFrom(foo, except=c(bar,baz)) produces an unusable NAMESPACE file.

**Comment by krlmlr** [comment]
You can always use `@rawNamespace` for this:

```
#' @rawNamespace import(shiny, except = runExample)
#' @rawNamespace import(shinyjs, except = runExample)
```

This seems to elevate the requirements for your package to >= R 3.3.0, but otherwise works fine for me.

**Comment by duccioa** [comment]
Hello,
I would like to import `rlang` without the `:=` method. What would the syntax be in this case? 

```
#' @rawNamespace import(rlang, except =  :=)
#' @rawNamespace import(rlang, except =  ":=")
#' @rawNamespace import(rlang, except =  `:=`)
```
All these lines give an `unexpected assignment` error.

Thank you

**Comment by gaborcsardi** [comment]
@duccioa This is a closed issue, and comments on long closed issues often go unnoticed. 

```
#' @rawNamespace import(rlang, except = ":=")
NULL
```
generates the right `NAMESPACE` for me:
```
...
import(rlang, except = ":=")
...
```

Please open a new issue, with a reproducible example. Thanks!

**Comment by duccioa** [comment]
Thank you for your quick reply.
