### ISSUE TITLE
Check file extension when identifying files in R to roxygenise

### ISSUE THREAD

**Issue by mkoohafkan** [klutometis/roxygen#625]
If a user does something silly like leave old documented code files in the R folder, but with the extension `.oldR`, `otheR`, etc. (such as I sometimes do when rewriting functions) Roxygen will still parse the Roxygen comments in those files, potentially leading to namespace weirdness. I'm guessing there's a regex call to blame that searches for `"r$"` rather than `"\.r$"`

**Comment by mkoohafkan** [comment]
woops, wrong rep ;)

**Comment by mkoohafkan** [comment]
I think it's a simple fix to change [this line](https://github.com/klutometis/roxygen/blob/c70dec5dec55628fc7f5788a0c59ba07b9d933c1/R/utils.R#L103) from

`sort_c(dir(file.path(path, "R"), "[.Rr]$", full.names = TRUE))`

to

`sort_c(dir(file.path(path, "R"), "\\.[Rr]$", full.names = TRUE))`

I'll test it and submit a pull request later.

**Comment by hadley** [comment]
Were you still interested in doing the PR?

**Comment by mkoohafkan** [comment]
Sorry, completely forgot---yes, but I won't be able to do it until September (away from computer)

**Comment by hadley** [comment]
Ok, in that case I'll just do myself since it's so small :)
