### ISSUE TITLE
inheritDotParams does not show dot parameters

### ISSUE THREAD

**Issue by nuno-agostinho** [klutometis/roxygen#633]
For instance, in the following code:

```R
#' Pre-styled button
#' 
#' @param id Character: button identifier
#' @param label Character: label
#' @param class Character: class
#' @inheritDotParams actionButton -inputId -label
#' 
#' @importFrom shiny actionButton
#' @return HTML for a pre-styled button
processButton <- function(id, label, ..., class="btn-primary") {
    button <- actionButton(id, label=label, class=class, type="button", ...)
    return(button)
}
```

The dot parameters should include the dot argument from `actionButton`, as the function is simply a wrapper to the other function and the dot argument is desired.

**Comment by hadley** [comment]
What is the dot argument?

**Comment by nuno-agostinho** [comment]
What I meant by dot argument is the `...` from [actionButton](https://shiny.rstudio.com/reference/shiny/latest/actionButton.html). As you can see in that documentation page, it describes the `...` as "Named attributes to be applied to the button or link."

I think that in cases like the one I show above, it could make sense to inherit the description for the `...` argument.

**Comment by hadley** [comment]
I really don't understand what you want here. Perhaps you could include the roxygen comments for `actionButton` and describe what you want to be inherited.

**Comment by privefl** [comment]
Say you want to document this function:
```
#' Title
#'
#' @inheritDotParams glue::glue
#'
#' @return
#' @export
#'
#' @examples
system_glue <- function(...) {
  system(glue::glue(...))
}
```

The "dots argument" (of `glue::glue()`) doesn't appear in the documentation of `system_glue()`:

![doc-no-dots](https://user-images.githubusercontent.com/11161036/38390675-49c5475a-3922-11e8-939b-1e00be9d7d68.png)

**Comment by pnacht** [comment]
I've recently bumped into this issue myself.

Let's say I have two functions:
- `foo` is a function which accepts dots:

```r
#' @param a a letter
#' @param b another letter
#' @param ... some dots
foo <- function(a, b, ...) {
  # do stuff
}
```
 
- `bar` is a function which calls `foo`:

```r
#' @inheritParams foo
bar <- function(...) {
  foo(...)
}
```

In this case, I'd expect the documentation of `bar`'s dots argument to be "Arguments passed on to `foo`" followed by three items: `a`, `b`, and `...`. However, I only get `a` and `b`, losing `foo`'s definition of its own `...` argument:

![image](https://user-images.githubusercontent.com/15221358/132241050-97791fde-adc6-4710-8177-087bbede76c4.png)

**Comment by d-morrison** [comment]
I've been running into this issue as well; I agree with @pearsonca's suggestion. @hadley, would it be reasonable to reopen this issue based on the further discussion?

**Comment by hadley** [comment]
@d-morrison after an issue has been closed for 2+ years, I'd recommend that you open a new issue with a clear description of the problem.
