### ISSUE TITLE
Line endings not configurable

### ISSUE THREAD

**Issue by Jakob2014uafmx** [klutometis/roxygen#636]
Roxygen always seems to use the platform's native line endings for generating Rd files and the NAMESPACE file. A configuration option would be nice, e.g. if you are on Windows, but you want Unix line endings (the RStudio line ending conversion option is not picked up).

**Comment by jsta** [comment]
Setting `.gitattributes` seems to make no difference.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
