### ISSUE TITLE
don't underline parentheses for function links

### ISSUE THREAD

**Issue by kevinushey** [klutometis/roxygen#638]
```R
roc_proc_text(rd_roclet(), "
  #' Title
  #' [yaml.load()]
  #' @md
  foo <- function() {}")[[1]]
```

produces

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in RtmpFNNTUI/file1406342905b5
\name{foo}
\alias{foo}
\title{Title
\code{\link[=yaml.load]{yaml.load()}}}
\usage{
foo()
}
\description{
Title \code{\link[=yaml.load]{yaml.load()}}
}
```

It might be preferable to generate `\code{\link[=yaml.load]{yaml.load}()}` -- that is, without the parentheses underlined.

Compare:

![screen shot 2017-07-12 at 1 41 28 pm](https://user-images.githubusercontent.com/1976582/28139116-ec93a2da-6707-11e7-9a7c-551b59b779ff.png)

![screen shot 2017-07-12 at 1 42 52 pm](https://user-images.githubusercontent.com/1976582/28139147-09777df4-6708-11e7-8e55-56de81c08794.png)

**Comment by gaborcsardi** [comment]
I don't have strong feelings either way.

**Comment by hadley** [comment]
I have a slight preference for not linking parens

**Comment by hadley** [comment]
But it looks like implementing this will be non-trivial, and this issue is 26, so if I just close it right now I'll be down to a single pages of issues.....

(If anyone really cares, I'd be happy to review a PR to `parse_link()`)
