### ISSUE TITLE
allow 'inheritParams' + 'noRd' to work together

### ISSUE THREAD

**Issue by kevinushey** [klutometis/roxygen#641]
Sometimes it's useful to have functions inherit documentation from a Roxygen block that itself shouldn't be written to a `.Rd` file, e.g.

```R
#' @param x A parameter.
#' @name docs
#' @noRd
NULL

#' @inheritParams docs
foo <- function(...) { ... }
```

Unfortunately, this doesn't work as `@noRd` completely wipes out the documentation object, so that `@inheritParams` now fails.

**Comment by hadley** [comment]
I _think_ this is just a matter of moving the `needs_doc()` check from `block_to_rd()` to `roclet_output.roclet_rd()`.

Although thinking about it more, that's going to cause problems if a mix of doc and no-doc end up written to the same file.  Hmmmmm.

**Comment by kevinushey** [comment]
A sneaky way of making this work would be to just allow this to work without a warning:

```
#' @param x A parameter.
#' @name docs
NULL

#' @inheritParams docs
foo <- function(...) { ... }
```

**Comment by hadley** [comment]
Oooh, maybe I could just make a `silentRd` or something tag?

**Comment by hadley** [comment]
I can't make that example silent because it would conceal other problems

**Comment by hadley** [comment]
Maybe `@virtualRd`?

**Comment by kevinushey** [comment]
I like that!

**Comment by hadley** [comment]
Now think that is probably best subsumed by #645
