### ISSUE TITLE
nicer way of building re-exports documentation?

### ISSUE THREAD

**Issue by kevinushey** [klutometis/roxygen#643]
When I call `?"%>%"`, I see this:

<img width="652" alt="screen shot 2017-07-27 at 3 39 08 pm" src="https://user-images.githubusercontent.com/1976582/28695066-da09b93e-72e1-11e7-91a3-6511cf30f498.png">

It's a little annoying that suddenly there's a separate help topic for each package that re-exports the pipe operator. Is there any way around this?

**Comment by hadley** [comment]
I don't think so - you have to list it as an alias to avoid the R CMD check note. If you can figure out a way around it, I'd be happy to implement, but I don't think it exists.
