### ISSUE TITLE
Allow comments inside roxygen code

### ISSUE THREAD

**Issue by richierocks** [klutometis/roxygen#648]
I'd like to be able to have roxygen content that doesn't end up in the resulting Rd file. That is, a roxygen comment. (I know that roxygen already supports R comments in, e.g., the `examples` tag.)

My use case is for teaching people how to use roxygen, though it may be more widely useful for meta-documentation.

C-style comments are one option.

```r
#' /* Write the title */
#' ___
#' 
#' /* Write a description of the function */
#' ___
#' /* Add a parameter tag */
#' ___
#' /* Add a return tag */
#' ___
hypotenuse <- function(x, y) {
  x ^ 2 + y ^ 2
}
```

Full line comments starting hash + another character are another option.

```r
#% Write the title
#' ___
#' 
#% Write a description of the function
#' ___
#% Add a parameter tag
#' ___
#% Add a return tag
#' ___
hypotenuse <- function(x, y) {
  x ^ 2 + y ^ 2
}
```

I'd like to know if this sounds like a useful feature to anyone else, and if anyone has any opinions on the best syntax.

cc: @sumedh10 @machow @aimeegott

**Comment by gaborcsardi** [comment]
You can put regular comment line in the middle of the roxygen chunks, these are ignored by roxygen AFAICT. E.g.

```r
#' Title
#' 
## comment
#'
#' @param arg1 blah blah
#'
## comment
#' @param arg2 bahbah bah
#'
#' @export
```

**Comment by richierocks** [comment]
@gaborcsardi Wow, I had no idea. Thanks.
