### ISSUE TITLE
Session crash when using roxygen2::roxygenise from devtools::release

### ISSUE THREAD

**Issue by privefl** [klutometis/roxygen#658]
I'm trying to release [my package](https://github.com/privefl/bigstatsr) to CRAN.
So, I used `devtools::release()` which made my session crash. 
So, I debugged a little going down to  release -> check -> document ->
Finally, it seems like it is `roxygen2::roxygenise(".", roclets = c("namespace", "rd"), load_code = devtools::ns_env)` which makes my session crash.

I'm on CentOS 7 (Linux) with R 3.3.3 (also tested with R 3.4.0).
I tried with both the latest CRAN versions of devtools and roxygen2 and then with both the latest development versions.

**Comment by hadley** [comment]
Have you run your code under valgrind? Given that your package uses C++ code, the most likely explanation is that you have a memory leak or otherwise incorrect allocation,

**Comment by privefl** [comment]
OK. But why I have this issue when using ``devtools::release()`` but not when testing my package locally or on Travis / on Appveyor / with Win-builder?

How can I use valgrind? I know what it is but never used it.

**Comment by hadley** [comment]
Because memory errors occur fairly randomly.  To start with, you might try just running in a debugger so you can at least see exactly where the error occurs (http://r-pkgs.had.co.nz/src.html#src-debugging)
