### ISSUE TITLE
Default @format is not overwritten when using a dummy documentation file

### ISSUE THREAD

**Issue by rabutler** [klutometis/roxygen#663]
When using a dummy documentation file to document two (or one) data sets, the default `@format` is not overwritten. However, when documenting the data from within data.R file, `@format` will overwrite the default. 

I encountered the issue when trying to combine documentation for multiple data sets into one file, but it appears the issue is more with the dummy file. 

**The following works, i.e., the default `@format` is overwritten:**
*data.R:*
```
#' Test data with shared description in this file
#'
#' Longer description for \code{t1} and \code{t2}
#'
#' @format Something besides the default format

"t1"

#' @rdname t1
"t2"
```

**While the following does not work, i.e., the default `@format` is not overwritten.** It results in format: An object of class `data.frame` with 10 rows and 2 columns.
*data.R:*
```
#' @rdname sharedDoc
"t3"

#' @rdname sharedDoc
"t4"
```
------
*doc.R:*
```
#' Test data with NULL documented
#'
#' Longer description for \code{t3} and \code{t4}
#'
#' @format A different format description that won't show up.
#' @name sharedDoc
NULL
```

The above continue to work/not work, even if only documenting one data set in each file.

If it helps at all, the minimum code is included in a skeleton package at https://github.com/rabutler/testBug

**Comment by rabutler** [comment]
The default format tag is not overwritten due to the order that the files are processed. Because data.R is processed before doc.R, then any existing tags from data.R are not overwritten by `topics$add(rd)` because the sharedDoc filename already exists. 

Changing the filename to a_doc.R causes it to be processed first, so the format tag from that file is used. 

Is this the expected behaviour/process or should I work on a solution?

As a side note, this does not seem to affect anything except for datasets that are documented from a dummy file.

**Comment by hadley** [comment]
It's expected behaviour

**Comment by rabutler** [comment]
Got it, thanks @hadley. I'll close the issue.
