### ISSUE TITLE
@export functions with traditional.style.longer.than.two.words.r.names

### ISSUE THREAD

**Issue by BillWeld** [klutometis/roxygen#665]
roxygen2 tags them with "S3method(...)" in the NAMESPACE file and they don't get exported.  Must I adopt a new naming convention to use roxygen?

**Comment by gaborcsardi** [comment]
Can you pls include an example?

**Comment by BillWeld** [comment]
Very strange.  The first and last functions here have the problem and the other two do not.

#' @export
log.memory.usage <- function()
{
    a <- 1 + 2
}

#' @export
traditional.style.longer.than.two.words.r.names <- function (x) x

#' @export
traditional.style.longer <- function (x) x

#' @export
log.memory.usage2 <- function()
{
    a <- 1 + 2
}

**Comment by hadley** [comment]
Probably because log is an S3 generic. Naming your functions like they are S3 methods when they aren't is a bad idea.

**Comment by BillWeld** [comment]
That would be it.  Thanks.

**Comment by gaborcsardi** [comment]
@BillWeld It is best to avoid dots in function names, because even if you carefully choose the name, you never know what S3 generics will be added in the future.

**Comment by BillWeld** [comment]
Sound advice, I’m sure.  Annoying but sound.  Thanks!
