### ISSUE TITLE
CRAN incompatible Rd files generated by S4 methods for classes with non-syntactic names.

### ISSUE THREAD

**Issue by ctbrown** [klutometis/roxygen#667]
I know the title of this issue is a bit of a word salad, but bear with me on this... For example:

```
#' @rdname is.one.sided
#' @aliases is.one.sided,<--method
setMethod( 'is.one.sided', '<-', .is.one.sided )
```

Generates Rd files that are (at present) rejected by CRAN.  This is unlikely to change in the near future.
Kurt Hornik writes regarding the formula.tools package:

> 
> Thanks.  I see that this got auto-rejected, base on
> 
> * checking for code/documentation mismatches ... WARNING
> Functions or methods with usage in documentation object 'formula.parts' but not in code:
>   \S4method{lhs}{<-} \S4method{op}{<-} \S4method{rhs}{<-}
> 
> so I took a closer look.
> 
> The code for processing Rd S3/S4 method markup assumes that the names of
> the classes involved are syntactic names.  In your case, <- is not, and
> using
> 
>   \S4method{is.one.sided}{<-}
> 
> would not parse, which I guess is why you use
> 
>   \S4method{is.one.sided}{`<-`}
> 
> in your Rd file.  But this is not recognized as S4 method markup and
> hence not processed accordingly, hence the mismatch.
> 
> One could try to extend the markup processing to handle not syntactic
> names quoted by backticks, but we've had no need for this in many years,
> so I'd rather avoid the effort if possible.  Now, R-exts says
> 
>   If it is necessary or desired to provide an explicit function
>   declaration (in a '\usage' section) for an S4 method (e.g., if it has
>   "surprising arguments" to be mentioned explicitly), one can use the
>   special markup
> 
>      \S4method{GENERIC}{SIGNATURE_LIST}(ARGUMENT_LIST)
> 
> Afaics, your methods have not surprising arguments, so perhaps you could
> simply not provide \S4method entries and instead say in text which
> classes you provide the methods for?
> 
> Best

The solution is to omit usage entries for non-syntactic names.

**Comment by hadley** [comment]
I don't think there's much that roxygen2 can do here - you can suppress the automatically generated usage statements with `@usage NULL`
