### ISSUE TITLE
Problematic string interpreted as roxygen comment

### ISSUE THREAD

**Issue by jennybc** [klutometis/roxygen#668]
I wanted to define a string constant in a package. The string happens to look like a roxygen comment and prevents `document()` from working. In real life, the string is yaml frontmatter for the reprex `.R` template.

Minimal reprex. In any functioning package that uses markdown syntax and where `document()` currently works, insert this into any `.R` file:

``` r
foo <- "
#' ---
"
```

and you get this when you run `document()`:

```
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating roxygen2 documentation
Loading roxygen2
Error in markdown_rparse(markdown_tags[[xml_name(xml)]](xml), markdown_tags = markdown_tags) : 
  attempt to apply non-function
Calls: suppressPackageStartupMessages ... markdown_rparse -> paste -> vapply -> FUN -> markdown_rparse
Execution halted
```

It appears to be extremely specific to the presence of this exact line: `#' ---`, i.e. you need at least 3 `-`s.

**Comment by jennybc** [comment]
A bit more. In any functioning package that uses markdown syntax and where `document()` currently works, insert this into any `.R` file:

``` r
foo <- "
#' blah
"
```

and it will cause the creation of `man/foo.Rd` with contents:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/reprex.R
\docType{data}
\name{foo}
\alias{foo}
\title{blah}
\format{An object of class \code{character} of length 1.}
\usage{
foo
}
\description{
blah
}
\keyword{datasets}
```

If I precede any of the above with `#' @noMd`, it prevents the error re: `#' ---` and the creation of unnecessary `.Rd` files, but generates warnings like:

```
Warning: @noMd [whisker.R#35]: has no parameters
```

**Comment by hadley** [comment]
Fixing this in roxygen2 would be a _lot_ of work. Maybe you can work around by either `paste()`ing strings together or using `\n`?

**Comment by jennybc** [comment]
Yes I decided to insert the leading `#'`s after the fact.

**Comment by nielsaka** [comment]
For future reference, the same error message shows up when there is a line starting with
```
#' # 
```
somewhere in the (roxygen) code. A quick `grep -r "#'\s*#\s"` will pin down the culprit.
