### ISSUE TITLE
Documenting S4 methods

### ISSUE THREAD

**Issue by spluque** [klutometis/roxygen#674]
I'm only learning roxygen, and I'm contemplating migrating some of my packages to this style documentation, as I'd like to keep docs next to code.  However, I'm getting stuck deciding where to document S4 generics and methods.

The typical structure is as follows for a silly example package "junk" for illustration purposes:

```shell
$ tree junk
junk
|-- DESCRIPTION
`-- R
    |-- AllGenerics.R
    |-- AllMethod.R
    `-- plotFoo.R
$ cat junk/R/AllGenerics.R
##' Methods for plotting
##'
##' @name plotFoo-methods
if (!isGeneric("plotFoo")) {
    setGeneric("plotFoo",
               function(x, y, ...) standardGeneric("plotFoo"))
}
$ cat junk/R/AllMethod.R
setMethod("plotFoo", signature(x="numeric", y="numeric"),
          function(x, y, time.lim=seq(0, 1, by=0.1),
                   depth.lim=seq(10), ...) {
              .plotFoo(time=x, depth=y, time.lim=time.lim,
                       depth.lim=depth.lim, ...)
          })

setMethod("plotFoo", signature(x="numeric", y="missing"),
          function(x, y, depth.lim, ...) {
              .plotFoo(time=x, depth=rev(x), depth.lim=depth.lim, ...)
          })
$ cat junk/R/plotFoo.R
###_ + Internal Function

".plotFoo" <- function(time, depth, time.lim=NULL, depth.lim=NULL, ...)
{
    plot(depth ~ time, xlim=time.lim, ylim=depth.lim, ...)
}
```

Of course, the real AllGenerics.R and AllMethod.R contain many more generics and methods, and there are several other files like plotFoo.R with other functions.  As implied, I'd like to show all plotFoo methods in a plotFoo-methods.Rd file.  The challenge is that the methods only handle some arguments before passing the correct arguments onto an internal function, so it's unclear where and how one documents all arguments?  Any tips welcome.

**Comment by hadley** [comment]
It's basically up to - roxygen2 doesn't impose any structure. Unfortunately I don't use S4 that much so I can't offer much help, but maybe try asking in http://community.rstudio.com/?
