### ISSUE TITLE
Markdown link text line wrapping removes whitespace

### ISSUE THREAD

**Issue by mixtrak** [klutometis/roxygen#675]
Using the Markdown tag (`@md`) on a Roxygen block works as expected for links in the `[link text](link.url)` markup, except where `[link text]` breaks across lines due to text wrapping. In this case, whitespace at the end or beginning of lines is stripped and words are concatenated. So for example the following Roxygen block:

```
#'  Personal R packages are not an original idea of mine; I think I first heard
#'  about them on [Hilary Parker's 
#'   blog](https://hilaryparker.com/2013/04/03/personal-r-packages/), though
```

Produces a link of the format [Hilary Parker'sblog](https://hilaryparker.com/2013/04/03/personal-r-packages/). Note that this example contains both trailing and leading whitespace and both are stripped.

The current workaround is not to wrap the `[link text]`, so that:

```
#'  Personal R packages are not an original idea of mine; I think I first heard
#'  about them on [Hilary Parker's blog](https://hilaryparker.com/2013/04/03/personal-r-packages/),
#'  though
```

Works as desired/expected.

**Comment by jennybc** [comment]
This was fixed in #630.
