### ISSUE TITLE
How to export Rcpp function with roxygen2?

### ISSUE THREAD

**Issue by yannickspill** [klutometis/roxygen#676]
I have some Rcpp functions, wrapped in an Rcpp module, which can be accessed from inside the package by prefixing with `pkg_name:::`. I added roxygen2 comments as suggested [here](https://github.com/RcppCore/Rcpp/issues/617) by creating an R file containing the markup around NULL. However, the @export statement does not work, and the functions are neither exported, nor do their documentation show. The Rcpp team told me to ask you here. Any ideas? Thanks...

**Comment by hadley** [comment]
See here http://r-pkgs.had.co.nz/src.html#cpp
