### ISSUE TITLE
Markdown code uses html escapes for < and >

### ISSUE THREAD

**Issue by hadley** [klutometis/roxygen#678]
e.g. `git@github<USENAME>`

**Comment by jennybc** [comment]
Should the fix perhaps only apply inside backticks? Maybe the actual point is that backticks should be respected as truly meaning "verbatim".

**Comment by hadley** [comment]
I don't think there's any case where we should be transforming `<>` to html escapes for Rd

**Comment by jennybc** [comment]
be3ef309381923e64337c3324510746990fde62f seems to have fixed all my known problems with this. If others agree, I think this is resolved.
