### ISSUE TITLE
roxygenise does not parse correctly \Sexpr with options

### ISSUE THREAD

**Issue by gvegayon** [klutometis/roxygen#682]
After trying to set up one of my packages with `Roxygen: list(markdown = TRUE)`, I realized that roxygenise was not parsing correctly some bit in which I use `\Sexpr` with options, namely `\Sexpr[results=text]{}`. I thought it had to do with me making a somewhat complex call, but it turns out that it fails with even the simplest example `\Sexpr[results=text]{1+1}`.

I've prepared an example with a package with no functions but only manuals here: [this doc chunck](https://github.com/gvegayon/roxygentest/blob/master/R/code.r#L6-L8) 

```r
#' This doesn't work \Sexpr[results=text]{1+1}
#'
#' But this does! \Sexpr{1+1}
```

mapping to [this Rd file](https://github.com/gvegayon/roxygentest/blob/master/man/md.Rd#L11-L13)

```tex
This doesn't work \Sexpr\link{results=text}{1+1}
But this does! \Sexpr{1+1}
```

**Comment by WastlM** [comment]
I just ran into the same issue. A workaround is to disable markdown parsing for that roxygen block via the `@noMd` tag.

**Comment by krlmlr** [comment]
...or add a second block with the same `@rdname` and define `@noMd` only in that block:

```r
#' Some function
#'
#' - docs require Markdown
fun <- function() {}

#' @name fun
#' @rdname fun
#' @noMd
#' \Sepxr[results=rd]{runif(1)}
NULL
```

Not sure if we really need `@name`.
