### ISSUE TITLE
Where @noMd/@md is placed matters

### ISSUE THREAD

**Issue by gvegayon** [klutometis/roxygen#683]
Testing out the `@md` @noMd` tags I found out that the position of those matters. If I put the noMd tag in the middle of the doc chunck I get the following error

```r
Warning: @noMd [code.r#34]: has no parameters
```

And roxygenize chops the Rd file up to that point. You can see a reproducible example [here](https://github.com/gvegayon/roxygentest/blob/master/R/code.r#L27-L44)

**Comment by hadley** [comment]
That's how tags work - they take all text up until the next tag starts.

**Comment by gvegayon** [comment]
Now I see my mistake. :blush:, sorry!
