### ISSUE TITLE
Selectively exclude package-internal docblocks from output

### ISSUE THREAD

**Issue by agwells** [klutometis/roxygen#684]
Is there a way to mark some Roxygen docblocks "package-internal", and exclude them from the generated output?

To explain what I mean, this is a feature that's present in some similar `@tag` code documentation systems for other languages. For example, [JSDoc](http://usejsdoc.org/) for Javascript when rendering will exclude all docblocks marked with the `@private` tag, by default. A parameter allows you to change this behavior, so that you can generate developer documentation that includes all the internal methods.

As a recent newcomer to R, I'd assumed Roxygen did something similar, so I had been documenting all my functions, exported or not, using `#'` Roxygen docblocks. But then I noticed in the [tidyjson](https://github.com/jeremystan/tidyjson/issues/105) project the devs have done the same thing, and the result is that the end-user package helpfiles are made confusing by the presence of help docs for many functions the end-user is not meant to access.

I think under the current functionality, a workaround for this could be to use `@rdname` to move "internal" docblocks into a file named `internal.Rd`, and add that to `.Rbuildignore`, but I was wondering if I've missed a more obvious way to achieve this.

Cheers!

**Comment by colearendt** [comment]
@agwells I dug into this a little bit by looking at packages like [`dplyr`](https://github.com/tidyverse/dplyr).  The convention there seems to be to use `@keywords internal`, which hides the help from the package index!  

Confirmation [here](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html):

> Keywords are not very useful, except for @keywords internal. Using the internal keyword removes all functions in the associated .Rd file from the documentation index and disables some of their automated tests.

This is probably worth closing, as I believe this is the thrust of your request!

**Comment by hadley** [comment]
You can also use `@noRd` to suppress the creation of the Rd file altogether.
