### ISSUE TITLE
\dontrun - creates strange `## Not Run`  strings

### ISSUE THREAD

**Issue by xhudik** [klutometis/roxygen#690]
Hi, 
the code:
```
#' Print a string.
#'
#' @examples
#' \dontrun{
#' str_length(letters)
#'}
print_str <- function(str) {
  print(string)
}
```
`roxygenize()` will create correct md file, however,  `R CMD check .` will generate:
```
## Not run:
str_length(letters)
## End(Not run)
```
What `## Not run` and `## End(Not run)` means? I think, for not super experienced user, this is very confusing. Is there any reason to have these strings in

**Comment by gaborcsardi** [comment]
> roxygenize() will create correct md file

You mean Rd file?

> R CMD check . will generate:

The help viewer generates that, and there is nothing we can do about it. If you want to show code, without running it, then you can use something like this (with markdown notation):

```
#' @section Some examples:
#' ```
#' str_length(letters)
#' ```
```

**Comment by xhudik** [comment]
thanks for the fast reply!
1. "You mean Rd file?" - yes you are right, I meant Rd file
2. "The help viewer generates that, and there is nothing we can do about it" - hmmmmmm, 
what is "help viewer"? I think it was generated by the command `R CMD check .`. The pdf created by this command contains the strange strings. If it is not done by `roxygenise()`, where is it?

**Comment by gaborcsardi** [comment]
> what is "help viewer"?

The `help` function. Or `?`, which is the same. But you are actually right, if you mean the PDF file, `R CMD check` does generate a PDF file.

> If it is not done by roxygenise(), where is it?

In base R. This is the one that creates the PDF I believe:
https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/tools/R/Rd2latex.R#L238
and there are a bunch of others, in `Rd2txt.R`, `RD2HTML.R`, etc.

**Comment by xhudik** [comment]
Thank you Gabor. Now it makes sense to me! I'm closing the issue
