### ISSUE TITLE
Full stop for the name of documented objects?

### ISSUE THREAD

**Issue by kbenoit** [klutometis/roxygen#691]
In @hadley's ["Generating Rd files"](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html), it states:

> Each documentation block starts with some text. The first sentence becomes the title of the documentation. That’s what you see when you look at help(package = mypackage) and is shown at the top of each help file. It should fit on one line, be written in sentence case, **and end in a full stop.** 
(emphasis added)

But: 
a) most of @hadley's packages (such as **dplyr**) do not use the full stop (although **roxygen2** does)
b) IMHO the full stop looks bad (and is totally unnecessary)

Guidance?

**Comment by hadley** [comment]
Need to update the vignette - titles don't end in full stops.

**Comment by kbenoit** [comment]
I also prefer starting the title in lowercase but nearly all of the package examples I can find start in "sentence case". Happy to follow the convention however (e.g. https://github.com/kbenoit/quanteda/issues/1156).

**Comment by hadley** [comment]
There's more conventions at http://style.tidyverse.org/code-documentation.html#title-and-description

**Comment by kbenoit** [comment]
Thanks @hadley. I forked the Style guide to correct 5.5 about the "semi-colon" but it is already corrected in the source:

> `Use a colon before enumerations or bulleted lists.`

Looks like the bookdown site just needs to be re-built.
