### ISSUE TITLE
Alias not correctly constructed when using name tag while documenting S4 methods

### ISSUE THREAD

**Issue by JoFAM** [klutometis/roxygen#695]
If you document a method in its own file, the correct alias is not constructed. If you document multiple methods in the same file, only the first one does not have a correctly constructed alias.

In attachment a reproducible example. This is the only code file in the package:

```
#' some methods
#'
#' blabla yadeyade
#'
#' @param object a param
#'
#' @importFrom stats4 nobs
#' @export
#' @name nobs
#' @rdname nobs
setMethod("nobs",
          "matrix",
          function(object){
            object
          })

#' @rdname nobs
setMethod("nobs",
          "data.frame",
          function(object){
            object
          })
```

Running check on the package gives the following warnings:

```
checking for missing documentation entries ... WARNING
Undocumented S4 methods:
  generic 'nobs' and siglist 'matrix'

...

checking Rd \usage sections ... WARNING
Objects in \usage without \alias in documentation object 'nobs':
  '\S4method{nobs}{matrix}'

```

The method for `data.frame` is documented correctly, and is present in the same file. If I remove the tag `@name` , then the warnings disappear.

I realize that in this case the `@name` tag is redundant, but the behaviour illustrated here is not what I expect based on documentation in vignettes and http://r-pkgs.had.co.nz/man.html#man-classes

The zip folder with the example package:

[ReprocRoxygen.zip](https://github.com/klutometis/roxygen/files/1607751/ReprocRoxygen.zip)

**Comment by hadley** [comment]
That's because you're setting `@name`, which overrides the default alias.

With:

```R
#' Title
#' @importFrom stats4 nobs
#' @export
#' @rdname nobs
setMethod("nobs", "matrix", function(object){})

#' @rdname nobs
setMethod("nobs", "data.frame", function(object) {})
```

I see:

```
\docType{methods}
\name{nobs}
\alias{nobs}
\alias{nobs,data.frame-method}
\title{Title}
\usage{
\S4method{nobs}{matrix}(object)

\S4method{nobs}{data.frame}(object)
}
\description{
Title
}
```

**Comment by JoFAM** [comment]
That's indeed what I reported. 

For reference: if one needs a different `@name` and `@rdname`, the first method should have an explicit `@aliases` too. This works:

```
#' some methods
#'
#' blabla yadeyade
#'
#' @param object a param
#'
#' @importFrom stats4 nobs
#' @export
#' @name nobs
#' @rdname nobsPage
#' @aliases nobs,matrix-method
setMethod("nobs",
          "matrix",
          function(object){
            object
          })

#' @rdname nobsPage
setMethod("nobs",
          "data.frame",
          function(object){
            object
          })
```
