### ISSUE TITLE
PDF manual throws a warning when using long default options

### ISSUE THREAD

**Issue by pierreroudier** [klutometis/roxygen#698]
This is a sneaky one -- and possibly not much `roxygen2` can do about it. I get the following error on a `R CMD check --as-cran`:

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
```

Looking at `Rdlatex.log`, the culprit seems to be an overfull verbatim box:

```
Overfull \hbox (6.78088pt too wide) in paragraph at lines 66--66
 []  \T1/pcr/m/n/10 p = 0.5, nmax = NULL, thresh = 0.01, min_iter = 5, max_iter
 = 20,[] 

Overfull \hbox (24.78088pt too wide) in paragraph at lines 68--68
 []  \T1/pcr/m/n/10 tune_grid = .create_tune_grid(model = method, length = tune
_length),[] 
```

From the generated manual:

![dissever-bug](https://user-images.githubusercontent.com/515259/34925597-36a6c060-fa0f-11e7-9152-833ece3cc866.png)

**Comment by hadley** [comment]
Yeah, I don't think there's anything roxygen2 can do about that.
