### ISSUE TITLE
Duplicated fields (e.g. description, values) when manually labeling sections

### ISSUE THREAD

**Issue by ssdavenport** [klutometis/roxygen#701]
I would like to create a function documentation with a multi-paragraph "description" field. By default, roxygen2 will take only one paragraph, so I am using manual overrides to tag the sections in the .R file before building documentation.

My .R file looks something like below:

    #' @title
    #' Title goes here
    #'
    #' @description
    #' This is my description
    #' 
    #' @details
    #' Details go here

Upon building the documentation, certain sections are duplicated in the .Rd. The description appears twice, as do details and usage. I know I can manually edit the .Rd to remove the duplicates but that is time-intensive and seems wrong.

Note that if I remove "@description" and "@details" tags, the problem is resolved (except the description is forced to one paragraph).

Is there some way to either stop the .R file from creating duplicated fields in the .Rd, while also allowing for a multi-paragraph description field?

**Comment by ssdavenport** [comment]
UPDATE:

I've found a work around: deleting the .Rda and re-building it from roxygen (with devtools::document()). Rebuilding the documentation without deleting the .Rda is what was causing the duplicated text -- which incidentally was not entirely duplicated but rather left-over versions of earlier text from previous .Rda builds.

But perhaps this still warrants a bug fix so this work-around is not needed.

**Comment by davidbody** [comment]
I took a look at this during the TidyVerse developer day and wasn't able to reproduce it. Perhaps it's already been fixed?

**Comment by davidbody** [comment]
I should clarify that I tried something like

```
#' @title
#' Title goes here
#'
#' @description
#' This is my description
#'
#' This is the second paragraph
#' 
#' @details
#' Details go here
```
and .Rd file appeared to render correctly using `devtools::document()`.

**Comment by hadley** [comment]
Thanks @davidbody!

**Comment by gwd666** [comment]
> UPDATE:
> 
> I've found a work around: deleting the .Rda and re-building it from roxygen (with devtools::document()). Rebuilding the documentation without deleting the .Rda is what was causing the duplicated text -- which incidentally was not entirely duplicated but rather left-over versions of earlier text from previous .Rda builds.
> 
> But perhaps this still warrants a bug fix so this work-around is not needed.

I am having the same issue - and I am under the imporession that the .rda file I have in /data coudl be the cause. What exactly is meant by "re-building the .Rda from roxygen (with devtools::document())"?
