### ISSUE TITLE
Maintain interface compatibility for roclet_process() and perhaps other generics

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#713]
`roclet_process()` is exported, and existing code uses it: https://github.com/search?q=roclet_process&type=Code&utf8=%E2%9C%93.

Because `roclet_process()` doesn't have `...` in their arguments, and because *roxygen2* calls it with anonymous arguments, it seems to be very difficult to write methods that work with both 6.0.1 and current dev versions. My own use case is the [pkgapi roclet](https://github.com/r-lib/pkgapi/blob/1cdc63ac11282a2dd35069471c63b28a58e2e1c2/R/roclet.R#L17), I don't even care about arguments other than `base_path`.

CC @klmr @renozao.

**Comment by hadley** [comment]
Given that the method now has different arguments, I don't see anyway around the problem apart from switch on `packageVersion()`. Is that a problem?

**Comment by krlmlr** [comment]
So the methods that implement this generic are supposed to switch? Can we be sure that this generic is called only by _roxygen2_?

I can think of a pattern like

```r
roclet_process.frob <- function(...) {
  if (packageVersion("roxygen2") < "6.0.1") {
    roclet_process_frob_legacy(...)
  } else {
    roclet_process_frob(...)
  }
}
```

with different interfaces for the `roclet_process_frob*()` functions -- if there's nothing _roxygen2_ can do about it.

**Comment by hadley** [comment]
The change doesn't break any revdeps, so I think it's only you and @klmr who need to make changes.

**Comment by krlmlr** [comment]
Thanks, fixed for myself by specifying minimum version in _pkgapi_.
