### ISSUE TITLE
\code{\link{function_name()}} not working

### ISSUE THREAD

**Issue by teo029** [klutometis/roxygen#715]
`\code{\link{foo}}` works, while adding parentheses will make it not find the link:

`\code{\link{foo()}}`

The [Code Documentation](http://style.tidyverse.org/code-documentation.html#code-font) tells us to add those parentheses.

**Comment by gaborcsardi** [comment]
Yeah, you can add the parens in markdown mode, but not in `\code{\link{...}}`. Roxygen converts `[foo()]` to `\code{\link[=foo]{foo()}}`. This is how to write the equivalent link in plain Rd notation.
