### ISSUE TITLE
markdown link doesn't check if the link really exist

### ISSUE THREAD

**Issue by xhdong-umd** [klutometis/roxygen#717]
When I referenced to some other functions in my package with `[other_fun]` syntax, but renamed the `other_fun` name later, the link created no longer works.

It's common that some function names are changed in refactoring, then it's quite difficult to find all the old references manually. I didn't notice the problem until a package installation procedure checked missing links in html (I don't know exactly when it will happen).

Should we check the link really exist in building the documentation, especially for the internal links?

**Comment by gaborcsardi** [comment]
`R CMD check` checks for this.
