### ISSUE TITLE
Escaping `[`, `]` character outside of code blocks is buggy in markdown mode

### ISSUE THREAD

**Issue by mb706** [klutometis/roxygen#720]
Trying to escape `[` characters outside of code blocks generates broken `.Rd` files.

Examples (in the description block, but the bug occurs in other blocks as well):
```{r}
#' \[ test \] description
```
generates
```
\description{
[ test ] description

[ test ]: R:%20test%20%5C
}
```

A way around this is currently to only escape the beginning `[` character:
```{r}
#' \[ test ] description
```
to get
```
\description{
[ test ] description
}
```
However, I have not found a way to put a link between escaped brackets (without resorting to `\link`):
```{r}
#' \[ [test] ] description
```
gives (also when escaping both outer `[` and `]`):
```
\description{
[ [test] ] description

[ [test]: R:%20[test
}
```

**Comment by gaborcsardi** [comment]
Reproducible example:
```
roc <- rd_roclet()
out1 <- roc_proc_text(roc, "
  #' Title
  #'
  #' \\[ test \\] description
  #' @md
  foo <- function() {}")[[1]]
```
