### ISSUE TITLE
NAMESPACE written twice AND when should not be written

### ISSUE THREAD

**Issue by stufield** [klutometis/roxygen#728]
Hi All,
I've just updated to the development version of roxygen2 (**6.0.1.9000**) and started noticing some 2 strange behaviors. Unsure why I can't seem to find anyone else with the same issues (which makes me think it might be just me ... d'oh!):

1. The NAMESPACE file is being written even when it's unnecessary (i.e. no changes made)
2. The NAMESPACE file is being written twice (it seems).

- This does **not** happen with roxygen2 **6.0.1**, just the dev version **6.0.1.9000**.
- The NAMESPACE file **is** correct when written (good)
- Issue occurs in both `vanilla` session and regular R startup session (probably not some weird environmental package conflict)
- Is this the expected behavior?

I created a very simple example with a package containing only 1 exported function and 1 dependency, so the NAMESPACE should be simple, containing only 2 lines, an `export()` and an `import()`.
I don't know how to generate a full `reprex` of the issue, so I just took a screenshot, showing that the behavior occurs in both `roxygen2::roxygenize` and `devtools::document` (**1.13.5.9000**), as you would expect since `document()` wraps around `roxygenize()`. In the example screenshot, no files were changed between calls.

Has anyone else noticed (or can reproduce) this? 

![namespacex2](https://user-images.githubusercontent.com/25203086/38421426-5254abee-3964-11e8-9a60-f7255fc4ea04.png)

```
─ Session info ──────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Ubuntu 16.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US                       
 collate  en_US.UTF-8                 
 tz       America/Denver              
 date     2018-04-06   
```

**Comment by hadley** [comment]
Yes, see the news.
