### ISSUE TITLE
WISH: Support Markdown [pkg::fcn(x = 42)] like [pkg::fcn()] is supported

### ISSUE THREAD

**Issue by HenrikBengtsson** [klutometis/roxygen#733]
For Roxygen2 w/ Markdown, we have that:

* `[pkg::fcn()]` becomes `\code{\link[pkg:fcn]{pkg::fcn()}}`

It would be handy if the following would also be supported:

* `[pkg::fcn(x = 42, y = pi)]` becomes `\code{\link[pkg:fcn]{pkg::fcn(x = 42, y = pi)}}`

**Comment by hadley** [comment]
Given the existing complexity of the regexp based link parser, I'm going say that this is probably never going to happen. I don't think we can make the regexp any more complicated, so implemented it would require a custom parser, and the cost-benefit ratio means that it's unlikely we'll ever implement.
