### ISSUE TITLE
S3 methods for S4 classes not properly documented

### ISSUE THREAD

**Issue by JoFAM** [klutometis/roxygen#741]
Per the [methods manual](https://stat.ethz.ch/R-manual/R-devel/library/methods/html/Methods_for_S3.html) , the following construct should be used when creating S3 methods for S4 classes. This is eg needed when having a model framework in S4, but one needs to provide predict(), fitted(), coef() , ... methods.

```
setClass("uncased", contains = "character")
unique.uncased <- function(x, incomparables = FALSE, ...) nextMethod(tolower(x))
setMethod("unique", "uncased", unique.uncased)
```
And the namespace should contain

```
S3method(unique, uncased)
exportMethods(unique)
```

When I try the following : 
```
#' @rdname unique
#' @export
unique.uncased <- function(x, incomparables = FALSE, ...) nextMethod(tolower(x))
#' @rdname unique
#' @export
setMethod("unique", "uncased", unique.uncased)
```
Then : 
- in the namespace `export(predict.tskrr)` is added.
- R CMD check gives a note about a possible S3 method being refered to in the manual with its full name.

> S3 methods shown with full name in documentation object 'unique':
>   'unique.uncased'
> The \usage entries for S3 methods should use the \method markup and not their full name.

If I use the (deprecated) tag `@S3method` instead, I have the correct entry in the namespace but still the same note in R CMD check.

**Comment by hadley** [comment]
This is a case where you should use `@method`.

**Comment by JoFAM** [comment]
Checked it, and `@method` doesn't do anything for the NAMESPACE. I need 

    S3method(unique, uncased)

in the NAMESPACE file instead of `export(unique.uncased)` as I get now. `@method` only adds the correct entry in the Rd file, not in the NAMESPACE file.

**Comment by hadley** [comment]
`@method` tells roxygen that it's a method, `@export` will then export it correctly.

**Comment by JoFAM** [comment]
Ah, so I need both tags together. Tried it, seems to work. Thx.
