### ISSUE TITLE
Issue with %in% in roxygen comment

### ISSUE THREAD

**Issue by ebridge2** [klutometis/roxygen#742]
Hi,

I have the following roxygen comment:

```
#' @param community.attribute the attribute of the graph vertices denoting the vertex communities. Should be that \code{community.attribute %in% names(vertex.attributes(g))}.
```

that throws the roxygen warning:

```
Warning: @param <file#linenumber>: mismatched braces or quotes
```

when I delete the `%in%` the warning goes away. Is this desired behavior?

**Comment by hadley** [comment]
You need to escape `%` because it's the Rd commenting character.  Alternatively, if you use markdown formatting (and the development version), roxygen2 will escape for you: 

```R
#' @param community.attribute the attribute of the graph
#'   vertices denoting the vertex communities. Should be that 
#'   `community.attribute %in% names(vertex.attributes(g))`.
```
