### ISSUE TITLE
unitTests

### ISSUE THREAD

**Issue by saralinker** [klutometis/roxygen#743]
Hi, 

I am running roxygen2::roxygenize() within a directory of a package I am created and receive the following warning:

RUNIT TEST PROTOCOL -- Tue May 29 08:36:52 2018 
*********************************************** 
Number of test functions: 1 
Number of errors: 1 
Number of failures: 0 

 
1 Test Suite : 
brainImageR RUnit Tests - 1 test function, 1 error, 0 failures
ERROR in test_predict_time: Error in brainImageR::predict_time(dat) : 

Test files with failing tests

   test_predict_time.R 
     test_predict_time 

The problem is that I have completely DELETED the function test_predict_time() from my computer and I still get this error. I have even tried deleting the R script that runs the BiocGenerics:::testPackage("brainImageR") function as well as the entire /tests folder, but this is all to no avail, I still I get this error. 

I should also note that after these deletions I have updated my git page, neither the git page nor my computer has these files stored on it, but I still get this error. 

I have also tried creating a new file called "test_predict_time", storing it in the appropriate place, but having it run a benign function that's sure to work. But....of course since I'm posting this issue, this also did not work. 

It seems as though there must be a hidden file somewhere storing this information, but I can't seem to find it. I'm attaching a file that shows my complete working directory including hidden files. Any help would be very much appreciated. 

[directoryfiles.txt](https://github.com/klutometis/roxygen/files/2049037/directoryfiles.txt)

EDIT: I'm not sure why this helped, but I tried running devtools::document(). After running this roxygen2::roxygenize() worked. It would still be great to know what is going on here, but the issue has been partially solved.

**Comment by hadley** [comment]
You appear to be running RUnit, not roxygen.
