### ISSUE TITLE
Petition CRAN to allow man-roxygen/ directory?

### ISSUE THREAD

**Issue by krivit** [klutometis/roxygen#744]
`R CMD check --as-cran` flags the `man-roxygen` template directory, which means that it has to be `.Rbuildignore`ed in building submitted packages.

This seems suboptimal (and goes against the spirit of open source, IMO), since it means that one can't successfully run `roxygen` on a CRAN tarball.

Would it therefore be worthwhile to ask CRAN to white-list `man-roxygen`?

**Comment by hadley** [comment]
Unfortunately it would not be worthwhile.
