### ISSUE TITLE
GitHub version documents functions starting with dot

### ISSUE THREAD

**Issue by bwiernik** [klutometis/roxygen#747]
In the current GitHub version (6.0.1.9000, commit https://github.com/klutometis/roxygen/commit/be3ef309381923e64337c3324510746990fde62f), the `internal` is being ignored by `roxygenize` and `devtools::document`. .Rd files for `internal` functions are being created.

**Comment by gaborcsardi** [comment]
> is being ignored

I am not sure what you mean by this, but the internal keyword is handled by R, it leaves the manual  page out of the index. Roxygen does not treat internal pages any differently, AFAIK.

**Comment by bwiernik** [comment]
With the GitHub version of roxygen2, `roxygenize` or `document` creates .Rd files for functions with the internal keyword. In the version on CRAN, these functions ignore and don’t create Rd files for functions with this keyword.

**Comment by gaborcsardi** [comment]
It is not a bug. `@keywords internal` does not mean that no Rd file is created. It is a not for R itself, not to put the manual page in the index. AFAIR, roxygen2 has always created Rd files for internal pages. At least version 6.0.1  surely does for me, see below. If you don't want an Rd file, you can use `@noRd`.

```
~/works/processx master*
❯ grep -C 5 'keywords internal' R/initialize.R
#' @param echo_cmd Echo command before starting it?
#' @param supervise Should the process be supervised?
#' @param encoding Assumed stdout and stderr encoding.
#' @param post_process Post processing function.
#'
#' @keywords internal
#' @importFrom utils head tail

process_initialize <- function(self, private, command, args,
                               stdin, stdout, stderr, connections,
                               poll_connection, env, cleanup, wd, echo_cmd,

~/works/processx master*
❯ R -q -e  'packageVersion("roxygen2")'
> packageVersion("roxygen2")
[1] ‘6.0.1’
>

~/works/processx master*
❯ R -q -e  'devtools::document()'
> devtools::document()
Updating processx documentation
Loading processx
>

~/works/processx master*
❯ head   man/process_initialize.Rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/initialize.R
\name{process_initialize}
\alias{process_initialize}
\title{Start a process}
\usage{
process_initialize(self, private, command, args, stdin, stdout, stderr,
  connections, poll_connection, env, cleanup, wd, echo_cmd, supervise,
  windows_verbatim_args, windows_hide_window, encoding, post_process)
}
```
