### ISSUE TITLE
particular function name makes R unresponsive

### ISSUE THREAD

**Issue by jkl789** [klutometis/roxygen#749]
I've been revising on a package and found that after changing a function name R became unresponsive after I enter document( ).  I have whittled things down to a minimal example, which I cut and pasted below my name.  In the example the function is called aux.stats. If I change the name of the function to reg.stats or auxStats, document() works just fine. Weird.

I'm operating with R 3.5.0 on Windows 7.

I hope that's enough information to be helpful.

Regards,  

Joe Ritter

#' A silly function.
#' @param decs the number of decimal places in the output
#' @export
aux.stats <- function(x, decs){
  round(x, decs)  
}

**Comment by hadley** [comment]
Unfortunately I can't reproduce the problem:

``` r
library(roxygen2)
roc_proc_text(rd_roclet(), "
#> Error: <text>:2:28: unexpected INCOMPLETE_STRING
#> 1: library(roxygen2)
#> 2: roc_proc_text(rd_roclet(), "
#>                               ^
```

A silly function.
@param decs the number of decimal places in the output
@export

``` r
aux.stats <- function(x, decs){
round(x, decs)
}
")
#> Error: <text>:4:1: unexpected INCOMPLETE_STRING
#> 3: }
#> 4: ")
#>    ^
```

Created on 2018-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
