### ISSUE TITLE
Templates in man-roxygen/ don't render markdown?

### ISSUE THREAD

**Issue by alexpghayes** [klutometis/roxygen#753]
I have enabled package-wide markdown documentation in my `DESCRIPTION`:

```
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.0.1.9000
```

but if I don't include an `md` tag in the template files in `man-roxygen`, the markdown isn't rendered. Is there a setting I can enable to avoid needing these tags? Markdown everywhere else renders normally.

**Comment by jayhesselberth** [comment]
Dup of https://github.com/klutometis/roxygen/issues/594

Looks like it was fixed there?

**Comment by alexpghayes** [comment]
https://github.com/alexpghayes/roxygen-reprex

**Comment by jayhesselberth** [comment]
I recommend running `usethis::use_roxygen_md()` and then following the prompt to run `roxygen2md`.

Doing so automatically adds `Roxygen: list(markdown = TRUE)` to your `DESCRIPTION`, which fixes your issue.

**Comment by alexpghayes** [comment]
That fixed it -- thanks for chasing this down! Will be more careful about `Roxygen: list(markdown = TRUE)` in the future.
