### ISSUE TITLE
Provision for arbitrary code in NAMESPACE

### ISSUE THREAD

**Issue by rvlenth** [klutometis/roxygen#759]
I need to conditionally import a generic from another package. So my `NAMESPACE` file needs to contain code like this:
```
if(requireNamespace("foo", quietly = TRUE) {
    importFrom(foo, bar)
    S3method(bar, bell)
}
```
The reason is that my package provides a courtesy `bar.bell()` method if the user happens to have the package **foo** installed; but if not, I don't want to register that method. 

Is it possible to do this and still use **roxygen2** to maintain my `NAMESPACE`? If not, could some feature that allows this be added?

Thanks

**Comment by gaborcsardi** [comment]
You can use the  `@rawNamespace` tag.

**Comment by rvlenth** [comment]
Thanks. This appears to be what is needed, but as far as I can tell, it is not documented anywhere. So I suggest adding documentation of this feature.
