### ISSUE TITLE
Is the requirement Encoding: UTF-8 at odds with WRE?

### ISSUE THREAD

**Issue by HughParsonage** [klutometis/roxygen#774]
I see since #649 the DESCRIPTION file must have Encoding: UTF-8. This seems sensible; however, I notice that in [*Writing R Extensions*](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Encoding-issues) it says:

> Do not specify an encoding unless one is actually needed: doing so makes the package less portable.

I'm reluctant to ignore warnings from roxygen2, but for my package the `Encoding` field is not "actually needed" and so I'm reluctant to add it. I don't know enough about encodings to suggest a fix.

**Comment by hadley** [comment]
Using Encoding: UTF-8 has not caused any problems for tidyverse packages.
