### ISSUE TITLE
no-build option for roxygenise?

### ISSUE THREAD

**Issue by spennihana** [klutometis/roxygen#776]
How do I get back the old behavior of roxygen that works on source files only without package building steps. Upgrading to the most recent of roxygen2 now attempts to do a package build which is undesirable.

Thanks

**Comment by eddelbuettel** [comment]
I asked for the same in #771 and have as soundly ignored as you.  

I resorted to keeping 6.0.1 in a local directory and use that instead.

**Comment by hadley** [comment]
Duplicate of #771
