### ISSUE TITLE
Error with a brand new project

### ISSUE THREAD

**Issue by MaksimRudnev** [klutometis/roxygen#779]
After updating roxygen2 to 6.1.0 it keeps showing the following error, even with the brand new projects set up by RStudio (1.1.456) defaults, i.e. containing a single hello.R file.

```
First time using roxygen2. Upgrading automatically...
Error in .f(.x[[i]], ...) : attempt to apply non-function
Calls: suppressPackageStartupMessages ... read_pkg_description -> read.description -> <Anonymous> -> .Call -> .f
Execution halted

Exited with status 1.
```

**Comment by rubak** [comment]
I had the same issue. Updating the `desc` package to version 1.2.0 fixed it for me.

**Comment by fawda123** [comment]
@rubak worked for as well

**Comment by MaksimRudnev** [comment]
Thanks, it fixed the problem. Update to roxygen 6.1.0.9 fixes it as well.

**Comment by abhijat-github** [comment]
> I had the same issue. Updating the `desc` package to version 1.2.0 fixed it for me.

Can you please explain how you updated the desc package. I am quite new to package building in R. Thank you.

**Comment by abhijat-github** [comment]
I get the following error when I try to build my package using Clean and Rebuild under Build Menu


_==> devtools::document(roclets = c('rd', 'collate', 'namespace', 'vignette'))

Updating qmR documentation
First time using roxygen2. Upgrading automatically...
Error in if (any(mismatch <- res != res2)) { : 
  missing value where TRUE/FALSE needed
Calls: suppressPackageStartupMessages ... idesc_create -> idesc_create_file -> idesc_create_text -> read_dcf
Execution halted

Exited with status 1._

**Comment by gaborcsardi** [comment]
> Can you please explain how you updated the desc package. I am quite new to package building in R. Thank you.

`install.packages("desc")`
