### ISSUE TITLE
Exporting `default_tags()` function

### ISSUE THREAD

**Issue by nteetor** [klutometis/roxygen#780]
It would be handy to be able to call `default_tags()` without `:::`. For example, I only want to modify how examples are processed and ideally I could do this,

```r
library(roxygen2)

default_registry <- default_tags()
default_registry$examples <- function(x) {
  tag_examples(x) # used to check for errors
  x               # return original value without extra newlines removed
}

parse_package("path/to/package")
```

Am I missing a way to do this currently? or is exporting `default_tags()` something we could discuss?

**Comment by hadley** [comment]
I don't think it's a good idea to redefine existing behaviour. Could you instead create a `@examples2` or similar?
