### ISSUE TITLE
"_PACKAGE" creates 2 help pages

### ISSUE THREAD

**Issue by mpascariu** [klutometis/roxygen#783]
When using `_PACKAGE` to document an R package, the function creates 2 help pages (or this is how it looks like), or two entries that takes us to the same help page. For example in `roxygen2` package we can see `roxygen2-package` on top of the list and `roxygen2` somewhere down the list (looking from RStudio).

In a large package this might not be a problem but in a small one that contains, say, 3 top level functions, having 2 identical help page with the package description seems superfluous.

I would like to keep only `roxygen2-package` and hide `roxygen2`.

**Comment by hadley** [comment]
There is only one help page, but it has two aliases, one available from (e.g.) `?roxygen2` and one from `package?roxygen2`. This is a standard documentation style.   If you don't want this, you can suppress the aliases (IIRC) with `@aliases NULL`.
