### ISSUE TITLE
Url containing %

### ISSUE THREAD

**Issue by shortyatz** [klutometis/roxygen#786]
I know this issue has been documented before mostly here: https://github.com/klutometis/roxygen/issues/407

But as of roxygen2 6.1.0 I am still receiving a mismatched quotes or brackets warning.

The line in question is: #'@source \url{https://finance.yahoo.com/quote/%5EDJI/}

Additionally, is there a way to suppress the warning.

**Comment by ha0ye** [comment]
Not sure if you've resolved this yet, but it's because `%` is the comment character in the .Rd format, and so it needs to be escaped.

**Comment by shortyatz** [comment]
I just skipped over this issue, as I haven’t heard back from CRAN since October of last year, when I submitted this package I probably don’t really care anymore.  Anyway, is there any documentation or link to point me to how to ‘escape’?

**Comment by ha0ye** [comment]
> I just skipped over this issue, as I haven’t heard back from CRAN since October of last year, when I submitted this package I probably don’t really care anymore. Anyway, is there any documentation or link to point me to how to ‘escape’?
> […](#)
> On Jul 18, 2019, at 3:08 PM, Hao Ye ***@***.***> wrote: ol

Try inserting a backslash or two before the `%` character.
