### ISSUE TITLE
This repo has no description

### ISSUE THREAD

**Issue by maelle** [klutometis/roxygen#795]
😺

**Comment by maelle** [comment]
I mean:

![image](https://user-images.githubusercontent.com/8360597/45737638-ab93c980-bbee-11e8-9112-6ad49c25380e.png)

**Comment by hadley** [comment]
Unfortunately I'm not the admin of the repo, and @klutometis hasn't responded to my requests to add.

**Comment by maelle** [comment]
👍 😭
