### ISSUE TITLE
Unknown inherit type: value

### ISSUE THREAD

**Issue by IndrajeetPatil** [klutometis/roxygen#797]
`roxygen2` vignette for inheriting documentation from other topics mentions that-

`@inherit source_function return details` will inherit selected components from `source_function()`.

Accordingly, I have the following in my package function:
```
#' @inherit stats::bartlett.test return value
```

Altough there is no problem creating documentation or with inheriting the documentation, when I do `devtools::document(roclets=c('rd', 'collate', 'namespace'))`, it produces the following warning:
```
Updating ggstatsplot documentation
Warning: @inherit [C:\Users\inp099\Documents\ggstatsplot\R\helpers_messages.R#20]: 
Unknown inherit type: value
```
So I was wondering about how I can get rid of this warning. Any thoughts?

**Comment by hadley** [comment]
Don't use `value`? I'm not sure what you're trying to achieve here.

**Comment by IndrajeetPatil** [comment]
I am inheriting the `value` section of `stats::bartlett.test`, which actually works just fine!
https://indrajeetpatil.github.io/ggstatsplot/reference/bartlett_message.html#value

![image](https://user-images.githubusercontent.com/11330453/47366630-1a5fb900-d6ac-11e8-9e5e-7fa5ca409d31.png)

Just wanted to mention that this raises a `warning`, and wasn't sure why.

**Comment by hadley** [comment]
That's because roxygen calls it the return section.
