### ISSUE TITLE
`roxygenize()` crashing RStudio Server

### ISSUE THREAD

**Issue by mjsteinbaugh** [klutometis/roxygen#801]
I'm running into an issue where calling `roxygenize()` inside a development package crashes RStudio Server. If I call the function directly from the R command line on the server, roxygen rebuilds the documentation as expected. I first noticed this running `devtools::document()` but can confirm that this happens consistently calling `roxygen2::roxygenize()` directly.

RStudio Server will crash when a package is loaded as a project or if the working directory is changed, and no project is loaded. So it's not a specific issue to having a project loaded.

I'm not sure how to debug this and pinpoint what the issue could be on my machine. Any advice?

Best,
Mike

**Comment by gaborcsardi** [comment]
@olsgaard Can you send  the output of `sessioninfo::session_info()` and also the output you get  at the crash, if any? If you are  using  RStudio, can you  pls try from the terminal?

**Comment by mjsteinbaugh** [comment]
@olsgaard My RStudio Server is installed on a Red Hat Linux VM. I updated the binaries on the image and then reinstalled the R package library from scratch. I think I may have run into a compilation issue with one of the dependency packages, due to R attempting to use some libraries inside my conda installation. If I can reproduce this issue with a new library, I'll post an update here.

**Comment by olsgaard** [comment]
Following @mjsteinbaugh theory, we tested building our documentation, linking to packages loaded from different historical snapshots of CRAN, and found that we can build documentation for our package using libraries from copies of CRAN *older* than 2nd of September. As there haven't been any new versions of Roxygen in CRAN after this date, I believe we might also have some compilation issues. Or less likely: there is a 3rd library that was updated in September, which interacts catastrophically with roxygen. 

@gaborcsardi 

We get no output when Roxygen crashes, just an ["R session Error" dialogue()](https://support.rstudio.com/hc/user_images/jlmmZLu1wLOtXndITjkDRg.png)

```R
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: OpenShift Enterprise

Matrix products: default
BLAS: /usr/lib64/R/3.4.3/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/3.4.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2 testthat_2.0.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  magrittr_1.5    R6_2.2.2        tools_3.4.3     withr_2.1.2     yaml_2.2.0      Rcpp_0.12.17    memoise_1.1.0  
 [9] digest_0.6.16   rlang_0.2.1     devtools_1.13.6 bindr_0.1.1
```

**Comment by mjsteinbaugh** [comment]
@olsgaard Anecdotally I think I'm seeing something similar here too. roxygen documentation was working fine for me on RStudio Server in August, and I've definitely been running into intermittent issues since then that I don't see when running R directly. I noticed this issue pop up on a different VM recently (Amazon AMI running Bioconductor 3.8). I'm trying to see if I can get some info on what may be happening. It's hard to debug because RStudio doesn't return any obvious error messages.

**Comment by olsgaard** [comment]
@gaborcsardi I forgot to test in terminal.

It appears to be working when running from R using the terminal, and only fails from within RStudio.

**Comment by hadley** [comment]
These types of random crashes are typically because you have incompatible binary versions of packages installed, and often resolve if you blow away your library and start from scratch.

**Comment by RolandASc** [comment]
For the record and others ending up here, most likely these issues were caused by jeroen/commonmark#12.

(I ran into this issue because someone here was unfortunate enough to use the MRAN snapshot as of Dec 1st 2018... with `commonmark` 1.7 everything works fine.)
