### ISSUE TITLE
mysterious exception in roxygen2:::read.description

### ISSUE THREAD

**Issue by jpritikin** [klutometis/roxygen#808]
Using roxygen2 6.1.0 and R 3.5.0, `roxygen2:::read.description("DESCRIPTION")` is producing an unhelpful error, `Error in .f(.x[[i]], ...) : attempt to apply non-function`

My DESCRIPTION is attached,
[DESCRIPTION.txt](https://github.com/klutometis/roxygen/files/2496056/DESCRIPTION.txt)

**Comment by gaborcsardi** [comment]
Can you please include  a `traceback()` from after  the error.

**Comment by jpritikin** [comment]
The reason I opened the issue with this example is that I couldn't figure out how to get a detailed trackback. The RStudio Debug/On Error option doesn't help. Surely you are more familiar with the code and can step into it?

**Comment by gaborcsardi** [comment]
It does not fail for me.

**Comment by jpritikin** [comment]
Ah ha! I bet there is some dependency where you have not mandated a high enough version. Investigating.

**Comment by gaborcsardi** [comment]
Can you run `document()` manually, and then get a traceback? Thanks.

**Comment by jpritikin** [comment]
I upgraded all the packages mentioned by roxygen2 as dependencies and the problem disappeared. Thanks.
