### ISSUE TITLE
Unbalanced backticks in Rd for a [link text][pkg::object]-style link

### ISSUE THREAD

**Issue by jennybc** [klutometis/roxygen#813]
This backtick behaviour: 

```
methods::`structure-class`
```

is inspired by how I would get help, e.g. by `` ?methods::`structure-class` ``

But the trailing backtick goes missing in the Rd docs.

I note that I got unstuck by *not* using backticks around `structure-class`. But it feels like these backticks should be tolerated / not mangled, since everything else in your experience suggests they are necessary or at least a good idea.

``` r
library(roxygen2)

roc_proc_text(
  rd_roclet(), "
    #' Title
    #'
    #' Description, see [`matrix`][methods::`structure-class`].
    #' @md
    foo <- function() {}"
)[[1]]
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in RtmpiHM2q1/file13dc854fab817
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo()
#> }
#> \description{
#> Description, see \code{\link[methods:`structure-class]
#> {matrix}}.
#> }
```

<sup>Created on 2018-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This Rd leads to the [following WARNING on travis](https://travis-ci.org/tidyverse/tibble/jobs/444840369#L1271-L1275) but not for me locally (macOS) and I have no idea why.

```
❯ checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'as_tibble.Rd':
    ‘[methods:`matrix-class]{matrix}’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.
```

**Comment by gaborcsardi** [comment]
Is 
```
\code{\link[methods:`structure-class`]{matrix}}
```
actually correct Rd at all? It does not seem so, it generates this error:
```
Link `structure-class` in package methods could not be located
```

I mean, it is syntactically correct, but will link to the wrong place. So we would need to remove both backticks. TBH this seems too much for me, especially, that this does not make any visual difference in the output.

Yes, ideally, the trailing backtick should be kept, this might just be some bad Rd-Md interaction. I think we should just not write markup in the ref part.

**Comment by jennybc** [comment]
I guess we should solve this with documentation then.

I wasn't using backticks for formatting reasons. I assumed that I actually **had** to use backticks around `structure-class` because they are absolutely required when doing `` ?methods::`structure-class` ``.

It's super-confusing (and not our problem, I guess) that you **must** use backticks to get help in an interactive session and you **must not** use them to create a link to that very same help topic 🤷‍♀️

**Comment by gaborcsardi** [comment]
Oh, right. That's  actually a thing in `?` I think. Because `methods::structure-class` is not an R object, it is just a documentation thing:
```r
❯ methods::`structure-class`
Error: 'structure-class' is not an exported object from 'namespace:methods'

❯ methods:::`structure-class`
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'structure-class' not found
```

But yeah, we can add some more examples or explanation, AFAIK there is only one example here: https://github.com/klutometis/roxygen/blob/56aa9b7ac64ad7a01fd98a8f5b14d86f08d18f1b/vignettes/markdown.Rmd#L167

**Comment by gaborcsardi** [comment]
> it is just a documentation thing:

And more importantly the backticks are not an Rd thing, it is a `?` thing. (Not even `help()` AFAICT.)  So yeah, it is a bit messed up.

**Comment by jennybc** [comment]
The bullet list in that vignette is one of my most-read things: "Markdown notation can be used to create links to other manual pages. There are six kinds of links: ..." This sits in my bookmarks bar at all times.

Maybe I would have seen the thing that helps me if we just added the S3/S4 class as a continuation of the list? I'm happy to make a PR.

You can also just close this if we decide it's my problem / user error.

**Comment by gaborcsardi** [comment]
I think a PR would be great. There is also a table in the source  code: https://github.com/klutometis/roxygen/blob/56aa9b7ac64ad7a01fd98a8f5b14d86f08d18f1b/R/markdown.R#L249
Maybe we could just brush it up and include that in the vignette? But I don't mind, up to you.

**Comment by jennybc** [comment]
Do you have the power to assign this to me? I will make the table I wish to see in this world.
