### ISSUE TITLE
Issues with math latex formatting

### ISSUE THREAD

**Issue by benholmgren** [klutometis/roxygen#816]
In the documentation for Roxygen2 it says that math equations can be made using standard Latex inside of \eqn{} or \deqn{}. This is no issue for simple equations, but I've been unable to use standard latex to make more specific math formatting in my documentation, like for example just trying to format an integral. For example, the simple latex integral from 0 to 4 in a roxygen comment:
 \deqn{$$\int_{0}^{4} x^2 dx$$}
doesn't provide an integral symbol, rather it just outputs the code inside of the brackets. 

The same is true if only one dollar sign is used, and if no dollar signs are used inside of the \deqn{} brackets. I have been unable to find a solution to this and was wondering if there was a way to use specific latex math formatting to present more attractive documentation of formulas.

**Comment by gaborcsardi** [comment]
Please provide a reproducible example. E.g. a package on GitHub that shows this behavior.
