### ISSUE TITLE
feature request: documenting default argument values

### ISSUE THREAD

**Issue by IndrajeetPatil** [klutometis/roxygen#819]
Is there any possibility that `roxygen2` can automatically add the default values for function arguments in the `.Rd` files?

For example,let's see this is the function:
```r
foo <- function(x, d = 1) {
return(x + d)
}
```

In this case, I usually write something like-
```r
#' @param x A numeric.
#' @param d A constant numeric value to add to `x` (Default : `1`).
```

But typically there are scores of such arguments with set default values and manually doing it means-

- this will be highly time-consuming 
- this will be highly error-prone since I can change the default value (`d = 2`) and forget to update the documentation 

If `roxygen2` can automatically add the default values at the end of the `param` description text, that would be really neat.

**Comment by gaborcsardi** [comment]
Well, the defaults are already in the manual, in the _Usage_ section. I agree that it can be nice to have them in the _Arguments_ section as well, but I am not sure how easy that would be to implement. Probably not too bad.

> this will be highly error-prone since I can change the default value (d = 2) and forget to update the documentation

Yes, `R CMD check` will catch discrepancies in the _Usage_ section,  though.

**Comment by hadley** [comment]
To me, repeating in the argument section is not terribly useful, and will require a decent amount of work because we'd need some package wide option to control the behaviour and give the user control over the precise appearance.

**Comment by IndrajeetPatil** [comment]
FWIW, `{plumber}` annotations do this.

For example, annotations for the following function signature:

<img width="467" alt="Screenshot 2023-09-20 at 12 17 26" src="https://github.com/r-lib/roxygen2/assets/11330453/2334ae03-d62e-4ca8-8612-dd2eefb6b708">

are rendered in the docs like so:

<img width="783" alt="Screenshot 2023-09-20 at 12 16 19" src="https://github.com/r-lib/roxygen2/assets/11330453/609b099d-a168-4b5d-bae5-aa16a72d9211">
