### ISSUE TITLE
Allow to control order of useDynLib lines in NAMESPACE file

### ISSUE THREAD

**Issue by SoerenXD** [klutometis/roxygen#821]
When generating the NAMESPACE file, the useDynLib lines (created with @useDynLib)  are ordered lexically by the name of the shared object.
However, the order of  loading the shared objects matters if there are dependencies between the shared objects, such as when functions from external libraries need to be called.
There should be a way to control the order of these lines. Probably just not sorting them and recommend to place all the @useDynLib calls in the right order in one location.
( [See also:](https://stackoverflow.com/questions/53171756/)

**Comment by SoerenXD** [comment]
I agree it is not a very frequent usecase, but if is your usecase it is pretty annoying. `@rawNamespace` is no workaround. The lines in the NAMESPACE files always get sorted lexically ([see:](https://github.com/klutometis/roxygen/blob/6b9582ac56002cd5c990530f603fe1bf987c3bbe/R/namespace.R#L32) )

**Comment by gaborcsardi** [comment]
> `@rawNamespace` is no workaround. The lines in the NAMESPACE files always get sorted lexically

Can you please try it like this:

```
#' @rawNamespace useDynLib(foo); useDynLib(bar)
```

**Comment by SoerenXD** [comment]
Perfect! That works, thank you very much.

**Comment by gaborcsardi** [comment]
We might want to document the workaround, as it is not obvious, so I'll leave this issue open.

**Comment by hadley** [comment]
This seems of relatively rare use, and it's not clear where we would document, so I'm going to close for now.
