### ISSUE TITLE
Wish: document infix-function with optional extra arguments, without usage-tags

### ISSUE THREAD

**Issue by EmilBode** [klutometis/roxygen#823]
In a comment on [SO](https://stackoverflow.com/questions/8873514/documenting-setter-functions-with-roxygen), from 2012, I read "you should never need to use @usage - any time you do it is a bug in roxygen2 and you should file a bug report", so that's why I'm posting now, even though I think my problem is an edge-case.
And furthermore, I'm not sure if what I would ideally want is even possible, or that it violates documentation requirements. Anyway, my situation:

I've written an infix-function, with an optional extra argument:
````
`%mod%` <- function(x,y, tolerance = sqrt(.Machine$double.eps))
````
(This function calculates modulo, but with some tolerance for rounding error, so 9.1 %mod% .1 == 0 instead of (very nearly) .1, as 9.1 %% .1 gives).
I expect any users to rarely use the parameter "tolerance", which is why I made it an infix.
But it is there, and R cmd-check expects all arguments to be in the docs.
Ideally, I'd like my usage sections to read something like this:
````
x %mod% y
`%mod%`(x, y, tolerance = sqrt(.Machine$double.eps))
````

However, if I don't specify a @usage section, roxygen2 only documents `x %mod% y`
And devtools::check() then complains (rightfully so) that my argument "tolerance" is undocumented.
I've found the only way to get rid of this warning is using @usage, with the full parameter list.

So I have 2 questions:
1. Could roxygen2 handle this automatically, without @usage?
2. Is there any way to document the 2 different calling forms? With multiple lines of @usage, my docs look good to me, but then devtools::check() also complains. (although it's not really an roxygen2 issue, but maybe you could help me)

**Comment by hadley** [comment]
In this case, I would recommend making two separate functions, one infix, and one prefix. I think your current approach is a cool idea, but it's just fighting against existing convention a bit too much.
