### ISSUE TITLE
@inheritParams on single parameters when multiple parameters match?

### ISSUE THREAD

**Issue by IndrajeetPatil** [klutometis/roxygen#824]
Close this issue if it is similar to https://github.com/klutometis/roxygen/issues/113, but this is a related question I found that I've also been struggling with-
https://stackoverflow.com/questions/47782004/how-to-use-inheritparams-on-single-parameters-when-multiple-parameters-match

**Comment by hadley** [comment]
Same as in #113; it seems like it would be a lot of work, and roxygen2 isn't getting a lot of developer attention at the moment.
