### ISSUE TITLE
warning: missing name/title. Skipping

### ISSUE THREAD

**Issue by IndrajeetPatil** [klutometis/roxygen#825]
Often I want to create a copy of a function because I know that users might be confused about the exact spelling of the function (think `dplyr::summarise` and `dplyr::summarize`). In that case, I do something like the following-
```r

#' @name foo1
#' @title foo1
#' @export
foo1 <- function(x) {
   print(x)
}

#' @rdname foo2
#' @export

foo2 <- foo1
```

But this gives the following warning for `devtools::document()`-
```
Warning: foo2.Rd is missing name/title. Skipping
```

Is it possible in this case for `foo2` to inherit `foo1`'s `name` and `title` without me having to copy-paste the same thing, which will be more prone to error?

**Comment by gaborcsardi** [comment]
Don't you just want to create a single manual page for both? That would be much simpler, no?

```r
#' Foo1 is foo bar
#'
#' @title foo1
#' @export
foo1 <- function(x) {
   print(x)
}

#' @rdname foo1
#' @aliases foo1
#' @export

foo2 <- foo1
```

(untested)
