### ISSUE TITLE
Inheriting Roxygen2 documentation for multiple arguments doesn't work as expected

### ISSUE THREAD

**Issue by IndrajeetPatil** [klutometis/roxygen#826]
This is kind of relevant to this [question](https://stackoverflow.com/questions/39762443/inherit-roxygen2-documentation-for-multiple-arguments-in-r-package), but not really.

If I have the same documentation, for multiple arguments, `roxygen2` takes care of this
```r
#' @rdname foo1
#' @param color,colour Color name to print.

foo1 <- function(color = NULL, colour) {
  color <- color %||% colour
  print(color)
}
```
and the `.Rd` file looks like the following-
```
\item{corr.method, type}{Color name to print.}
```
But inherit this documentation in another function, **this works** 
```r
#' @rdname foo2
#' @inheritParams foo1

foo2 <- function(color = NULL, colour) {
  foo1(color = color, colour = colour)
}
```
but produces duplication in the `.Rd` file-
```r
\item{color}{Color name to print.}
\item{colour}{Color name to print.}
```
Any way to avoid such duplication?

**Comment by maurolepore** [comment]
Same here

**Comment by hadley** [comment]
Yes, this is currently unsupported.
