### ISSUE TITLE
allow customization of '@family' prefix

### ISSUE THREAD

**Issue by kevinushey** [klutometis/roxygen#830]
When using e.g.

    #' @family foo

The documentation gets an entry in the seealso section as:

    Other foo: <...>

I'd like to be able to customize the prefix, so that I could just write e.g.

    #' @family Environment management

and just have a plain old:

    Environment management: <...>

ie, without the `Other:` prefix. Does that seem sensible?

tl;dr: "Other:" isn't always a great prefix and I'd like to customize that somehow.

**Comment by kevinushey** [comment]
More generally, it would be 'nice' to be able to map family names (e.g. 'foo') to a particular prefix / label for when that set of functions are rendered.

**Comment by hadley** [comment]
I think this is a reasonable request, but I just don't see where you'd define the lookup. If you can think of a reasonable place to store that data, I'd consider implementing it.

**Comment by kevinushey** [comment]
How would you feel about a subfolder like `meta-roxygen` that encoded this in some way? E.g. we could have `meta-roxygen/family.json` and we could map family names to prefixes there. (or it could just be an .R file, or some other appropriate representation)

**Comment by hadley** [comment]
I wonder if we could put that in `man/` or `man/roxygen`?

**Comment by kevinushey** [comment]
I like `man/roxygen`. I'll prototype something.
