### ISSUE TITLE
@templateVar value cannot span multiple lines

### ISSUE THREAD

**Issue by nteetor** [klutometis/roxygen#832]
I was surprised to find `@templateVar`'s value cannot span multiple lines as both `@templateVar` and `@param` use the same [`tag_name_description`](https://github.com/klutometis/roxygen/blob/be3ef309381923e64337c3324510746990fde62f/R/tag.R#L156) specification. The value is cutoff after the first line. I will see about submitting a PR if I can make any headway.

**Comment by hadley** [comment]
I'd probably mark templates as questioning these days; so I'm not sure if I want to increase their complexity (but if you did come up with a reasonably simple PR, I'd consider it).
