### ISSUE TITLE
rd comments in @examples section

### ISSUE THREAD

**Issue by nteetor** [klutometis/roxygen#839]
Is there a convention for not escaping `%`s inside the `@examples` section? 

I have a package where an examples section includes some rd comments. But, because all `%`s are escaped, the package in question fails a check due to unexpected symbols in the examples section. 

```R
#' @examples
#' 
#' % An rd comment
#' sample_code()
#'
sample_code <- function() {
  NULL
}
```

**Comment by tbates** [comment]
can you edit the issue and supply example code?

**Comment by nteetor** [comment]
I see I did not make myself clear enough. I was hoping `%` comments under the `@examples` section could behave as they do elsewhere in a roxygen block.

```R
#' Parse tokens
#'
#' Parse result of [tokenize()].
#'
#' % This is ignored.
#'
#' @param tokens A list of tokens.
#'
#' @keywords internal
#' @export
#' @examples
#'
#' # % I hope I don't appear in the help page.
#' parse()
#' 
```

![image](https://user-images.githubusercontent.com/3228369/59293067-6b78e900-8c4c-11e9-94f8-c4a6d1a3b476.png)

**Comment by tbates** [comment]
then you should just say

```R
#' @examples
#'
# I am just a regular source comment (no #' preamble), and I won't appear in the help page.
#' parse()
```

issue should be closed now

**Comment by nteetor** [comment]
Great! And this will ensure the comment is also included in the roxy block object parsed by roxygen?
