### ISSUE TITLE
Feature Proposal: Type Checking

### ISSUE THREAD

**Issue by SteveBronder** [klutometis/roxygen#845]
This proposal is to allow users to add type checking in their docs with a `@contract` tag.

I recently came across the python package [contract](https://github.com/AndreaCensi/contracts). From the description:

> PyContracts is a Python package that allows users to declare constraints on function parameters and return values. It supports a basic type system, variables binding, arithmetic constraints, and has several specialized contracts (notably for Numpy arrays).

So type hinting but actually doing things, pretty dang cool!

I was staring at the below example for a bit and thinking, "Gosh it would be very rad to have this in R"

```python
@contract
def my_function(a, b):
    """ Function description.
        :type a: int,>0
        :type b: list[N],N>0
        :rtype: list[N]
    """
    ...
```

Suddenly `TrianglesAndMathInMyFaceMeme.jpg` why can't we do that in roxygen???

```R
#' Function description.
#' @contract
#' @param a [int, min > 0] A very important number.
#' @param b [list, length > 0] A very important list.
#' @return [vector, type = numeric] A very important vector.
my_function = function(a, b){
...
}
```

I think the easiest way to do this would be to add a function to the users function. Though this sounds kind of invasive it would look something like

```R
#' Function description.
#' @contract
#' @param a [int, min > 0] A very important number.
#' @param b [list, length > 0] A very important list
#' @return [vector, type = numeric] A very important vector
my_function = function(a, b){
# adds type checking
contract_my_function()
}
```

The `contract_my_function()` would look into it's parents frame getting all function inputs. It could use something like [checkmate](https://github.com/mllg/checkmate) to then build the assertion rules to pass or fail functions.

idk if it would be better in roxygen or as it's own package, but either way would like like to know how the roxygen team feels about something like the above. It feels like a good idea, though adding stuff to peoples code seems a bit aggressive.

Thanks for reading!

**Comment by SteveBronder** [comment]
(ftr I'm volunteering my time to do this if the roxygen team is too busy)

**Comment by gaborcsardi** [comment]
Some of us were thinking about this already, see e.g. https://github.com/gaborcsardi/argufy which contains two completely different implementations, but we were not satisfied with what we ended up with. Another approach is here: https://github.com/jimhester/typecheck

Personally, I think it would be useful if you wanted to pursue this. I think ideally it should be in its own package, using a new Roxygen roclet.

I think the challenge is to make it user-friendly, but at the same time not too hacky.

**Comment by SteveBronder** [comment]
Thanks for the info! Yeah I've tried thinking seven ways to Sunday how to do this in a 'not bad' way. I'll read over what you folks have worked on and see if I can cook up anything interesting.

Going to close this issue and will update if I can get a prototype running that looks reasonable.
