### ISSUE TITLE
Enable reference-style links to fully external URLs

### ISSUE THREAD

**Issue by jennybc** [klutometis/roxygen#849]
It would be nice to be able to use reference style links for external URLs. Why? Because sometimes they are incredibly long and/or appear in multiple places and reference style would eliminate ugly long lines and repetition.

```
#' I want to link to [this][external-thing].
#'
#' [external-thing]: http://example.com/some/incredibly/long/link/that/goes/on/and/on/and/on/forever  "Optional Title Here"
```

Right now this clashes with the way this style of link has been commandeered for linking to other help topics.

**Comment by hadley** [comment]
I think unfortunately that this would be too hard to implement — we'd have to develop a convention for where in the roxygen block these would live, and then do some gymanstics with commonmark to get all the data into one place.
