### ISSUE TITLE
function names not exported in NAMESPACE despite export

### ISSUE THREAD

**Issue by gdurif** [klutometis/roxygen#852]
Hi,
I have an issue, the functions of my package are not exported in the NAMESPACE file despite the use of @export, c.f example below:

```r
#' Hi, I'm not exported!
#'
#' @param txt       what to say
#'
#' @export
hello <- function(txt = "world") {
    cat("Hello, ", txt, "\n")
}
```

I try to generate the doc with `devtools::document` or `roxygen2::roxygenize` from Rstudio or command line.

The problem is reproducible with `roxygen2_6.1.1` (last version available on CRAN) and `roxygen2_6.1.1.9000` (last version available on Github). However, there is no problem with `roxygen2_6.0.1` (previous version available on CRAN).

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] roxygen2_6.1.1

loaded via a namespace (and not attached):
 [1] compiler_3.5.3  backports_1.1.3 R6_2.4.0        magrittr_1.5   
 [5] rprojroot_1.3-2 tools_3.5.3     Rcpp_1.0.1      xml2_1.2.0     
 [9] stringi_1.4.3   stringr_1.4.0   commonmark_1.7
```

**Comment by gaborcsardi** [comment]
You'll need to show us a reproducible example, i.e. a link to the repo in which this does not work.

**Comment by gdurif** [comment]
Sorry for the delay of my response, here is the repo with the source of my package <https://github.com/gdurif/pCMF>

At the project root, I run `devtools::document("pkg")

**Comment by gaborcsardi** [comment]
I can see your exported functions right here: https://github.com/gdurif/pCMF/blob/a6e50bafe5f673f3e5e6ebfa9d671424c6c83826/pkg/NAMESPACE#L3-L17

**Comment by gdurif** [comment]
I used roxygen2 version 6.0.1 to generate my package source, to be able to release it. However, if I use v6.1.1 or 6.1.1.9000 the functions are not exported anymore

**Comment by gaborcsardi** [comment]
I just run `devtools::document()` with roxygen2 6.1.1 and it seemed to work fine. This is a freshly cloned repo:

```r
❯ R -q -e 'packageVersion("roxygen2")'
> packageVersion("roxygen2")
[1] ‘6.1.1’
>
>

/tmp/pCMF/pkg prod*
❯ R -q -e 'devtools::load_all()'
> devtools::load_all()
Loading pCMF
>
>

/tmp/pCMF/pkg prod*
❯ R -q -e 'devtools::document()'
> devtools::document()
Updating pCMF documentation
Writing NAMESPACE
Loading pCMF
Writing NAMESPACE
>
>

/tmp/pCMF/pkg prod*
❯ grep export NAMESPACE
export(generate_count_matrix)
export(generate_factor_matrix)
export(getU)
export(getV)
export(graphU)
export(graphV)
export(matrix_heatmap)
export(matrix_plot)
export(pCMF)
export(prefilter)
export(run_gap_factor)
export(run_poisson_nmf)
export(run_sparse_gap_factor)
export(run_zi_gap_factor)
export(run_zi_sparse_gap_factor)
```

**Comment by gaborcsardi** [comment]
Can you please run exactly the same, and then copy the output here? Thanks.

**Comment by gdurif** [comment]
Ok, I guess there is something wrong with my machines (I tried on 2 different). I did the same on a fresh repo and clean environment with roxygen2 v6.1.1 and it does not work, here are my session info:
```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        rstudioapi_0.10   xml2_1.2.0        magrittr_1.5     
 [5] roxygen2_6.1.1    usethis_1.4.0     devtools_2.0.1    pkgload_1.0.2    
 [9] pCMF_1.2.1        R6_2.4.0          rlang_0.3.2       stringr_1.4.0    
[13] tools_3.5.3       pkgbuild_1.0.3    sessioninfo_1.1.1 cli_1.1.0        
[17] withr_2.1.2       remotes_2.0.2     commonmark_1.7    assertthat_0.2.1 
[21] digest_0.6.18     rprojroot_1.3-2   crayon_1.3.4      processx_3.3.0   
[25] purrr_0.3.2       callr_3.2.0       fs_1.2.7          ps_1.3.0         
[29] memoise_1.1.0     glue_1.3.1        stringi_1.4.3     compiler_3.5.3   
[33] desc_1.2.0        backports_1.1.3   prettyunits_1.0.2
```

I will dig deeper and see what I can find, thanks for your anser.

**Comment by gaborcsardi** [comment]
What do you mean by "does not work", and also can please run the commands I did and copy the output here? Thanks.

**Comment by gdurif** [comment]
Here is the output of the commands that you run, now the export are generated in the `NAMESPACE` file:
```bash
$ cd pCMF/pkg
$ pwd
/xxxx/xxxx/tmp/pCMF/pkg
$ R -q -e 'packageVersion("roxygen2")'
> packageVersion("roxygen2")
[1] ‘6.1.1’
> 
> 
$ R -q -e 'devtools::load_all()'
> devtools::load_all()
Loading pCMF
> 
> 
$ R -q -e 'devtools::document()'
> devtools::document()
Updating pCMF documentation
Writing NAMESPACE
Loading pCMF
Writing NAMESPACE
> 
> 
$ grep export NAMESPACE
export(generate_count_matrix)
export(generate_factor_matrix)
export(getU)
export(getV)
export(graphU)
export(graphV)
export(matrix_heatmap)
export(matrix_plot)
export(pCMF)
export(prefilter)
export(run_gap_factor)
export(run_poisson_nmf)
export(run_sparse_gap_factor)
export(run_zi_gap_factor)
export(run_zi_sparse_gap_factor)
```

I did not use `devtools::load_all`, I guess this is the reason. Thanks

**Comment by stevecondylios** [comment]
@gaborcsardi Thanks, I had the same problem and your instructions fixed perfectly. 

Would you mind explaining why the functions weren't appearing before the additional steps? (the reason I ask is, in all cases I've encountered except this one, Build -> Build Source Package has populated `NAMESPACE`, but in this case, it took these additional steps)

In case it's relevant
```R
> packageVersion("roxygen2")
[1] ‘7.0.2’
```

**Comment by gaborcsardi** [comment]
@stevecondylios I don't know, hard to say from here and retrospectively. My instructions were mostly for diagnostics, not fixing. In any case, to generate the `NAMESPACE` file, roxygen needs to be able to load your package correctly, and maybe it could not.

"Build Source Package" does run `devtools::document()` but I am not sure if it always did.

In any case, if this happens again, and you can reproduce it, please open a new issue. Thanks.

**Comment by dancingfrog** [comment]
@frareb Thank you, that was a good thing to check!

I also had an issue with "@export" functions not  being exported during `devtools::document()`, and the cause actually seems to have been an overly ambitious `.Rbuildignore` file that ended up excluding some of my R source files. So, check that file as well.
