### ISSUE TITLE
Creating PDF version Warning: Replacing ... does not exist, replaced by a fixed one.

### ISSUE THREAD

**Issue by phargarten2** [klutometis/roxygen#853]
The \code{\link[pkg]{function}} syntax in a list throws a warning that a link cannot be found and is replaced with fixed text when creating a pdf. For instance, in this function: 

#'@title I love dogs
#'@description A function about dog stats
#'@details
#' A dataframe of statistics of individual chemical analysis is returned: \describe{
  #'  \item{component.name}{name of the component}
  #'  \item{estimate}{the estimate }
  #'  \item{Std.Error}{the standard error}
  #'  \item{AIC}{Model Fit. See \code{\link[stats]{AIC}}.}
  #'  }
show.examples <- function() { }

When I use rcmdcheck::rcmdcheck()  to  make a pdf manual for my package (that consists of this one function), I receive this warning in Rdlatex.log : 

pdfTeX warning (dest): name{Rfn.AIC} has been referenced but does not exist, replaced by a fixed one

I understand that to make a PDF document the manuel files are first converted to LaTex, and then to  a PDF document. But the link is indeed correct for the help file says 
# AIC {stats}	R Documentation

Do you know why LaTex cannot find the right hyperlink? I noticed that it adds "Rfn" in front ... could this be a reason why it cannot find some LaTex files?

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
