### ISSUE TITLE
Provide a way to concisely document the API of a package

### ISSUE THREAD

**Issue by krlmlr** [klutometis/roxygen#858]
so that changes can be tracked and compared between releases.

According to https://principles.tidyverse.org/function-interface.html, the API consists of:

- (Function) name
- Inputs
- Output value
- Errors
- Side effects

The [API roclet](https://github.com/r-lib/pkgapi/blob/2464d224630c6bc1b7e68b5448096a0baebbe8ec/R/roclet.R) in {pkgapi} documents the first two items in a new `API` file. This format (one line per function) won't be sufficient if we consider output, errors and side effects, but it seems clear that {roxygen} is a good tool to create this.

Related to {vctrs} which provides ways to specify/check the type of an object.

We should strive for consistency with the [RDocTaskForce](https://github.com/RDocTaskForce) R Consortium project.

**Comment by hadley** [comment]
I think this needs to wait until we have a more precise notion of what the types and side-effects are. We're at least a few versions of vctrs away from this.
