### ISSUE TITLE
NAMESPACE overwritten when externally authored

### ISSUE THREAD

**Issue by drjxf** [klutometis/roxygen#864]
Generally Roxygen does not overwrite an externally authored NAMESPACE file. However, if a Roxygen comment block contains @import (and maybe other tags) the NAMESPACE file will be overwritten.

The offending code seems to be in namespace.R, line 36.

**Comment by hadley** [comment]
That line of code looks fine to me - it immediately returns if there are no lines to write, or if the `NAMESPACE` was not created by roxygen2. If you are seeing a problem in practice, I'd recommend creating a reprex and filing a new issue.
