### ISSUE TITLE
New `@testthat` tag

### ISSUE THREAD

**Issue by mikldk** [klutometis/roxygen#865]
I really enjoy having documentation of a function at its definition. For a while I have wished for something similar for tests (not for all tests, but for some). What do you think of the idea of introducing a new `@testthat` that can generate [testthat](https://github.com/r-lib/testthat) tests automatically? E.g. for the `str_length` at this repo's `README`:

```
@testthat expect_equal(str_length(letters), nchar(letters))
@testthat expect_equal(nchar("roxygen"), 7)
```

I'm not sure if there should be multiple `@testthat`'s or just a single; this was just to illustrate the idea.

What do you think of something like that?

If `roxygen2` was extendable, i.e. a package could provide a new roclet, then I think that would make a neat little add-on package. But as far as I understand the `roxygen2` process, then that's not the case and additions like the one suggested above need to be implemented in `roxygen2` directly. Is that correct?

**Comment by nteetor** [comment]
I have back burner-ed reworking the [tinsel](https://github.com/nteetor/tinsel) package to do just this. Seeing this issue now I'm torn between excitement and an "aw shucks" feeling.  

Inline tests would be great for getting package testing off the ground and could be used to generate testthat folder structure. If this were the case, how would generated tests be kept in sync with more complex tests in the testthat folder? I suspect some tests are complex and not suitable for inline inclusion. If this is not the case, are users inadvertently encouraged to over-simplify their tests?

I imagined {tinsel} (or similar tool) would allow flexible, inline testing while a package's functionality is still experimental. Then once a package's API standardizes the developer would generate a testthat structure and drop the inline tests.

**Comment by mikldk** [comment]
Great points, thanks.

I was imagining auto-tests and "normal" tests living side by side. Auto tests could have have prefix e.g. `test-auto-fn_name.R` and a comment at the top ("auto generated by ...") as `NAMESPACE` does. And then all files named `test-auto-*.R` with that comment at the top could be removed at documentation time.

I also imagine that the auto tests were really small and simple, e.g. for testing input validation, whereas the normal tests were larger and tested more complex usage.

But you are absolutely right that there are several problems, and the idea may turn out to be counter productive.

**Comment by hadley** [comment]
roxygen2 is extensible, so there's no reason for this to not live in a separate package. The process of creating your on roclet is not well documented, but hopefully `?roclet` will get you started, and if you run into any problems you can ping me and I'll improve the docs.

**Comment by mikldk** [comment]
Thanks. I have made an experimental package at <https://github.com/mikldk/roxytest>. It is in no way polished or anything, yet.
