### ISSUE TITLE
Uninformative error when leaving an empty @param

### ISSUE THREAD

**Issue by JazzyPierrot** [klutometis/roxygen#869]
Hi, 
Leaving an empty   `#' @param` in a roxygen comment leads to an error with no information at all to identify the problem:
`Error in FUN(X[[i]], ...) : index out of bound`

I believe it could be useful to specify in which comment the error occurs in such situations.

**Comment by tbates** [comment]
Can't replicate in `packageVersion("devtools")` ‘2.0.2’. Help builds fine, and issues a helpful warning about @param needing a value.

Here's a repro file (which should have be provided with the original issue...) Need to save it as .R

```R
#' Fn with hanging @@param
#' @param
#' @export
#' @family Data Functions
checkMe <- function() {}
```
I get
> Warning: @param [/Users/tim/bin/umx/R/hang_param.R#3]: requires a value

[hang_param.txt](https://github.com/klutometis/roxygen/files/3272160/hang_param.txt)

**Comment by JazzyPierrot** [comment]
> which should have be provided with the original issue...

Hum, yes, please accept my apologies for that.

Here is one: with an empty line after the @param line. 
```
#' Fn with hanging @@param
#' @param
#'
#' @export
#' @family Data Functions
checkMe <- function() {}
```

I have put that function in the R directory of an empty "test" package and have run "devtools::document()", and get the aforementioned error (in French). 

I indeed get no error and the proper warning with same procedure but without the additional empty line. 
Devtools package version is 2.0.2 as well.

**Comment by tbates** [comment]
A nice user message for this error would require catching white space after param (including a new line), and trimming it out. Then would be treated as the no-value-provided case. (or else require that the value be on the same line as @param - but that would break this, which currently works:

```R
#' param test
#'
#' @description
#' param on new line
#' @param
#' x here I am
#' @return - matrix
#' @export
tmp <- function(x) {
	matrix(1:4, nrow = 2)
}
```

![Screenshot 2019-06-11 18 07 18](https://user-images.githubusercontent.com/736156/59291971-e6a1c580-8c73-11e9-8075-a123dc42f5b4.png)

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(roxygen2)
roc_proc_text(rd_roclet(), "
  #' Title
  #' @param
  #'
  #' @export
  foo <- function() {}"
)
#> Error in FUN(X[[i]], ...): subscript out of bounds
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
