### ISSUE TITLE
`rd.Rmd` vignette references wrong vignette for Markdown documentation

### ISSUE THREAD

**Issue by mikemc** [klutometis/roxygen#871]
While reading the documentation, I noticed that Line 108 of the [rd.Rmd vignette](https://github.com/klutometis/roxygen/blob/master/vignettes/rd.Rmd) refers to the [formatting vignette](https://github.com/klutometis/roxygen/blob/master/vignettes/formatting.Rmd) for discussion of Markdown formatting. However, the formatting vignette does not mention Markdown. Perhaps Line 108 should simply be updated to refer to the [Markdown vignette](https://github.com/klutometis/roxygen/blob/master/vignettes/markdown.Rmd) instead?

**Comment by gaborcsardi** [comment]
Yeah, I think ideally it should refer to both, because (some of) the formatting vignette is relevant to markdown as well. Do you want to submit a PR?

**Comment by mikemc** [comment]
I can submit a PR in the next 1-2 days, just need to find a moment to consider how to properly tie in the formatting vignette.
