### ISSUE TITLE
Support for optional text between arguments/parameters

### ISSUE THREAD

**Issue by mnazarov** [klutometis/roxygen#872]
According to [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Documenting-functions) section on Rd files, it is possible to include text between function arguments (parameters), for example to separate groups of related arguments:
> There may be optional text outside the \item entries, for example to give general information about groups of parameters.

Is there a way to support this in `roxygen2`? I understand it may be complicated, as this doesn't represent a name-description "tag"... If not, are there any other suggestions to achieve visual 'grouping' of parameters?

**Comment by hadley** [comment]
Given the way that parameters are managed internally, which loses the original order, I don't see any obvious way to implement this.
