### ISSUE TITLE
exposing a command line interface using roxygen

### ISSUE THREAD

**Issue by leej3** [klutometis/roxygen#876]
This is related to #858. The idea would be that using adding 
"@exposeas bar" to the roxygen comment lines would create a command line tool (in this case bar) that fulfills  the API specification of the documented function.  The wrapping tool could be called from a shell. This would be enable R functionality to be chained with other tools in a language agnostic way (I am thinking IO specification along the lines of [boutiques](https://boutiques.github.io), Common Workflow Language, or nipype interfaces).

Does this seem feasible? My impression is that currently, to create a command line tool one must right wrapping code that parses command arguments (using the likes of commandArgs,docopt, or argparse among others). This in effect forces one to specify the same interface in two different places. Using roxygen seems like a more elegant approach. 

Please correct me if I'm wrong as I currently need to create some command line tools for a project, and roxygen seems like the clear winner to me for documenting functionality in  a way that nicely integrates with the devtools/rstudio workflow

**Comment by hadley** [comment]
I think this would be best tackled in another package; roxygen2 is already quite big and this is unrelated to the main thrust of the package.
