### ISSUE TITLE
How to write tags and where to look for existing (non standard) ones?

### ISSUE THREAD

**Issue by mamueller** [klutometis/roxygen#878]
As a concrete project, I would like to extend the functionality of the documentation for R4 classes and methods a little bit, if only to document my own code.
 
Use cases are for example:
- a list of constructors for a  certain class automatically linked to the class
- automatic links to methods that are documented separately  both from the class and the generic
...
From a first glance at the roxygen2 code I assume that writing my own 'tags' would be a fairly nonintrusive way to achieve this. 
If this is indeed the case it seems reasonable that other people had similar ideas and wrote their own tags. But I could not find any. 
**Are there any resources about how to find or make one's own tags apart from the source code of the implemented tags?** 

Thanks for your time and the huge amount of work already done

**Comment by hadley** [comment]
There isn't currently, but I just filed an issue so we eventually write something about this: #882
