### ISSUE TITLE
Expose a file argument to roxygen2::roxygenize()

### ISSUE THREAD

**Issue by lorenzwalthert** [klutometis/roxygen#887]
Exposing an API for selected files only would be handy for two reasons:

* parallelization. Have not found any issue on that. Is this a priority?
* Ability to only run it on files that were changed, e.g. as part of a pre-commit hook. That would probably result in a significant speed up. Also, frameworks such as pre-commit.com have built-in parallelization over files, so currently in https://github.com/lorenzwalhtert/pre-commit-hooks, to roxygenize hook is run as many times as there are changed files (because it does not make use of the passed information about files).

Would you consider exporting such a function from the package? Or add a `files`  argument to `roxygen2::roxygenize()`?

**Comment by hadley** [comment]
I don't think it's possible to roxygenise a single file because so much is written with the assumption that the complete package is loaded, and all the documentation is parsed (i.e. all of the inheritance, `@rdname`, ...)

**Comment by hadley** [comment]
Also I think roxygen2 assumes it writes everything in the `man/` directory so it can automatically delete files that it created that are no longer needed.

I think changing this assumption would be too much work to be worthwhile. Instead, I'd suggest profiling to identify bottenecks and then working to speed up the whole package.

**Comment by lorenzwalthert** [comment]
Ok. Thanks.
